
package com.snapstream.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-05-05T12:52:57.690-06:00
 * Generated source version: 2.4.0
 * 
 */
public final class BTVDispatcherSoap_BTVDispatcherSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://www.snapstream.com/WebService", "BTVDispatcher");

    private BTVDispatcherSoap_BTVDispatcherSoap_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = BTVDispatcher.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BTVDispatcher ss = new BTVDispatcher(wsdlURL, SERVICE_NAME);
        BTVDispatcherSoap port = ss.getBTVDispatcherSoap();  
        
        {
        System.out.println("Invoking getEnginesWithChannel...");
        java.lang.String _getEnginesWithChannel_authTicket = "";
        java.lang.String _getEnginesWithChannel_uniqueChannelID = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getEnginesWithChannel__return = port.getEnginesWithChannel(_getEnginesWithChannel_authTicket, _getEnginesWithChannel_uniqueChannelID);
        System.out.println("getEnginesWithChannel.result=" + _getEnginesWithChannel__return);


        }
        {
        System.out.println("Invoking getActiveRecordingsWithChannel...");
        java.lang.String _getActiveRecordingsWithChannel_authTicket = "";
        java.lang.String _getActiveRecordingsWithChannel_uniqueChannelID = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getActiveRecordingsWithChannel__return = port.getActiveRecordingsWithChannel(_getActiveRecordingsWithChannel_authTicket, _getActiveRecordingsWithChannel_uniqueChannelID);
        System.out.println("getActiveRecordingsWithChannel.result=" + _getActiveRecordingsWithChannel__return);


        }
        {
        System.out.println("Invoking getEngines...");
        java.lang.String _getEngines_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getEngines__return = port.getEngines(_getEngines_authTicket);
        System.out.println("getEngines.result=" + _getEngines__return);


        }
        {
        System.out.println("Invoking setSources...");
        java.lang.String _setSources_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _setSources_sources = null;
        port.setSources(_setSources_authTicket, _setSources_sources);


        }
        {
        System.out.println("Invoking getActiveRecordings...");
        java.lang.String _getActiveRecordings_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getActiveRecordings__return = port.getActiveRecordings(_getActiveRecordings_authTicket);
        System.out.println("getActiveRecordings.result=" + _getActiveRecordings__return);


        }

        System.exit(0);
    }

}
