
/*
 * 
 */

package com.snapstream.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-05-05T12:52:57.792-06:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "BTVDispatcher", 
                  wsdlLocation = "file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/BTVDispatcher.asmx.xml",
                  targetNamespace = "http://www.snapstream.com/WebService") 
public class BTVDispatcher extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.snapstream.com/WebService", "BTVDispatcher");
    public final static QName BTVDispatcherSoap = new QName("http://www.snapstream.com/WebService", "BTVDispatcherSoap");
    public final static QName BTVDispatcherSoap12 = new QName("http://www.snapstream.com/WebService", "BTVDispatcherSoap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/BTVDispatcher.asmx.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BTVDispatcher.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/BTVDispatcher.asmx.xml");
        }
        WSDL_LOCATION = url;
    }

    public BTVDispatcher(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BTVDispatcher(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BTVDispatcher() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns BTVDispatcherSoap
     */
    @WebEndpoint(name = "BTVDispatcherSoap")
    public BTVDispatcherSoap getBTVDispatcherSoap() {
        return super.getPort(BTVDispatcherSoap, BTVDispatcherSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BTVDispatcherSoap
     */
    @WebEndpoint(name = "BTVDispatcherSoap")
    public BTVDispatcherSoap getBTVDispatcherSoap(WebServiceFeature... features) {
        return super.getPort(BTVDispatcherSoap, BTVDispatcherSoap.class, features);
    }
    /**
     * 
     * @return
     *     returns BTVDispatcherSoap
     */
    @WebEndpoint(name = "BTVDispatcherSoap12")
    public BTVDispatcherSoap getBTVDispatcherSoap12() {
        return super.getPort(BTVDispatcherSoap12, BTVDispatcherSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BTVDispatcherSoap
     */
    @WebEndpoint(name = "BTVDispatcherSoap12")
    public BTVDispatcherSoap getBTVDispatcherSoap12(WebServiceFeature... features) {
        return super.getPort(BTVDispatcherSoap12, BTVDispatcherSoap.class, features);
    }

}
