
/*
 * 
 */

package com.snapstream.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-05-05T12:53:07.770-06:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "BTVExpiration", 
                  wsdlLocation = "file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/BTVExpiration.asmx.xml",
                  targetNamespace = "http://www.snapstream.com/WebService") 
public class BTVExpiration extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.snapstream.com/WebService", "BTVExpiration");
    public final static QName BTVExpirationSoap12 = new QName("http://www.snapstream.com/WebService", "BTVExpirationSoap12");
    public final static QName BTVExpirationSoap = new QName("http://www.snapstream.com/WebService", "BTVExpirationSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/BTVExpiration.asmx.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BTVExpiration.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/BTVExpiration.asmx.xml");
        }
        WSDL_LOCATION = url;
    }

    public BTVExpiration(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BTVExpiration(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BTVExpiration() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns BTVExpirationSoap
     */
    @WebEndpoint(name = "BTVExpirationSoap12")
    public BTVExpirationSoap getBTVExpirationSoap12() {
        return super.getPort(BTVExpirationSoap12, BTVExpirationSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BTVExpirationSoap
     */
    @WebEndpoint(name = "BTVExpirationSoap12")
    public BTVExpirationSoap getBTVExpirationSoap12(WebServiceFeature... features) {
        return super.getPort(BTVExpirationSoap12, BTVExpirationSoap.class, features);
    }
    /**
     * 
     * @return
     *     returns BTVExpirationSoap
     */
    @WebEndpoint(name = "BTVExpirationSoap")
    public BTVExpirationSoap getBTVExpirationSoap() {
        return super.getPort(BTVExpirationSoap, BTVExpirationSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BTVExpirationSoap
     */
    @WebEndpoint(name = "BTVExpirationSoap")
    public BTVExpirationSoap getBTVExpirationSoap(WebServiceFeature... features) {
        return super.getPort(BTVExpirationSoap, BTVExpirationSoap.class, features);
    }

}
