package org.atgas.sync.media.beyondtv.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.atgas.sync.media.beyondtv.webservice.types.PVSPropertyBag;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-05-05T12:53:07.759-06:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://www.snapstream.com/WebService", name = "BTVExpirationSoap")
@XmlSeeAlso({ObjectFactory.class, ObjectFactory.class})
public interface BTVExpirationSoap {

    @RequestWrapper(localName = "SetDaysLimitsByGuid", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.SetDaysLimitsByGuid")
    @WebMethod(operationName = "SetDaysLimitsByGuid", action = "http://www.snapstream.com/WebService/SetDaysLimitsByGuid")
    @ResponseWrapper(localName = "SetDaysLimitsByGuidResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.SetDaysLimitsByGuidResponse")
    public void setDaysLimitsByGuid(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String guid,
        @WebParam(name = "days", targetNamespace = "http://www.snapstream.com/WebService")
        int days
    );

    @WebResult(name = "GetShowLimitsByGuidResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetShowLimitsByGuid", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetShowLimitsByGuid")
    @WebMethod(operationName = "GetShowLimitsByGuid", action = "http://www.snapstream.com/WebService/GetShowLimitsByGuid")
    @ResponseWrapper(localName = "GetShowLimitsByGuidResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetShowLimitsByGuidResponse")
    public int getShowLimitsByGuid(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String guid
    );

    @RequestWrapper(localName = "SetDriveLimits", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.SetDriveLimits")
    @WebMethod(operationName = "SetDriveLimits", action = "http://www.snapstream.com/WebService/SetDriveLimits")
    @ResponseWrapper(localName = "SetDriveLimitsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.SetDriveLimitsResponse")
    public void setDriveLimits(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bag", targetNamespace = "http://www.snapstream.com/WebService")
        PVSPropertyBag bag
    );

    @WebResult(name = "GetDriveLimitsByNameResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetDriveLimitsByName", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetDriveLimitsByName")
    @WebMethod(operationName = "GetDriveLimitsByName", action = "http://www.snapstream.com/WebService/GetDriveLimitsByName")
    @ResponseWrapper(localName = "GetDriveLimitsByNameResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetDriveLimitsByNameResponse")
    public PVSPropertyBag getDriveLimitsByName(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "name", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String name
    );

    @RequestWrapper(localName = "SetShowLimitsByGuid", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.SetShowLimitsByGuid")
    @WebMethod(operationName = "SetShowLimitsByGuid", action = "http://www.snapstream.com/WebService/SetShowLimitsByGuid")
    @ResponseWrapper(localName = "SetShowLimitsByGuidResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.SetShowLimitsByGuidResponse")
    public void setShowLimitsByGuid(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String guid,
        @WebParam(name = "limit", targetNamespace = "http://www.snapstream.com/WebService")
        int limit
    );

    @WebResult(name = "GetMaxDaysByGuidResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetMaxDaysByGuid", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetMaxDaysByGuid")
    @WebMethod(operationName = "GetMaxDaysByGuid", action = "http://www.snapstream.com/WebService/GetMaxDaysByGuid")
    @ResponseWrapper(localName = "GetMaxDaysByGuidResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetMaxDaysByGuidResponse")
    public int getMaxDaysByGuid(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String guid
    );
}
