
/*
 * 
 */

package com.snapstream.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-05-05T12:53:47.758-06:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "BTVGuideData", 
                  wsdlLocation = "file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/BTVGuideData.asmx.xml",
                  targetNamespace = "http://www.snapstream.com/WebService") 
public class BTVGuideData extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.snapstream.com/WebService", "BTVGuideData");
    public final static QName BTVGuideDataSoap12 = new QName("http://www.snapstream.com/WebService", "BTVGuideDataSoap12");
    public final static QName BTVGuideDataSoap = new QName("http://www.snapstream.com/WebService", "BTVGuideDataSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/BTVGuideData.asmx.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BTVGuideData.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/BTVGuideData.asmx.xml");
        }
        WSDL_LOCATION = url;
    }

    public BTVGuideData(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BTVGuideData(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BTVGuideData() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns BTVGuideDataSoap
     */
    @WebEndpoint(name = "BTVGuideDataSoap12")
    public BTVGuideDataSoap getBTVGuideDataSoap12() {
        return super.getPort(BTVGuideDataSoap12, BTVGuideDataSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BTVGuideDataSoap
     */
    @WebEndpoint(name = "BTVGuideDataSoap12")
    public BTVGuideDataSoap getBTVGuideDataSoap12(WebServiceFeature... features) {
        return super.getPort(BTVGuideDataSoap12, BTVGuideDataSoap.class, features);
    }
    /**
     * 
     * @return
     *     returns BTVGuideDataSoap
     */
    @WebEndpoint(name = "BTVGuideDataSoap")
    public BTVGuideDataSoap getBTVGuideDataSoap() {
        return super.getPort(BTVGuideDataSoap, BTVGuideDataSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BTVGuideDataSoap
     */
    @WebEndpoint(name = "BTVGuideDataSoap")
    public BTVGuideDataSoap getBTVGuideDataSoap(WebServiceFeature... features) {
        return super.getPort(BTVGuideDataSoap, BTVGuideDataSoap.class, features);
    }

}
