
package com.snapstream.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-05-05T12:53:56.121-06:00
 * Generated source version: 2.4.0
 * 
 */
public final class BTVGuideUpdaterSoap_BTVGuideUpdaterSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://www.snapstream.com/WebService", "BTVGuideUpdater");

    private BTVGuideUpdaterSoap_BTVGuideUpdaterSoap12_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = BTVGuideUpdater.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BTVGuideUpdater ss = new BTVGuideUpdater(wsdlURL, SERVICE_NAME);
        BTVGuideUpdaterSoap port = ss.getBTVGuideUpdaterSoap12();  
        
        {
        System.out.println("Invoking startUpdate...");
        java.lang.String _startUpdate_authTicket = "";
        port.startUpdate(_startUpdate_authTicket);


        }
        {
        System.out.println("Invoking getLastAttemptedUpdate...");
        java.lang.String _getLastAttemptedUpdate_authTicket = "";
        java.math.BigInteger _getLastAttemptedUpdate__return = port.getLastAttemptedUpdate(_getLastAttemptedUpdate_authTicket);
        System.out.println("getLastAttemptedUpdate.result=" + _getLastAttemptedUpdate__return);


        }
        {
        System.out.println("Invoking getProgress...");
        java.lang.String _getProgress_authTicket = "";
        javax.xml.ws.Holder<java.lang.Long> _getProgress_getProgressResult = new javax.xml.ws.Holder<java.lang.Long>();
        javax.xml.ws.Holder<java.lang.String> _getProgress_state = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _getProgress_message = new javax.xml.ws.Holder<java.lang.String>();
        port.getProgress(_getProgress_authTicket, _getProgress_getProgressResult, _getProgress_state, _getProgress_message);

        System.out.println("getProgress._getProgress_getProgressResult=" + _getProgress_getProgressResult.value);
        System.out.println("getProgress._getProgress_state=" + _getProgress_state.value);
        System.out.println("getProgress._getProgress_message=" + _getProgress_message.value);

        }
        {
        System.out.println("Invoking setProperty...");
        java.lang.String _setProperty_authTicket = "";
        java.lang.String _setProperty_name = "";
        java.lang.String _setProperty_val = "";
        port.setProperty(_setProperty_authTicket, _setProperty_name, _setProperty_val);


        }
        {
        System.out.println("Invoking tvtvUpdate...");
        java.lang.String _tvtvUpdate_authTicket = "";
        long _tvtvUpdate__return = port.tvtvUpdate(_tvtvUpdate_authTicket);
        System.out.println("tvtvUpdate.result=" + _tvtvUpdate__return);


        }
        {
        System.out.println("Invoking getNextAttemptedUpdate...");
        java.lang.String _getNextAttemptedUpdate_authTicket = "";
        java.math.BigInteger _getNextAttemptedUpdate__return = port.getNextAttemptedUpdate(_getNextAttemptedUpdate_authTicket);
        System.out.println("getNextAttemptedUpdate.result=" + _getNextAttemptedUpdate__return);


        }
        {
        System.out.println("Invoking getLastSuccessfulUpdate...");
        java.lang.String _getLastSuccessfulUpdate_authTicket = "";
        java.math.BigInteger _getLastSuccessfulUpdate__return = port.getLastSuccessfulUpdate(_getLastSuccessfulUpdate_authTicket);
        System.out.println("getLastSuccessfulUpdate.result=" + _getLastSuccessfulUpdate__return);


        }
        {
        System.out.println("Invoking cancelUpdate...");
        java.lang.String _cancelUpdate_authTicket = "";
        port.cancelUpdate(_cancelUpdate_authTicket);


        }
        {
        System.out.println("Invoking getRemoteRecordings...");
        java.lang.String _getRemoteRecordings_authTicket = "";
        long _getRemoteRecordings__return = port.getRemoteRecordings(_getRemoteRecordings_authTicket);
        System.out.println("getRemoteRecordings.result=" + _getRemoteRecordings__return);


        }

        System.exit(0);
    }

}
