
/*
 * 
 */

package com.snapstream.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-05-05T12:53:56.231-06:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "BTVGuideUpdater", 
                  wsdlLocation = "file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/BTVGuideUpdater.asmx.xml",
                  targetNamespace = "http://www.snapstream.com/WebService") 
public class BTVGuideUpdater extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.snapstream.com/WebService", "BTVGuideUpdater");
    public final static QName BTVGuideUpdaterSoap12 = new QName("http://www.snapstream.com/WebService", "BTVGuideUpdaterSoap12");
    public final static QName BTVGuideUpdaterSoap = new QName("http://www.snapstream.com/WebService", "BTVGuideUpdaterSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/BTVGuideUpdater.asmx.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BTVGuideUpdater.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/BTVGuideUpdater.asmx.xml");
        }
        WSDL_LOCATION = url;
    }

    public BTVGuideUpdater(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BTVGuideUpdater(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BTVGuideUpdater() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns BTVGuideUpdaterSoap
     */
    @WebEndpoint(name = "BTVGuideUpdaterSoap12")
    public BTVGuideUpdaterSoap getBTVGuideUpdaterSoap12() {
        return super.getPort(BTVGuideUpdaterSoap12, BTVGuideUpdaterSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BTVGuideUpdaterSoap
     */
    @WebEndpoint(name = "BTVGuideUpdaterSoap12")
    public BTVGuideUpdaterSoap getBTVGuideUpdaterSoap12(WebServiceFeature... features) {
        return super.getPort(BTVGuideUpdaterSoap12, BTVGuideUpdaterSoap.class, features);
    }
    /**
     * 
     * @return
     *     returns BTVGuideUpdaterSoap
     */
    @WebEndpoint(name = "BTVGuideUpdaterSoap")
    public BTVGuideUpdaterSoap getBTVGuideUpdaterSoap() {
        return super.getPort(BTVGuideUpdaterSoap, BTVGuideUpdaterSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BTVGuideUpdaterSoap
     */
    @WebEndpoint(name = "BTVGuideUpdaterSoap")
    public BTVGuideUpdaterSoap getBTVGuideUpdaterSoap(WebServiceFeature... features) {
        return super.getPort(BTVGuideUpdaterSoap, BTVGuideUpdaterSoap.class, features);
    }

}
