
package com.snapstream.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-05-05T12:54:40.135-06:00
 * Generated source version: 2.4.0
 * 
 */
public final class BTVLibrarySoap_BTVLibrarySoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://www.snapstream.com/WebService", "BTVLibrary");

    private BTVLibrarySoap_BTVLibrarySoap12_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = BTVLibrary.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BTVLibrary ss = new BTVLibrary(wsdlURL, SERVICE_NAME);
        BTVLibrarySoap port = ss.getBTVLibrarySoap12();  
        
        {
        System.out.println("Invoking addFolder...");
        java.lang.String _addFolder_authTicket = "";
        java.lang.String _addFolder_sFolder = "";
        port.addFolder(_addFolder_authTicket, _addFolder_sFolder);


        }
        {
        System.out.println("Invoking editMedia...");
        java.lang.String _editMedia_authTicket = "";
        java.lang.String _editMedia_fullName = "";
        com.snapstream.types.PVSPropertyBag _editMedia_bag = null;
        port.editMedia(_editMedia_authTicket, _editMedia_fullName, _editMedia_bag);


        }
        {
        System.out.println("Invoking getAllClipsWithFilter...");
        java.lang.String _getAllClipsWithFilter_authTicket = "";
        com.snapstream.webservice.LibraryHideOption _getAllClipsWithFilter_hide = null;
        com.snapstream.webservice.LibrarySort _getAllClipsWithFilter_sort = null;
        com.snapstream.webservice.LibrarySortOrder _getAllClipsWithFilter_order = null;
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getAllClipsWithFilter__return = port.getAllClipsWithFilter(_getAllClipsWithFilter_authTicket, _getAllClipsWithFilter_hide, _getAllClipsWithFilter_sort, _getAllClipsWithFilter_order);
        System.out.println("getAllClipsWithFilter.result=" + _getAllClipsWithFilter__return);


        }
        {
        System.out.println("Invoking getLastChange...");
        java.lang.String _getLastChange_authTicket = "";
        long _getLastChange__return = port.getLastChange(_getLastChange_authTicket);
        System.out.println("getLastChange.result=" + _getLastChange__return);


        }
        {
        System.out.println("Invoking getMediaByFullName...");
        java.lang.String _getMediaByFullName_authTicket = "";
        java.lang.String _getMediaByFullName_fullName = "";
        com.snapstream.types.PVSPropertyBag _getMediaByFullName__return = port.getMediaByFullName(_getMediaByFullName_authTicket, _getMediaByFullName_fullName);
        System.out.println("getMediaByFullName.result=" + _getMediaByFullName__return);


        }
        {
        System.out.println("Invoking getFolderMediaCount...");
        java.lang.String _getFolderMediaCount_authTicket = "";
        java.lang.String _getFolderMediaCount_folderName = "";
        int _getFolderMediaCount__return = port.getFolderMediaCount(_getFolderMediaCount_authTicket, _getFolderMediaCount_folderName);
        System.out.println("getFolderMediaCount.result=" + _getFolderMediaCount__return);


        }
        {
        System.out.println("Invoking getSeriesWithFilter...");
        java.lang.String _getSeriesWithFilter_authTicket = "";
        java.lang.String _getSeriesWithFilter_series = "";
        com.snapstream.webservice.LibraryHideOption _getSeriesWithFilter_hide = null;
        com.snapstream.webservice.LibrarySort _getSeriesWithFilter_sort = null;
        com.snapstream.webservice.LibrarySortOrder _getSeriesWithFilter_order = null;
        int _getSeriesWithFilter_start = 0;
        int _getSeriesWithFilter_count = 0;
        javax.xml.ws.Holder<com.snapstream.webservice.ArrayOfPVSPropertyBag> _getSeriesWithFilter_getSeriesWithFilterResult = new javax.xml.ws.Holder<com.snapstream.webservice.ArrayOfPVSPropertyBag>();
        javax.xml.ws.Holder<java.lang.Integer> _getSeriesWithFilter_totalCount = new javax.xml.ws.Holder<java.lang.Integer>();
        port.getSeriesWithFilter(_getSeriesWithFilter_authTicket, _getSeriesWithFilter_series, _getSeriesWithFilter_hide, _getSeriesWithFilter_sort, _getSeriesWithFilter_order, _getSeriesWithFilter_start, _getSeriesWithFilter_count, _getSeriesWithFilter_getSeriesWithFilterResult, _getSeriesWithFilter_totalCount);

        System.out.println("getSeriesWithFilter._getSeriesWithFilter_getSeriesWithFilterResult=" + _getSeriesWithFilter_getSeriesWithFilterResult.value);
        System.out.println("getSeriesWithFilter._getSeriesWithFilter_totalCount=" + _getSeriesWithFilter_totalCount.value);

        }
        {
        System.out.println("Invoking addFolder2...");
        java.lang.String _addFolder2_authTicket = "";
        java.lang.String _addFolder2_sFolder = "";
        boolean _addFolder2_bRecurse = false;
        port.addFolder2(_addFolder2_authTicket, _addFolder2_sFolder, _addFolder2_bRecurse);


        }
        {
        System.out.println("Invoking addFolder3...");
        java.lang.String _addFolder3_authTicket = "";
        java.lang.String _addFolder3_sFolder = "";
        boolean _addFolder3_bRecurse = false;
        boolean _addFolder3_bManaged = false;
        port.addFolder3(_addFolder3_authTicket, _addFolder3_sFolder, _addFolder3_bRecurse, _addFolder3_bManaged);


        }
        {
        System.out.println("Invoking getStatsInformation...");
        java.lang.String _getStatsInformation_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getStatsInformation__return = port.getStatsInformation(_getStatsInformation_authTicket);
        System.out.println("getStatsInformation.result=" + _getStatsInformation__return);


        }
        {
        System.out.println("Invoking getSeries...");
        java.lang.String _getSeries_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getSeries__return = port.getSeries(_getSeries_authTicket);
        System.out.println("getSeries.result=" + _getSeries__return);


        }
        {
        System.out.println("Invoking flatViewByDate...");
        java.lang.String _flatViewByDate_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _flatViewByDate__return = port.flatViewByDate(_flatViewByDate_authTicket);
        System.out.println("flatViewByDate.result=" + _flatViewByDate__return);


        }
        {
        System.out.println("Invoking flatViewByDate2...");
        java.lang.String _flatViewByDate2_authTicket = "";
        int _flatViewByDate2_index = 0;
        int _flatViewByDate2_count = 0;
        com.snapstream.webservice.ArrayOfPVSPropertyBag _flatViewByDate2__return = port.flatViewByDate2(_flatViewByDate2_authTicket, _flatViewByDate2_index, _flatViewByDate2_count);
        System.out.println("flatViewByDate2.result=" + _flatViewByDate2__return);


        }
        {
        System.out.println("Invoking flatViewByTitle...");
        java.lang.String _flatViewByTitle_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _flatViewByTitle__return = port.flatViewByTitle(_flatViewByTitle_authTicket);
        System.out.println("flatViewByTitle.result=" + _flatViewByTitle__return);


        }
        {
        System.out.println("Invoking luceneHighlightString...");
        java.lang.String _luceneHighlightString_authTicket = "";
        java.lang.String _luceneHighlightString_inputString = "";
        java.lang.String _luceneHighlightString_query = "";
        java.lang.String _luceneHighlightString_highlightStart = "";
        java.lang.String _luceneHighlightString_highlightEnd = "";
        java.lang.String _luceneHighlightString__return = port.luceneHighlightString(_luceneHighlightString_authTicket, _luceneHighlightString_inputString, _luceneHighlightString_query, _luceneHighlightString_highlightStart, _luceneHighlightString_highlightEnd);
        System.out.println("luceneHighlightString.result=" + _luceneHighlightString__return);


        }
        {
        System.out.println("Invoking getItemsBySeriesWithFilter...");
        java.lang.String _getItemsBySeriesWithFilter_authTicket = "";
        java.lang.String _getItemsBySeriesWithFilter_series = "";
        com.snapstream.webservice.LibraryHideOption _getItemsBySeriesWithFilter_hide = null;
        com.snapstream.webservice.LibrarySort _getItemsBySeriesWithFilter_sort = null;
        com.snapstream.webservice.LibrarySortOrder _getItemsBySeriesWithFilter_order = null;
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getItemsBySeriesWithFilter__return = port.getItemsBySeriesWithFilter(_getItemsBySeriesWithFilter_authTicket, _getItemsBySeriesWithFilter_series, _getItemsBySeriesWithFilter_hide, _getItemsBySeriesWithFilter_sort, _getItemsBySeriesWithFilter_order);
        System.out.println("getItemsBySeriesWithFilter.result=" + _getItemsBySeriesWithFilter__return);


        }
        {
        System.out.println("Invoking getFolders...");
        java.lang.String _getFolders_authTicket = "";
        java.lang.String _getFolders_folderName = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getFolders__return = port.getFolders(_getFolders_authTicket, _getFolders_folderName);
        System.out.println("getFolders.result=" + _getFolders__return);


        }
        {
        System.out.println("Invoking getMedia...");
        java.lang.String _getMedia_authTicket = "";
        com.snapstream.webservice.LibraryHideOption _getMedia_hide = null;
        com.snapstream.webservice.LibrarySort _getMedia_sort = null;
        com.snapstream.webservice.LibrarySortOrder _getMedia_order = null;
        int _getMedia_start = 0;
        int _getMedia_count = 0;
        javax.xml.ws.Holder<com.snapstream.webservice.ArrayOfPVSPropertyBag> _getMedia_getMediaResult = new javax.xml.ws.Holder<com.snapstream.webservice.ArrayOfPVSPropertyBag>();
        javax.xml.ws.Holder<java.lang.Integer> _getMedia_totalCount = new javax.xml.ws.Holder<java.lang.Integer>();
        port.getMedia(_getMedia_authTicket, _getMedia_hide, _getMedia_sort, _getMedia_order, _getMedia_start, _getMedia_count, _getMedia_getMediaResult, _getMedia_totalCount);

        System.out.println("getMedia._getMedia_getMediaResult=" + _getMedia_getMediaResult.value);
        System.out.println("getMedia._getMedia_totalCount=" + _getMedia_totalCount.value);

        }
        {
        System.out.println("Invoking getMyClips...");
        java.lang.String _getMyClips_authTicket = "";
        com.snapstream.webservice.LibraryHideOption _getMyClips_hide = null;
        com.snapstream.webservice.LibrarySort _getMyClips_sort = null;
        com.snapstream.webservice.LibrarySortOrder _getMyClips_order = null;
        int _getMyClips_start = 0;
        int _getMyClips_count = 0;
        javax.xml.ws.Holder<com.snapstream.webservice.ArrayOfPVSPropertyBag> _getMyClips_getMyClipsResult = new javax.xml.ws.Holder<com.snapstream.webservice.ArrayOfPVSPropertyBag>();
        javax.xml.ws.Holder<java.lang.Integer> _getMyClips_totalCount = new javax.xml.ws.Holder<java.lang.Integer>();
        port.getMyClips(_getMyClips_authTicket, _getMyClips_hide, _getMyClips_sort, _getMyClips_order, _getMyClips_start, _getMyClips_count, _getMyClips_getMyClipsResult, _getMyClips_totalCount);

        System.out.println("getMyClips._getMyClips_getMyClipsResult=" + _getMyClips_getMyClipsResult.value);
        System.out.println("getMyClips._getMyClips_totalCount=" + _getMyClips_totalCount.value);

        }
        {
        System.out.println("Invoking deleteMedia...");
        java.lang.String _deleteMedia_authTicket = "";
        java.lang.String _deleteMedia_fullName = "";
        port.deleteMedia(_deleteMedia_authTicket, _deleteMedia_fullName);


        }
        {
        System.out.println("Invoking setUserSpecificProperty...");
        java.lang.String _setUserSpecificProperty_authTicket = "";
        java.lang.String _setUserSpecificProperty_fullName = "";
        java.lang.String _setUserSpecificProperty_property = "";
        java.lang.String _setUserSpecificProperty_value = "";
        port.setUserSpecificProperty(_setUserSpecificProperty_authTicket, _setUserSpecificProperty_fullName, _setUserSpecificProperty_property, _setUserSpecificProperty_value);


        }
        {
        System.out.println("Invoking getClips...");
        java.lang.String _getClips_authTicket = "";
        com.snapstream.webservice.LibraryHideOption _getClips_hide = null;
        com.snapstream.webservice.LibrarySort _getClips_sort = null;
        com.snapstream.webservice.LibrarySortOrder _getClips_order = null;
        int _getClips_start = 0;
        int _getClips_count = 0;
        javax.xml.ws.Holder<com.snapstream.webservice.ArrayOfPVSPropertyBag> _getClips_getClipsResult = new javax.xml.ws.Holder<com.snapstream.webservice.ArrayOfPVSPropertyBag>();
        javax.xml.ws.Holder<java.lang.Integer> _getClips_totalCount = new javax.xml.ws.Holder<java.lang.Integer>();
        port.getClips(_getClips_authTicket, _getClips_hide, _getClips_sort, _getClips_order, _getClips_start, _getClips_count, _getClips_getClipsResult, _getClips_totalCount);

        System.out.println("getClips._getClips_getClipsResult=" + _getClips_getClipsResult.value);
        System.out.println("getClips._getClips_totalCount=" + _getClips_totalCount.value);

        }
        {
        System.out.println("Invoking getDriveInformationByName...");
        java.lang.String _getDriveInformationByName_authTicket = "";
        java.lang.String _getDriveInformationByName_driveName = "";
        com.snapstream.types.PVSPropertyBag _getDriveInformationByName__return = port.getDriveInformationByName(_getDriveInformationByName_authTicket, _getDriveInformationByName_driveName);
        System.out.println("getDriveInformationByName.result=" + _getDriveInformationByName__return);


        }
        {
        System.out.println("Invoking getAllMediaWithFilter...");
        java.lang.String _getAllMediaWithFilter_authTicket = "";
        com.snapstream.webservice.LibraryHideOption _getAllMediaWithFilter_hide = null;
        com.snapstream.webservice.LibrarySort _getAllMediaWithFilter_sort = null;
        com.snapstream.webservice.LibrarySortOrder _getAllMediaWithFilter_order = null;
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getAllMediaWithFilter__return = port.getAllMediaWithFilter(_getAllMediaWithFilter_authTicket, _getAllMediaWithFilter_hide, _getAllMediaWithFilter_sort, _getAllMediaWithFilter_order);
        System.out.println("getAllMediaWithFilter.result=" + _getAllMediaWithFilter__return);


        }
        {
        System.out.println("Invoking getFoldersByRange...");
        java.lang.String _getFoldersByRange_authTicket = "";
        java.lang.String _getFoldersByRange_folderName = "";
        int _getFoldersByRange_start = 0;
        int _getFoldersByRange_count = 0;
        javax.xml.ws.Holder<com.snapstream.webservice.ArrayOfPVSPropertyBag> _getFoldersByRange_getFoldersByRangeResult = new javax.xml.ws.Holder<com.snapstream.webservice.ArrayOfPVSPropertyBag>();
        javax.xml.ws.Holder<java.lang.Integer> _getFoldersByRange_totalCount = new javax.xml.ws.Holder<java.lang.Integer>();
        port.getFoldersByRange(_getFoldersByRange_authTicket, _getFoldersByRange_folderName, _getFoldersByRange_start, _getFoldersByRange_count, _getFoldersByRange_getFoldersByRangeResult, _getFoldersByRange_totalCount);

        System.out.println("getFoldersByRange._getFoldersByRange_getFoldersByRangeResult=" + _getFoldersByRange_getFoldersByRangeResult.value);
        System.out.println("getFoldersByRange._getFoldersByRange_totalCount=" + _getFoldersByRange_totalCount.value);

        }
        {
        System.out.println("Invoking getItemsByFolderWithFilter...");
        java.lang.String _getItemsByFolderWithFilter_authTicket = "";
        java.lang.String _getItemsByFolderWithFilter_folder = "";
        com.snapstream.webservice.LibraryHideOption _getItemsByFolderWithFilter_hide = null;
        com.snapstream.webservice.LibrarySort _getItemsByFolderWithFilter_sort = null;
        com.snapstream.webservice.LibrarySortOrder _getItemsByFolderWithFilter_order = null;
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getItemsByFolderWithFilter__return = port.getItemsByFolderWithFilter(_getItemsByFolderWithFilter_authTicket, _getItemsByFolderWithFilter_folder, _getItemsByFolderWithFilter_hide, _getItemsByFolderWithFilter_sort, _getItemsByFolderWithFilter_order);
        System.out.println("getItemsByFolderWithFilter.result=" + _getItemsByFolderWithFilter__return);


        }
        {
        System.out.println("Invoking advancedSearchCCCount...");
        java.lang.String _advancedSearchCCCount_authTicket = "";
        java.lang.String _advancedSearchCCCount_search = "";
        boolean _advancedSearchCCCount_titleSearch = false;
        boolean _advancedSearchCCCount_descSearch = false;
        boolean _advancedSearchCCCount_ccSearch = false;
        int _advancedSearchCCCount__return = port.advancedSearchCCCount(_advancedSearchCCCount_authTicket, _advancedSearchCCCount_search, _advancedSearchCCCount_titleSearch, _advancedSearchCCCount_descSearch, _advancedSearchCCCount_ccSearch);
        System.out.println("advancedSearchCCCount.result=" + _advancedSearchCCCount__return);


        }
        {
        System.out.println("Invoking getOldestUnlockedMediaDateTicks...");
        java.lang.String _getOldestUnlockedMediaDateTicks_authTicket = "";
        long _getOldestUnlockedMediaDateTicks__return = port.getOldestUnlockedMediaDateTicks(_getOldestUnlockedMediaDateTicks_authTicket);
        System.out.println("getOldestUnlockedMediaDateTicks.result=" + _getOldestUnlockedMediaDateTicks__return);


        }
        {
        System.out.println("Invoking advancedSearchCCWithSuggestion...");
        java.lang.String _advancedSearchCCWithSuggestion_authTicket = "";
        java.lang.String _advancedSearchCCWithSuggestion_search = "";
        int _advancedSearchCCWithSuggestion_pageNumber = 0;
        int _advancedSearchCCWithSuggestion_resultsPerPage = 0;
        boolean _advancedSearchCCWithSuggestion_titleSearch = false;
        boolean _advancedSearchCCWithSuggestion_descSearch = false;
        boolean _advancedSearchCCWithSuggestion_ccSearch = false;
        java.lang.String _advancedSearchCCWithSuggestion_highlightStart = "";
        java.lang.String _advancedSearchCCWithSuggestion_highlightEnd = "";
        java.lang.String _advancedSearchCCWithSuggestion_suggestionStart = "";
        java.lang.String _advancedSearchCCWithSuggestion_suggestionEnd = "";
        javax.xml.ws.Holder<com.snapstream.webservice.ArrayOfPVSPropertyBag> _advancedSearchCCWithSuggestion_advancedSearchCCWithSuggestionResult = new javax.xml.ws.Holder<com.snapstream.webservice.ArrayOfPVSPropertyBag>();
        javax.xml.ws.Holder<java.lang.Integer> _advancedSearchCCWithSuggestion_numberOfPages = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<java.lang.Integer> _advancedSearchCCWithSuggestion_numberOfResults = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<java.lang.String> _advancedSearchCCWithSuggestion_suggestion = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _advancedSearchCCWithSuggestion_suggestionFormatted = new javax.xml.ws.Holder<java.lang.String>();
        port.advancedSearchCCWithSuggestion(_advancedSearchCCWithSuggestion_authTicket, _advancedSearchCCWithSuggestion_search, _advancedSearchCCWithSuggestion_pageNumber, _advancedSearchCCWithSuggestion_resultsPerPage, _advancedSearchCCWithSuggestion_titleSearch, _advancedSearchCCWithSuggestion_descSearch, _advancedSearchCCWithSuggestion_ccSearch, _advancedSearchCCWithSuggestion_highlightStart, _advancedSearchCCWithSuggestion_highlightEnd, _advancedSearchCCWithSuggestion_suggestionStart, _advancedSearchCCWithSuggestion_suggestionEnd, _advancedSearchCCWithSuggestion_advancedSearchCCWithSuggestionResult, _advancedSearchCCWithSuggestion_numberOfPages, _advancedSearchCCWithSuggestion_numberOfResults, _advancedSearchCCWithSuggestion_suggestion, _advancedSearchCCWithSuggestion_suggestionFormatted);

        System.out.println("advancedSearchCCWithSuggestion._advancedSearchCCWithSuggestion_advancedSearchCCWithSuggestionResult=" + _advancedSearchCCWithSuggestion_advancedSearchCCWithSuggestionResult.value);
        System.out.println("advancedSearchCCWithSuggestion._advancedSearchCCWithSuggestion_numberOfPages=" + _advancedSearchCCWithSuggestion_numberOfPages.value);
        System.out.println("advancedSearchCCWithSuggestion._advancedSearchCCWithSuggestion_numberOfResults=" + _advancedSearchCCWithSuggestion_numberOfResults.value);
        System.out.println("advancedSearchCCWithSuggestion._advancedSearchCCWithSuggestion_suggestion=" + _advancedSearchCCWithSuggestion_suggestion.value);
        System.out.println("advancedSearchCCWithSuggestion._advancedSearchCCWithSuggestion_suggestionFormatted=" + _advancedSearchCCWithSuggestion_suggestionFormatted.value);

        }
        {
        System.out.println("Invoking getSeriesByRange...");
        java.lang.String _getSeriesByRange_authTicket = "";
        int _getSeriesByRange_start = 0;
        int _getSeriesByRange_count = 0;
        javax.xml.ws.Holder<com.snapstream.webservice.ArrayOfPVSPropertyBag> _getSeriesByRange_getSeriesByRangeResult = new javax.xml.ws.Holder<com.snapstream.webservice.ArrayOfPVSPropertyBag>();
        javax.xml.ws.Holder<java.lang.Integer> _getSeriesByRange_totalCount = new javax.xml.ws.Holder<java.lang.Integer>();
        port.getSeriesByRange(_getSeriesByRange_authTicket, _getSeriesByRange_start, _getSeriesByRange_count, _getSeriesByRange_getSeriesByRangeResult, _getSeriesByRange_totalCount);

        System.out.println("getSeriesByRange._getSeriesByRange_getSeriesByRangeResult=" + _getSeriesByRange_getSeriesByRangeResult.value);
        System.out.println("getSeriesByRange._getSeriesByRange_totalCount=" + _getSeriesByRange_totalCount.value);

        }
        {
        System.out.println("Invoking getItemsBySeries...");
        java.lang.String _getItemsBySeries_authTicket = "";
        java.lang.String _getItemsBySeries_series = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getItemsBySeries__return = port.getItemsBySeries(_getItemsBySeries_authTicket, _getItemsBySeries_series);
        System.out.println("getItemsBySeries.result=" + _getItemsBySeries__return);


        }
        {
        System.out.println("Invoking flatViewClipsByDate...");
        java.lang.String _flatViewClipsByDate_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _flatViewClipsByDate__return = port.flatViewClipsByDate(_flatViewClipsByDate_authTicket);
        System.out.println("flatViewClipsByDate.result=" + _flatViewClipsByDate__return);


        }
        {
        System.out.println("Invoking advancedSearchCCCountWithSuggestion...");
        java.lang.String _advancedSearchCCCountWithSuggestion_authTicket = "";
        java.lang.String _advancedSearchCCCountWithSuggestion_search = "";
        boolean _advancedSearchCCCountWithSuggestion_titleSearch = false;
        boolean _advancedSearchCCCountWithSuggestion_descSearch = false;
        boolean _advancedSearchCCCountWithSuggestion_ccSearch = false;
        java.lang.String _advancedSearchCCCountWithSuggestion_suggestionStart = "";
        java.lang.String _advancedSearchCCCountWithSuggestion_suggestionEnd = "";
        javax.xml.ws.Holder<java.lang.Integer> _advancedSearchCCCountWithSuggestion_advancedSearchCCCountWithSuggestionResult = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<java.lang.String> _advancedSearchCCCountWithSuggestion_suggestion = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _advancedSearchCCCountWithSuggestion_suggestionFormatted = new javax.xml.ws.Holder<java.lang.String>();
        port.advancedSearchCCCountWithSuggestion(_advancedSearchCCCountWithSuggestion_authTicket, _advancedSearchCCCountWithSuggestion_search, _advancedSearchCCCountWithSuggestion_titleSearch, _advancedSearchCCCountWithSuggestion_descSearch, _advancedSearchCCCountWithSuggestion_ccSearch, _advancedSearchCCCountWithSuggestion_suggestionStart, _advancedSearchCCCountWithSuggestion_suggestionEnd, _advancedSearchCCCountWithSuggestion_advancedSearchCCCountWithSuggestionResult, _advancedSearchCCCountWithSuggestion_suggestion, _advancedSearchCCCountWithSuggestion_suggestionFormatted);

        System.out.println("advancedSearchCCCountWithSuggestion._advancedSearchCCCountWithSuggestion_advancedSearchCCCountWithSuggestionResult=" + _advancedSearchCCCountWithSuggestion_advancedSearchCCCountWithSuggestionResult.value);
        System.out.println("advancedSearchCCCountWithSuggestion._advancedSearchCCCountWithSuggestion_suggestion=" + _advancedSearchCCCountWithSuggestion_suggestion.value);
        System.out.println("advancedSearchCCCountWithSuggestion._advancedSearchCCCountWithSuggestion_suggestionFormatted=" + _advancedSearchCCCountWithSuggestion_suggestionFormatted.value);

        }
        {
        System.out.println("Invoking getFolderWithFilter...");
        java.lang.String _getFolderWithFilter_authTicket = "";
        java.lang.String _getFolderWithFilter_folder = "";
        com.snapstream.webservice.LibraryHideOption _getFolderWithFilter_hide = null;
        com.snapstream.webservice.LibrarySort _getFolderWithFilter_sort = null;
        com.snapstream.webservice.LibrarySortOrder _getFolderWithFilter_order = null;
        int _getFolderWithFilter_start = 0;
        int _getFolderWithFilter_count = 0;
        javax.xml.ws.Holder<com.snapstream.webservice.ArrayOfPVSPropertyBag> _getFolderWithFilter_getFolderWithFilterResult = new javax.xml.ws.Holder<com.snapstream.webservice.ArrayOfPVSPropertyBag>();
        javax.xml.ws.Holder<java.lang.Integer> _getFolderWithFilter_totalCount = new javax.xml.ws.Holder<java.lang.Integer>();
        port.getFolderWithFilter(_getFolderWithFilter_authTicket, _getFolderWithFilter_folder, _getFolderWithFilter_hide, _getFolderWithFilter_sort, _getFolderWithFilter_order, _getFolderWithFilter_start, _getFolderWithFilter_count, _getFolderWithFilter_getFolderWithFilterResult, _getFolderWithFilter_totalCount);

        System.out.println("getFolderWithFilter._getFolderWithFilter_getFolderWithFilterResult=" + _getFolderWithFilter_getFolderWithFilterResult.value);
        System.out.println("getFolderWithFilter._getFolderWithFilter_totalCount=" + _getFolderWithFilter_totalCount.value);

        }
        {
        System.out.println("Invoking removeFolder...");
        java.lang.String _removeFolder_authTicket = "";
        java.lang.String _removeFolder_sFolder = "";
        port.removeFolder(_removeFolder_authTicket, _removeFolder_sFolder);


        }
        {
        System.out.println("Invoking getFolder...");
        java.lang.String _getFolder_authTicket = "";
        java.lang.String _getFolder_folderName = "";
        com.snapstream.types.PVSPropertyBag _getFolder__return = port.getFolder(_getFolder_authTicket, _getFolder_folderName);
        System.out.println("getFolder.result=" + _getFolder__return);


        }
        {
        System.out.println("Invoking advancedSearchCC...");
        java.lang.String _advancedSearchCC_authTicket = "";
        java.lang.String _advancedSearchCC_search = "";
        int _advancedSearchCC_pageNumber = 0;
        int _advancedSearchCC_resultsPerPage = 0;
        boolean _advancedSearchCC_titleSearch = false;
        boolean _advancedSearchCC_descSearch = false;
        boolean _advancedSearchCC_ccSearch = false;
        java.lang.String _advancedSearchCC_highlightStart = "";
        java.lang.String _advancedSearchCC_highlightEnd = "";
        javax.xml.ws.Holder<com.snapstream.webservice.ArrayOfPVSPropertyBag> _advancedSearchCC_advancedSearchCCResult = new javax.xml.ws.Holder<com.snapstream.webservice.ArrayOfPVSPropertyBag>();
        javax.xml.ws.Holder<java.lang.Integer> _advancedSearchCC_numberOfPages = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<java.lang.Integer> _advancedSearchCC_numberOfResults = new javax.xml.ws.Holder<java.lang.Integer>();
        port.advancedSearchCC(_advancedSearchCC_authTicket, _advancedSearchCC_search, _advancedSearchCC_pageNumber, _advancedSearchCC_resultsPerPage, _advancedSearchCC_titleSearch, _advancedSearchCC_descSearch, _advancedSearchCC_ccSearch, _advancedSearchCC_highlightStart, _advancedSearchCC_highlightEnd, _advancedSearchCC_advancedSearchCCResult, _advancedSearchCC_numberOfPages, _advancedSearchCC_numberOfResults);

        System.out.println("advancedSearchCC._advancedSearchCC_advancedSearchCCResult=" + _advancedSearchCC_advancedSearchCCResult.value);
        System.out.println("advancedSearchCC._advancedSearchCC_numberOfPages=" + _advancedSearchCC_numberOfPages.value);
        System.out.println("advancedSearchCC._advancedSearchCC_numberOfResults=" + _advancedSearchCC_numberOfResults.value);

        }
        {
        System.out.println("Invoking getItemsByJob...");
        java.lang.String _getItemsByJob_authTicket = "";
        java.lang.String _getItemsByJob_job = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getItemsByJob__return = port.getItemsByJob(_getItemsByJob_authTicket, _getItemsByJob_job);
        System.out.println("getItemsByJob.result=" + _getItemsByJob__return);


        }
        {
        System.out.println("Invoking getItemsByFolder...");
        java.lang.String _getItemsByFolder_authTicket = "";
        java.lang.String _getItemsByFolder_folder = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getItemsByFolder__return = port.getItemsByFolder(_getItemsByFolder_authTicket, _getItemsByFolder_folder);
        System.out.println("getItemsByFolder.result=" + _getItemsByFolder__return);


        }

        System.exit(0);
    }

}
