
/*
 * 
 */

package com.snapstream.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-05-05T12:55:00.787-06:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "BTVLiveTVManager", 
                  wsdlLocation = "file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/BTVLiveTVManager.asmx.xml",
                  targetNamespace = "http://www.snapstream.com/WebService") 
public class BTVLiveTVManager extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.snapstream.com/WebService", "BTVLiveTVManager");
    public final static QName BTVLiveTVManagerSoap12 = new QName("http://www.snapstream.com/WebService", "BTVLiveTVManagerSoap12");
    public final static QName BTVLiveTVManagerSoap = new QName("http://www.snapstream.com/WebService", "BTVLiveTVManagerSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/BTVLiveTVManager.asmx.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BTVLiveTVManager.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/BTVLiveTVManager.asmx.xml");
        }
        WSDL_LOCATION = url;
    }

    public BTVLiveTVManager(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BTVLiveTVManager(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BTVLiveTVManager() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns BTVLiveTVManagerSoap
     */
    @WebEndpoint(name = "BTVLiveTVManagerSoap12")
    public BTVLiveTVManagerSoap getBTVLiveTVManagerSoap12() {
        return super.getPort(BTVLiveTVManagerSoap12, BTVLiveTVManagerSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BTVLiveTVManagerSoap
     */
    @WebEndpoint(name = "BTVLiveTVManagerSoap12")
    public BTVLiveTVManagerSoap getBTVLiveTVManagerSoap12(WebServiceFeature... features) {
        return super.getPort(BTVLiveTVManagerSoap12, BTVLiveTVManagerSoap.class, features);
    }
    /**
     * 
     * @return
     *     returns BTVLiveTVManagerSoap
     */
    @WebEndpoint(name = "BTVLiveTVManagerSoap")
    public BTVLiveTVManagerSoap getBTVLiveTVManagerSoap() {
        return super.getPort(BTVLiveTVManagerSoap, BTVLiveTVManagerSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BTVLiveTVManagerSoap
     */
    @WebEndpoint(name = "BTVLiveTVManagerSoap")
    public BTVLiveTVManagerSoap getBTVLiveTVManagerSoap(WebServiceFeature... features) {
        return super.getPort(BTVLiveTVManagerSoap, BTVLiveTVManagerSoap.class, features);
    }

}
