package com.snapstream.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-05-05T12:55:10.660-06:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://www.snapstream.com/WebService", name = "BTVLogSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface BTVLogSoap {

    @RequestWrapper(localName = "DismissAllErrors", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.DismissAllErrors")
    @WebMethod(operationName = "DismissAllErrors", action = "http://www.snapstream.com/WebService/DismissAllErrors")
    @ResponseWrapper(localName = "DismissAllErrorsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.DismissAllErrorsResponse")
    public void dismissAllErrors(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );

    @RequestWrapper(localName = "WriteLogMessagesToDisk", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.WriteLogMessagesToDisk")
    @WebMethod(operationName = "WriteLogMessagesToDisk", action = "http://www.snapstream.com/WebService/WriteLogMessagesToDisk")
    @ResponseWrapper(localName = "WriteLogMessagesToDiskResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.WriteLogMessagesToDiskResponse")
    public void writeLogMessagesToDisk(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );

    @RequestWrapper(localName = "LogError", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.LogError")
    @WebMethod(operationName = "LogError", action = "http://www.snapstream.com/WebService/LogError")
    @ResponseWrapper(localName = "LogErrorResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.LogErrorResponse")
    public void logError(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "ulErrorCode", targetNamespace = "http://www.snapstream.com/WebService")
        long ulErrorCode,
        @WebParam(name = "bUnique", targetNamespace = "http://www.snapstream.com/WebService")
        int bUnique,
        @WebParam(name = "bUniqueDesc", targetNamespace = "http://www.snapstream.com/WebService")
        int bUniqueDesc,
        @WebParam(name = "bstrErrStr", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String bstrErrStr
    );

    @RequestWrapper(localName = "DismissError", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.DismissError")
    @WebMethod(operationName = "DismissError", action = "http://www.snapstream.com/WebService/DismissError")
    @ResponseWrapper(localName = "DismissErrorResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.DismissErrorResponse")
    public void dismissError(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "timestamp", targetNamespace = "http://www.snapstream.com/WebService")
        java.math.BigInteger timestamp,
        @WebParam(name = "errorCode", targetNamespace = "http://www.snapstream.com/WebService")
        long errorCode
    );

    @RequestWrapper(localName = "GetNextErrorWithDescription", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetNextErrorWithDescription")
    @WebMethod(operationName = "GetNextErrorWithDescription", action = "http://www.snapstream.com/WebService/GetNextErrorWithDescription")
    @ResponseWrapper(localName = "GetNextErrorWithDescriptionResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetNextErrorWithDescriptionResponse")
    public void getNextErrorWithDescription(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "startTime", targetNamespace = "http://www.snapstream.com/WebService")
        java.math.BigInteger startTime,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetNextErrorWithDescriptionResult", targetNamespace = "http://www.snapstream.com/WebService")
        javax.xml.ws.Holder<java.lang.String> getNextErrorWithDescriptionResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "timestamp", targetNamespace = "http://www.snapstream.com/WebService")
        javax.xml.ws.Holder<java.math.BigInteger> timestamp,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorCode", targetNamespace = "http://www.snapstream.com/WebService")
        javax.xml.ws.Holder<java.lang.Long> errorCode
    );

    @RequestWrapper(localName = "WriteLog", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.WriteLog")
    @WebMethod(operationName = "WriteLog", action = "http://www.snapstream.com/WebService/WriteLog")
    @ResponseWrapper(localName = "WriteLogResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.WriteLogResponse")
    public void writeLog(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bstrMsg", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String bstrMsg
    );

    @RequestWrapper(localName = "GetNextError", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetNextError")
    @WebMethod(operationName = "GetNextError", action = "http://www.snapstream.com/WebService/GetNextError")
    @ResponseWrapper(localName = "GetNextErrorResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetNextErrorResponse")
    public void getNextError(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "startTime", targetNamespace = "http://www.snapstream.com/WebService")
        java.math.BigInteger startTime,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetNextErrorResult", targetNamespace = "http://www.snapstream.com/WebService")
        javax.xml.ws.Holder<java.lang.String> getNextErrorResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "timestamp", targetNamespace = "http://www.snapstream.com/WebService")
        javax.xml.ws.Holder<java.math.BigInteger> timestamp,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorCode", targetNamespace = "http://www.snapstream.com/WebService")
        javax.xml.ws.Holder<java.lang.Long> errorCode
    );

    @RequestWrapper(localName = "ReactivateIgnoredErrors", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.ReactivateIgnoredErrors")
    @WebMethod(operationName = "ReactivateIgnoredErrors", action = "http://www.snapstream.com/WebService/ReactivateIgnoredErrors")
    @ResponseWrapper(localName = "ReactivateIgnoredErrorsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.ReactivateIgnoredErrorsResponse")
    public void reactivateIgnoredErrors(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );

    @RequestWrapper(localName = "GetNextMessage", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetNextMessage")
    @WebMethod(operationName = "GetNextMessage", action = "http://www.snapstream.com/WebService/GetNextMessage")
    @ResponseWrapper(localName = "GetNextMessageResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetNextMessageResponse")
    public void getNextMessage(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(mode = WebParam.Mode.INOUT, name = "pqwStart", targetNamespace = "http://www.snapstream.com/WebService")
        javax.xml.ws.Holder<java.math.BigInteger> pqwStart,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetNextMessageResult", targetNamespace = "http://www.snapstream.com/WebService")
        javax.xml.ws.Holder<java.lang.String> getNextMessageResult
    );

    @RequestWrapper(localName = "WriteLogUser", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.WriteLogUser")
    @WebMethod(operationName = "WriteLogUser", action = "http://www.snapstream.com/WebService/WriteLogUser")
    @ResponseWrapper(localName = "WriteLogUserResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.WriteLogUserResponse")
    public void writeLogUser(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bstrMsg", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String bstrMsg
    );

    @RequestWrapper(localName = "WriteChange", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.WriteChange")
    @WebMethod(operationName = "WriteChange", action = "http://www.snapstream.com/WebService/WriteChange")
    @ResponseWrapper(localName = "WriteChangeResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.WriteChangeResponse")
    public void writeChange(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bstrSetting", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String bstrSetting,
        @WebParam(name = "bstrOldValue", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String bstrOldValue,
        @WebParam(name = "bstrNewValue", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String bstrNewValue
    );

    @RequestWrapper(localName = "IgnoreError", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.IgnoreError")
    @WebMethod(operationName = "IgnoreError", action = "http://www.snapstream.com/WebService/IgnoreError")
    @ResponseWrapper(localName = "IgnoreErrorResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.IgnoreErrorResponse")
    public void ignoreError(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "errorCode", targetNamespace = "http://www.snapstream.com/WebService")
        long errorCode
    );
}
