
/*
 * 
 */

package com.snapstream.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-05-05T12:54:49.779-06:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "BTVLicenseManager", 
                  wsdlLocation = "file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/BTVLicenseManager.asmx.xml",
                  targetNamespace = "http://www.snapstream.com/WebService") 
public class BTVLicenseManager extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.snapstream.com/WebService", "BTVLicenseManager");
    public final static QName BTVLicenseManagerSoap = new QName("http://www.snapstream.com/WebService", "BTVLicenseManagerSoap");
    public final static QName BTVLicenseManagerSoap12 = new QName("http://www.snapstream.com/WebService", "BTVLicenseManagerSoap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/BTVLicenseManager.asmx.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BTVLicenseManager.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/BTVLicenseManager.asmx.xml");
        }
        WSDL_LOCATION = url;
    }

    public BTVLicenseManager(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BTVLicenseManager(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BTVLicenseManager() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns BTVLicenseManagerSoap
     */
    @WebEndpoint(name = "BTVLicenseManagerSoap")
    public BTVLicenseManagerSoap getBTVLicenseManagerSoap() {
        return super.getPort(BTVLicenseManagerSoap, BTVLicenseManagerSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BTVLicenseManagerSoap
     */
    @WebEndpoint(name = "BTVLicenseManagerSoap")
    public BTVLicenseManagerSoap getBTVLicenseManagerSoap(WebServiceFeature... features) {
        return super.getPort(BTVLicenseManagerSoap, BTVLicenseManagerSoap.class, features);
    }
    /**
     * 
     * @return
     *     returns BTVLicenseManagerSoap
     */
    @WebEndpoint(name = "BTVLicenseManagerSoap12")
    public BTVLicenseManagerSoap getBTVLicenseManagerSoap12() {
        return super.getPort(BTVLicenseManagerSoap12, BTVLicenseManagerSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BTVLicenseManagerSoap
     */
    @WebEndpoint(name = "BTVLicenseManagerSoap12")
    public BTVLicenseManagerSoap getBTVLicenseManagerSoap12(WebServiceFeature... features) {
        return super.getPort(BTVLicenseManagerSoap12, BTVLicenseManagerSoap.class, features);
    }

}
