package com.snapstream.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-05-05T12:55:58.379-06:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://www.snapstream.com/WebService", name = "BTVSettingsSoap")
@XmlSeeAlso({com.snapstream.types.ObjectFactory.class, ObjectFactory.class})
public interface BTVSettingsSoap {

    @WebResult(name = "GetDevicesResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetDevices", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetDevices")
    @WebMethod(operationName = "GetDevices", action = "http://www.snapstream.com/WebService/GetDevices")
    @ResponseWrapper(localName = "GetDevicesResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetDevicesResponse")
    public com.snapstream.webservice.ArrayOfPVSPropertyBag getDevices(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );

    @WebResult(name = "GetPropertyAsBoolResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetPropertyAsBool", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetPropertyAsBool")
    @WebMethod(operationName = "GetPropertyAsBool", action = "http://www.snapstream.com/WebService/GetPropertyAsBool")
    @ResponseWrapper(localName = "GetPropertyAsBoolResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetPropertyAsBoolResponse")
    public boolean getPropertyAsBool(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "name", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String name
    );

    @WebResult(name = "GetUnifiedLineupResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetUnifiedLineup", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetUnifiedLineup")
    @WebMethod(operationName = "GetUnifiedLineup", action = "http://www.snapstream.com/WebService/GetUnifiedLineup")
    @ResponseWrapper(localName = "GetUnifiedLineupResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetUnifiedLineupResponse")
    public java.lang.String getUnifiedLineup(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );

    @WebResult(name = "GetUnifiedLineupDisplayedChannelsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetUnifiedLineupDisplayedChannels", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetUnifiedLineupDisplayedChannels")
    @WebMethod(operationName = "GetUnifiedLineupDisplayedChannels", action = "http://www.snapstream.com/WebService/GetUnifiedLineupDisplayedChannels")
    @ResponseWrapper(localName = "GetUnifiedLineupDisplayedChannelsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetUnifiedLineupDisplayedChannelsResponse")
    public java.lang.String getUnifiedLineupDisplayedChannels(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );

    @WebResult(name = "GetBaseLineupsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetBaseLineups", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetBaseLineups")
    @WebMethod(operationName = "GetBaseLineups", action = "http://www.snapstream.com/WebService/GetBaseLineups")
    @ResponseWrapper(localName = "GetBaseLineupsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetBaseLineupsResponse")
    public java.lang.String getBaseLineups(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );

    @RequestWrapper(localName = "SetProfiles", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.SetProfiles")
    @WebMethod(operationName = "SetProfiles", action = "http://www.snapstream.com/WebService/SetProfiles")
    @ResponseWrapper(localName = "SetProfilesResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.SetProfilesResponse")
    public void setProfiles(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        com.snapstream.webservice.ArrayOfPVSPropertyBag bags,
        @WebParam(name = "bSaveFile", targetNamespace = "http://www.snapstream.com/WebService")
        int bSaveFile
    );

    @RequestWrapper(localName = "SetPropertyAsDouble", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.SetPropertyAsDouble")
    @WebMethod(operationName = "SetPropertyAsDouble", action = "http://www.snapstream.com/WebService/SetPropertyAsDouble")
    @ResponseWrapper(localName = "SetPropertyAsDoubleResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.SetPropertyAsDoubleResponse")
    public void setPropertyAsDouble(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "name", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String name,
        @WebParam(name = "val", targetNamespace = "http://www.snapstream.com/WebService")
        double val
    );

    @WebResult(name = "GetProfilesResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetProfiles", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetProfiles")
    @WebMethod(operationName = "GetProfiles", action = "http://www.snapstream.com/WebService/GetProfiles")
    @ResponseWrapper(localName = "GetProfilesResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetProfilesResponse")
    public com.snapstream.webservice.ArrayOfPVSPropertyBag getProfiles(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );

    @RequestWrapper(localName = "SetPropertyAsInt", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.SetPropertyAsInt")
    @WebMethod(operationName = "SetPropertyAsInt", action = "http://www.snapstream.com/WebService/SetPropertyAsInt")
    @ResponseWrapper(localName = "SetPropertyAsIntResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.SetPropertyAsIntResponse")
    public void setPropertyAsInt(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "name", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String name,
        @WebParam(name = "val", targetNamespace = "http://www.snapstream.com/WebService")
        long val
    );

    @WebResult(name = "GetValidRecordingFormatsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetValidRecordingFormats", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetValidRecordingFormats")
    @WebMethod(operationName = "GetValidRecordingFormats", action = "http://www.snapstream.com/WebService/GetValidRecordingFormats")
    @ResponseWrapper(localName = "GetValidRecordingFormatsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetValidRecordingFormatsResponse")
    public long getValidRecordingFormats(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );

    @WebResult(name = "GetPropertyAsDoubleResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetPropertyAsDouble", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetPropertyAsDouble")
    @WebMethod(operationName = "GetPropertyAsDouble", action = "http://www.snapstream.com/WebService/GetPropertyAsDouble")
    @ResponseWrapper(localName = "GetPropertyAsDoubleResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetPropertyAsDoubleResponse")
    public double getPropertyAsDouble(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "name", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String name
    );

    @RequestWrapper(localName = "SetProperty", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.SetProperty")
    @WebMethod(operationName = "SetProperty", action = "http://www.snapstream.com/WebService/SetProperty")
    @ResponseWrapper(localName = "SetPropertyResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.SetPropertyResponse")
    public void setProperty(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "name", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String name,
        @WebParam(name = "valueString", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String valueString
    );

    @WebResult(name = "GetPropertyAsIntResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetPropertyAsInt", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetPropertyAsInt")
    @WebMethod(operationName = "GetPropertyAsInt", action = "http://www.snapstream.com/WebService/GetPropertyAsInt")
    @ResponseWrapper(localName = "GetPropertyAsIntResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetPropertyAsIntResponse")
    public long getPropertyAsInt(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "name", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String name
    );

    @RequestWrapper(localName = "SetDevices", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.SetDevices")
    @WebMethod(operationName = "SetDevices", action = "http://www.snapstream.com/WebService/SetDevices")
    @ResponseWrapper(localName = "SetDevicesResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.SetDevicesResponse")
    public void setDevices(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        com.snapstream.webservice.ArrayOfPVSPropertyBag bags
    );

    @RequestWrapper(localName = "SetPropertyAsBool", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.SetPropertyAsBool")
    @WebMethod(operationName = "SetPropertyAsBool", action = "http://www.snapstream.com/WebService/SetPropertyAsBool")
    @ResponseWrapper(localName = "SetPropertyAsBoolResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.SetPropertyAsBoolResponse")
    public void setPropertyAsBool(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "name", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String name,
        @WebParam(name = "val", targetNamespace = "http://www.snapstream.com/WebService")
        boolean val
    );

    @WebResult(name = "GetPropertyResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetProperty", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetProperty")
    @WebMethod(operationName = "GetProperty", action = "http://www.snapstream.com/WebService/GetProperty")
    @ResponseWrapper(localName = "GetPropertyResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetPropertyResponse")
    public java.lang.String getProperty(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "name", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String name
    );

    @WebResult(name = "GetOEMCodeResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetOEMCode", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetOEMCode")
    @WebMethod(operationName = "GetOEMCode", action = "http://www.snapstream.com/WebService/GetOEMCode")
    @ResponseWrapper(localName = "GetOEMCodeResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetOEMCodeResponse")
    public int getOEMCode(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );

    @WebResult(name = "GetUserLineupsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetUserLineups", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetUserLineups")
    @WebMethod(operationName = "GetUserLineups", action = "http://www.snapstream.com/WebService/GetUserLineups")
    @ResponseWrapper(localName = "GetUserLineupsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetUserLineupsResponse")
    public java.lang.String getUserLineups(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );

    @WebResult(name = "GetPropertyBagCollectionResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetPropertyBagCollection", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetPropertyBagCollection")
    @WebMethod(operationName = "GetPropertyBagCollection", action = "http://www.snapstream.com/WebService/GetPropertyBagCollection")
    @ResponseWrapper(localName = "GetPropertyBagCollectionResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetPropertyBagCollectionResponse")
    public com.snapstream.webservice.ArrayOfPVSPropertyBag getPropertyBagCollection(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "name", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String name
    );

    @RequestWrapper(localName = "WriteSettingsToDisk", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.WriteSettingsToDisk")
    @WebMethod(operationName = "WriteSettingsToDisk", action = "http://www.snapstream.com/WebService/WriteSettingsToDisk")
    @ResponseWrapper(localName = "WriteSettingsToDiskResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.WriteSettingsToDiskResponse")
    public void writeSettingsToDisk(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );

    @WebResult(name = "GetRadioLineupResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetRadioLineup", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetRadioLineup")
    @WebMethod(operationName = "GetRadioLineup", action = "http://www.snapstream.com/WebService/GetRadioLineup")
    @ResponseWrapper(localName = "GetRadioLineupResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetRadioLineupResponse")
    public java.lang.String getRadioLineup(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );

    @WebResult(name = "GetFeatureResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetFeature", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetFeature")
    @WebMethod(operationName = "GetFeature", action = "http://www.snapstream.com/WebService/GetFeature")
    @ResponseWrapper(localName = "GetFeatureResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetFeatureResponse")
    public java.lang.String getFeature(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "name", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String name
    );

    @WebResult(name = "GetNetURLResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetNetURL", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetNetURL")
    @WebMethod(operationName = "GetNetURL", action = "http://www.snapstream.com/WebService/GetNetURL")
    @ResponseWrapper(localName = "GetNetURLResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetNetURLResponse")
    public java.lang.String getNetURL(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );
}
