
package com.snapstream.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-05-05T12:55:58.249-06:00
 * Generated source version: 2.4.0
 * 
 */
public final class BTVSettingsSoap_BTVSettingsSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://www.snapstream.com/WebService", "BTVSettings");

    private BTVSettingsSoap_BTVSettingsSoap12_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = BTVSettings.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BTVSettings ss = new BTVSettings(wsdlURL, SERVICE_NAME);
        BTVSettingsSoap port = ss.getBTVSettingsSoap12();  
        
        {
        System.out.println("Invoking getDevices...");
        java.lang.String _getDevices_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getDevices__return = port.getDevices(_getDevices_authTicket);
        System.out.println("getDevices.result=" + _getDevices__return);


        }
        {
        System.out.println("Invoking getPropertyAsBool...");
        java.lang.String _getPropertyAsBool_authTicket = "";
        java.lang.String _getPropertyAsBool_name = "";
        boolean _getPropertyAsBool__return = port.getPropertyAsBool(_getPropertyAsBool_authTicket, _getPropertyAsBool_name);
        System.out.println("getPropertyAsBool.result=" + _getPropertyAsBool__return);


        }
        {
        System.out.println("Invoking getUnifiedLineup...");
        java.lang.String _getUnifiedLineup_authTicket = "";
        java.lang.String _getUnifiedLineup__return = port.getUnifiedLineup(_getUnifiedLineup_authTicket);
        System.out.println("getUnifiedLineup.result=" + _getUnifiedLineup__return);


        }
        {
        System.out.println("Invoking getUnifiedLineupDisplayedChannels...");
        java.lang.String _getUnifiedLineupDisplayedChannels_authTicket = "";
        java.lang.String _getUnifiedLineupDisplayedChannels__return = port.getUnifiedLineupDisplayedChannels(_getUnifiedLineupDisplayedChannels_authTicket);
        System.out.println("getUnifiedLineupDisplayedChannels.result=" + _getUnifiedLineupDisplayedChannels__return);


        }
        {
        System.out.println("Invoking getBaseLineups...");
        java.lang.String _getBaseLineups_authTicket = "";
        java.lang.String _getBaseLineups__return = port.getBaseLineups(_getBaseLineups_authTicket);
        System.out.println("getBaseLineups.result=" + _getBaseLineups__return);


        }
        {
        System.out.println("Invoking setProfiles...");
        java.lang.String _setProfiles_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _setProfiles_bags = null;
        int _setProfiles_bSaveFile = 0;
        port.setProfiles(_setProfiles_authTicket, _setProfiles_bags, _setProfiles_bSaveFile);


        }
        {
        System.out.println("Invoking setPropertyAsDouble...");
        java.lang.String _setPropertyAsDouble_authTicket = "";
        java.lang.String _setPropertyAsDouble_name = "";
        double _setPropertyAsDouble_val = 0.0;
        port.setPropertyAsDouble(_setPropertyAsDouble_authTicket, _setPropertyAsDouble_name, _setPropertyAsDouble_val);


        }
        {
        System.out.println("Invoking getProfiles...");
        java.lang.String _getProfiles_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getProfiles__return = port.getProfiles(_getProfiles_authTicket);
        System.out.println("getProfiles.result=" + _getProfiles__return);


        }
        {
        System.out.println("Invoking setPropertyAsInt...");
        java.lang.String _setPropertyAsInt_authTicket = "";
        java.lang.String _setPropertyAsInt_name = "";
        long _setPropertyAsInt_val = 0;
        port.setPropertyAsInt(_setPropertyAsInt_authTicket, _setPropertyAsInt_name, _setPropertyAsInt_val);


        }
        {
        System.out.println("Invoking getValidRecordingFormats...");
        java.lang.String _getValidRecordingFormats_authTicket = "";
        long _getValidRecordingFormats__return = port.getValidRecordingFormats(_getValidRecordingFormats_authTicket);
        System.out.println("getValidRecordingFormats.result=" + _getValidRecordingFormats__return);


        }
        {
        System.out.println("Invoking getPropertyAsDouble...");
        java.lang.String _getPropertyAsDouble_authTicket = "";
        java.lang.String _getPropertyAsDouble_name = "";
        double _getPropertyAsDouble__return = port.getPropertyAsDouble(_getPropertyAsDouble_authTicket, _getPropertyAsDouble_name);
        System.out.println("getPropertyAsDouble.result=" + _getPropertyAsDouble__return);


        }
        {
        System.out.println("Invoking setProperty...");
        java.lang.String _setProperty_authTicket = "";
        java.lang.String _setProperty_name = "";
        java.lang.String _setProperty_valueString = "";
        port.setProperty(_setProperty_authTicket, _setProperty_name, _setProperty_valueString);


        }
        {
        System.out.println("Invoking getPropertyAsInt...");
        java.lang.String _getPropertyAsInt_authTicket = "";
        java.lang.String _getPropertyAsInt_name = "";
        long _getPropertyAsInt__return = port.getPropertyAsInt(_getPropertyAsInt_authTicket, _getPropertyAsInt_name);
        System.out.println("getPropertyAsInt.result=" + _getPropertyAsInt__return);


        }
        {
        System.out.println("Invoking setDevices...");
        java.lang.String _setDevices_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _setDevices_bags = null;
        port.setDevices(_setDevices_authTicket, _setDevices_bags);


        }
        {
        System.out.println("Invoking setPropertyAsBool...");
        java.lang.String _setPropertyAsBool_authTicket = "";
        java.lang.String _setPropertyAsBool_name = "";
        boolean _setPropertyAsBool_val = false;
        port.setPropertyAsBool(_setPropertyAsBool_authTicket, _setPropertyAsBool_name, _setPropertyAsBool_val);


        }
        {
        System.out.println("Invoking getProperty...");
        java.lang.String _getProperty_authTicket = "";
        java.lang.String _getProperty_name = "";
        java.lang.String _getProperty__return = port.getProperty(_getProperty_authTicket, _getProperty_name);
        System.out.println("getProperty.result=" + _getProperty__return);


        }
        {
        System.out.println("Invoking getOEMCode...");
        java.lang.String _getOEMCode_authTicket = "";
        int _getOEMCode__return = port.getOEMCode(_getOEMCode_authTicket);
        System.out.println("getOEMCode.result=" + _getOEMCode__return);


        }
        {
        System.out.println("Invoking getUserLineups...");
        java.lang.String _getUserLineups_authTicket = "";
        java.lang.String _getUserLineups__return = port.getUserLineups(_getUserLineups_authTicket);
        System.out.println("getUserLineups.result=" + _getUserLineups__return);


        }
        {
        System.out.println("Invoking getPropertyBagCollection...");
        java.lang.String _getPropertyBagCollection_authTicket = "";
        java.lang.String _getPropertyBagCollection_name = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getPropertyBagCollection__return = port.getPropertyBagCollection(_getPropertyBagCollection_authTicket, _getPropertyBagCollection_name);
        System.out.println("getPropertyBagCollection.result=" + _getPropertyBagCollection__return);


        }
        {
        System.out.println("Invoking writeSettingsToDisk...");
        java.lang.String _writeSettingsToDisk_authTicket = "";
        port.writeSettingsToDisk(_writeSettingsToDisk_authTicket);


        }
        {
        System.out.println("Invoking getRadioLineup...");
        java.lang.String _getRadioLineup_authTicket = "";
        java.lang.String _getRadioLineup__return = port.getRadioLineup(_getRadioLineup_authTicket);
        System.out.println("getRadioLineup.result=" + _getRadioLineup__return);


        }
        {
        System.out.println("Invoking getFeature...");
        java.lang.String _getFeature_authTicket = "";
        java.lang.String _getFeature_name = "";
        java.lang.String _getFeature__return = port.getFeature(_getFeature_authTicket, _getFeature_name);
        System.out.println("getFeature.result=" + _getFeature__return);


        }
        {
        System.out.println("Invoking getNetURL...");
        java.lang.String _getNetURL_authTicket = "";
        java.lang.String _getNetURL__return = port.getNetURL(_getNetURL_authTicket);
        System.out.println("getNetURL.result=" + _getNetURL__return);


        }

        System.exit(0);
    }

}
