package com.snapstream.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-05-05T12:55:49.265-06:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://www.snapstream.com/WebService", name = "BTVSchedulerSoap")
@XmlSeeAlso({com.snapstream.types.ObjectFactory.class, ObjectFactory.class})
public interface BTVSchedulerSoap {

    @WebResult(name = "GetNextRecordingResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetNextRecording", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetNextRecording")
    @WebMethod(operationName = "GetNextRecording", action = "http://www.snapstream.com/WebService/GetNextRecording")
    @ResponseWrapper(localName = "GetNextRecordingResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetNextRecordingResponse")
    public com.snapstream.types.PVSPropertyBag getNextRecording(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );

    @RequestWrapper(localName = "AddRecentRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.AddRecentRecordings")
    @WebMethod(operationName = "AddRecentRecordings", action = "http://www.snapstream.com/WebService/AddRecentRecordings")
    @ResponseWrapper(localName = "AddRecentRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.AddRecentRecordingsResponse")
    public void addRecentRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        com.snapstream.webservice.ArrayOfPVSPropertyBag bags
    );

    @RequestWrapper(localName = "AddForcedRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.AddForcedRecordings")
    @WebMethod(operationName = "AddForcedRecordings", action = "http://www.snapstream.com/WebService/AddForcedRecordings")
    @ResponseWrapper(localName = "AddForcedRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.AddForcedRecordingsResponse")
    public void addForcedRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        com.snapstream.webservice.ArrayOfPVSPropertyBag bags
    );

    @WebResult(name = "GetLastRebuildResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetLastRebuild", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetLastRebuild")
    @WebMethod(operationName = "GetLastRebuild", action = "http://www.snapstream.com/WebService/GetLastRebuild")
    @ResponseWrapper(localName = "GetLastRebuildResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetLastRebuildResponse")
    public java.math.BigInteger getLastRebuild(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );

    @RequestWrapper(localName = "AddRecordingJobs", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.AddRecordingJobs")
    @WebMethod(operationName = "AddRecordingJobs", action = "http://www.snapstream.com/WebService/AddRecordingJobs")
    @ResponseWrapper(localName = "AddRecordingJobsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.AddRecordingJobsResponse")
    public void addRecordingJobs(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        com.snapstream.webservice.ArrayOfPVSPropertyBag bags,
        @WebParam(name = "highestPriority", targetNamespace = "http://www.snapstream.com/WebService")
        int highestPriority
    );

    @WebResult(name = "GetRecentRecordingsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetRecentRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetRecentRecordings")
    @WebMethod(operationName = "GetRecentRecordings", action = "http://www.snapstream.com/WebService/GetRecentRecordings")
    @ResponseWrapper(localName = "GetRecentRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetRecentRecordingsResponse")
    public com.snapstream.webservice.ArrayOfPVSPropertyBag getRecentRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );

    @WebResult(name = "GetEpisodeCollectionStatusResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetEpisodeCollectionStatus", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetEpisodeCollectionStatus")
    @WebMethod(operationName = "GetEpisodeCollectionStatus", action = "http://www.snapstream.com/WebService/GetEpisodeCollectionStatus")
    @ResponseWrapper(localName = "GetEpisodeCollectionStatusResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetEpisodeCollectionStatusResponse")
    public com.snapstream.webservice.ArrayOfPVSPropertyBag getEpisodeCollectionStatus(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        com.snapstream.webservice.ArrayOfPVSPropertyBag bags
    );

    @WebResult(name = "GetUpcomingRecordingsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetUpcomingRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetUpcomingRecordings")
    @WebMethod(operationName = "GetUpcomingRecordings", action = "http://www.snapstream.com/WebService/GetUpcomingRecordings")
    @ResponseWrapper(localName = "GetUpcomingRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetUpcomingRecordingsResponse")
    public com.snapstream.webservice.ArrayOfPVSPropertyBag getUpcomingRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );

    @RequestWrapper(localName = "AddRecentRecordingByGUID", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.AddRecentRecordingByGUID")
    @WebMethod(operationName = "AddRecentRecordingByGUID", action = "http://www.snapstream.com/WebService/AddRecentRecordingByGUID")
    @ResponseWrapper(localName = "AddRecentRecordingByGUIDResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.AddRecentRecordingByGUIDResponse")
    public void addRecentRecordingByGUID(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String guid
    );

    @WebResult(name = "HasPotentialConflictsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "HasPotentialConflicts", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.HasPotentialConflicts")
    @WebMethod(operationName = "HasPotentialConflicts", action = "http://www.snapstream.com/WebService/HasPotentialConflicts")
    @ResponseWrapper(localName = "HasPotentialConflictsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.HasPotentialConflictsResponse")
    public int hasPotentialConflicts(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bag", targetNamespace = "http://www.snapstream.com/WebService")
        com.snapstream.types.PVSPropertyBag bag
    );

    @RequestWrapper(localName = "ReprioritizeJob", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.ReprioritizeJob")
    @WebMethod(operationName = "ReprioritizeJob", action = "http://www.snapstream.com/WebService/ReprioritizeJob")
    @ResponseWrapper(localName = "ReprioritizeJobResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.ReprioritizeJobResponse")
    public void reprioritizeJob(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String guid,
        @WebParam(name = "priority", targetNamespace = "http://www.snapstream.com/WebService")
        long priority
    );

    @RequestWrapper(localName = "RemoveForcedRecordingsByGUID", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.RemoveForcedRecordingsByGUID")
    @WebMethod(operationName = "RemoveForcedRecordingsByGUID", action = "http://www.snapstream.com/WebService/RemoveForcedRecordingsByGUID")
    @ResponseWrapper(localName = "RemoveForcedRecordingsByGUIDResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.RemoveForcedRecordingsByGUIDResponse")
    public void removeForcedRecordingsByGUID(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        com.snapstream.webservice.ArrayOfPVSPropertyBag bags
    );

    @WebResult(name = "GetForcedRecordingsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetForcedRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetForcedRecordings")
    @WebMethod(operationName = "GetForcedRecordings", action = "http://www.snapstream.com/WebService/GetForcedRecordings")
    @ResponseWrapper(localName = "GetForcedRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetForcedRecordingsResponse")
    public com.snapstream.webservice.ArrayOfPVSPropertyBag getForcedRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );

    @WebResult(name = "GetExistingConflictsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetExistingConflicts", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetExistingConflicts")
    @WebMethod(operationName = "GetExistingConflicts", action = "http://www.snapstream.com/WebService/GetExistingConflicts")
    @ResponseWrapper(localName = "GetExistingConflictsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetExistingConflictsResponse")
    public com.snapstream.webservice.ArrayOfPVSPropertyBag getExistingConflicts(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String guid
    );

    @WebResult(name = "GetEpisodeStatusResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetEpisodeStatus", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetEpisodeStatus")
    @WebMethod(operationName = "GetEpisodeStatus", action = "http://www.snapstream.com/WebService/GetEpisodeStatus")
    @ResponseWrapper(localName = "GetEpisodeStatusResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetEpisodeStatusResponse")
    public com.snapstream.types.PVSPropertyBag getEpisodeStatus(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bag", targetNamespace = "http://www.snapstream.com/WebService")
        com.snapstream.types.PVSPropertyBag bag
    );

    @WebResult(name = "GetPotentialScheduleAtPriorityResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetPotentialScheduleAtPriority", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetPotentialScheduleAtPriority")
    @WebMethod(operationName = "GetPotentialScheduleAtPriority", action = "http://www.snapstream.com/WebService/GetPotentialScheduleAtPriority")
    @ResponseWrapper(localName = "GetPotentialScheduleAtPriorityResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetPotentialScheduleAtPriorityResponse")
    public com.snapstream.webservice.ArrayOfPVSPropertyBagArray getPotentialScheduleAtPriority(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bag", targetNamespace = "http://www.snapstream.com/WebService")
        com.snapstream.types.PVSPropertyBag bag,
        @WebParam(name = "priority", targetNamespace = "http://www.snapstream.com/WebService")
        long priority
    );

    @WebResult(name = "GetJobByGUIDResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetJobByGUID", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetJobByGUID")
    @WebMethod(operationName = "GetJobByGUID", action = "http://www.snapstream.com/WebService/GetJobByGUID")
    @ResponseWrapper(localName = "GetJobByGUIDResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetJobByGUIDResponse")
    public com.snapstream.types.PVSPropertyBag getJobByGUID(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String guid
    );

    @WebResult(name = "HasExistingConflictsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "HasExistingConflicts", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.HasExistingConflicts")
    @WebMethod(operationName = "HasExistingConflicts", action = "http://www.snapstream.com/WebService/HasExistingConflicts")
    @ResponseWrapper(localName = "HasExistingConflictsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.HasExistingConflictsResponse")
    public int hasExistingConflicts(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String guid
    );

    @WebResult(name = "GetPossibleRecordingsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetPossibleRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetPossibleRecordings")
    @WebMethod(operationName = "GetPossibleRecordings", action = "http://www.snapstream.com/WebService/GetPossibleRecordings")
    @ResponseWrapper(localName = "GetPossibleRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetPossibleRecordingsResponse")
    public com.snapstream.webservice.ArrayOfPVSPropertyBag getPossibleRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );

    @WebResult(name = "IsSeriesManagedResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "IsSeriesManaged", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.IsSeriesManaged")
    @WebMethod(operationName = "IsSeriesManaged", action = "http://www.snapstream.com/WebService/IsSeriesManaged")
    @ResponseWrapper(localName = "IsSeriesManagedResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.IsSeriesManagedResponse")
    public boolean isSeriesManaged(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bstrEPGID", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String bstrEPGID
    );

    @RequestWrapper(localName = "ReprioritizeJobs", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.ReprioritizeJobs")
    @WebMethod(operationName = "ReprioritizeJobs", action = "http://www.snapstream.com/WebService/ReprioritizeJobs")
    @ResponseWrapper(localName = "ReprioritizeJobsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.ReprioritizeJobsResponse")
    public void reprioritizeJobs(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        com.snapstream.webservice.ArrayOfPVSPropertyBag bags
    );

    @RequestWrapper(localName = "ClearPopularityJobs", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.ClearPopularityJobs")
    @WebMethod(operationName = "ClearPopularityJobs", action = "http://www.snapstream.com/WebService/ClearPopularityJobs")
    @ResponseWrapper(localName = "ClearPopularityJobsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.ClearPopularityJobsResponse")
    public void clearPopularityJobs(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );

    @RequestWrapper(localName = "RemoveRecentRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.RemoveRecentRecordings")
    @WebMethod(operationName = "RemoveRecentRecordings", action = "http://www.snapstream.com/WebService/RemoveRecentRecordings")
    @ResponseWrapper(localName = "RemoveRecentRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.RemoveRecentRecordingsResponse")
    public void removeRecentRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        com.snapstream.webservice.ArrayOfPVSPropertyBag bags
    );

    @WebResult(name = "GetJobsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetJobs", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetJobs")
    @WebMethod(operationName = "GetJobs", action = "http://www.snapstream.com/WebService/GetJobs")
    @ResponseWrapper(localName = "GetJobsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetJobsResponse")
    public com.snapstream.webservice.ArrayOfPVSPropertyBag getJobs(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );

    @WebResult(name = "GetBlockedRecordingsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetBlockedRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetBlockedRecordings")
    @WebMethod(operationName = "GetBlockedRecordings", action = "http://www.snapstream.com/WebService/GetBlockedRecordings")
    @ResponseWrapper(localName = "GetBlockedRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetBlockedRecordingsResponse")
    public com.snapstream.webservice.ArrayOfPVSPropertyBag getBlockedRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );

    @RequestWrapper(localName = "RemoveBlockedRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.RemoveBlockedRecordings")
    @WebMethod(operationName = "RemoveBlockedRecordings", action = "http://www.snapstream.com/WebService/RemoveBlockedRecordings")
    @ResponseWrapper(localName = "RemoveBlockedRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.RemoveBlockedRecordingsResponse")
    public void removeBlockedRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        com.snapstream.webservice.ArrayOfPVSPropertyBag bags
    );

    @RequestWrapper(localName = "RemoveForcedRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.RemoveForcedRecordings")
    @WebMethod(operationName = "RemoveForcedRecordings", action = "http://www.snapstream.com/WebService/RemoveForcedRecordings")
    @ResponseWrapper(localName = "RemoveForcedRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.RemoveForcedRecordingsResponse")
    public void removeForcedRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        com.snapstream.webservice.ArrayOfPVSPropertyBag bags
    );

    @WebResult(name = "GetLastRecordingResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetLastRecording", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetLastRecording")
    @WebMethod(operationName = "GetLastRecording", action = "http://www.snapstream.com/WebService/GetLastRecording")
    @ResponseWrapper(localName = "GetLastRecordingResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetLastRecordingResponse")
    public com.snapstream.types.PVSPropertyBag getLastRecording(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );

    @RequestWrapper(localName = "RemoveRecentRecordingsByGUID", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.RemoveRecentRecordingsByGUID")
    @WebMethod(operationName = "RemoveRecentRecordingsByGUID", action = "http://www.snapstream.com/WebService/RemoveRecentRecordingsByGUID")
    @ResponseWrapper(localName = "RemoveRecentRecordingsByGUIDResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.RemoveRecentRecordingsByGUIDResponse")
    public void removeRecentRecordingsByGUID(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        com.snapstream.webservice.ArrayOfPVSPropertyBag bags
    );

    @RequestWrapper(localName = "AddBlockedRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.AddBlockedRecordings")
    @WebMethod(operationName = "AddBlockedRecordings", action = "http://www.snapstream.com/WebService/AddBlockedRecordings")
    @ResponseWrapper(localName = "AddBlockedRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.AddBlockedRecordingsResponse")
    public void addBlockedRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        com.snapstream.webservice.ArrayOfPVSPropertyBag bags
    );

    @RequestWrapper(localName = "RemoveBlockedRecordingsByGUID", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.RemoveBlockedRecordingsByGUID")
    @WebMethod(operationName = "RemoveBlockedRecordingsByGUID", action = "http://www.snapstream.com/WebService/RemoveBlockedRecordingsByGUID")
    @ResponseWrapper(localName = "RemoveBlockedRecordingsByGUIDResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.RemoveBlockedRecordingsByGUIDResponse")
    public void removeBlockedRecordingsByGUID(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        com.snapstream.webservice.ArrayOfPVSPropertyBag bags
    );

    @RequestWrapper(localName = "AddRecordingJob", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.AddRecordingJob")
    @WebMethod(operationName = "AddRecordingJob", action = "http://www.snapstream.com/WebService/AddRecordingJob")
    @ResponseWrapper(localName = "AddRecordingJobResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.AddRecordingJobResponse")
    public void addRecordingJob(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bag", targetNamespace = "http://www.snapstream.com/WebService")
        com.snapstream.types.PVSPropertyBag bag,
        @WebParam(name = "highestPriority", targetNamespace = "http://www.snapstream.com/WebService")
        int highestPriority
    );

    @RequestWrapper(localName = "AddBlockedRecordingByGUID", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.AddBlockedRecordingByGUID")
    @WebMethod(operationName = "AddBlockedRecordingByGUID", action = "http://www.snapstream.com/WebService/AddBlockedRecordingByGUID")
    @ResponseWrapper(localName = "AddBlockedRecordingByGUIDResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.AddBlockedRecordingByGUIDResponse")
    public void addBlockedRecordingByGUID(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String guid
    );

    @RequestWrapper(localName = "EditRecordingJob", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.EditRecordingJob")
    @WebMethod(operationName = "EditRecordingJob", action = "http://www.snapstream.com/WebService/EditRecordingJob")
    @ResponseWrapper(localName = "EditRecordingJobResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.EditRecordingJobResponse")
    public void editRecordingJob(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String guid,
        @WebParam(name = "bag", targetNamespace = "http://www.snapstream.com/WebService")
        com.snapstream.types.PVSPropertyBag bag
    );

    @WebResult(name = "GetUpcomingRecordingDurationResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetUpcomingRecordingDuration", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetUpcomingRecordingDuration")
    @WebMethod(operationName = "GetUpcomingRecordingDuration", action = "http://www.snapstream.com/WebService/GetUpcomingRecordingDuration")
    @ResponseWrapper(localName = "GetUpcomingRecordingDurationResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetUpcomingRecordingDurationResponse")
    public java.math.BigInteger getUpcomingRecordingDuration(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );

    @WebResult(name = "GetPotentialConflictsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetPotentialConflicts", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetPotentialConflicts")
    @WebMethod(operationName = "GetPotentialConflicts", action = "http://www.snapstream.com/WebService/GetPotentialConflicts")
    @ResponseWrapper(localName = "GetPotentialConflictsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetPotentialConflictsResponse")
    public com.snapstream.webservice.ArrayOfPVSPropertyBag getPotentialConflicts(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bag", targetNamespace = "http://www.snapstream.com/WebService")
        com.snapstream.types.PVSPropertyBag bag
    );

    @RequestWrapper(localName = "EditRecordingJobs", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.EditRecordingJobs")
    @WebMethod(operationName = "EditRecordingJobs", action = "http://www.snapstream.com/WebService/EditRecordingJobs")
    @ResponseWrapper(localName = "EditRecordingJobsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.EditRecordingJobsResponse")
    public void editRecordingJobs(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        com.snapstream.webservice.ArrayOfPVSPropertyBag bags
    );

    @RequestWrapper(localName = "AddForcedRecordingByGUID", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.AddForcedRecordingByGUID")
    @WebMethod(operationName = "AddForcedRecordingByGUID", action = "http://www.snapstream.com/WebService/AddForcedRecordingByGUID")
    @ResponseWrapper(localName = "AddForcedRecordingByGUIDResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.AddForcedRecordingByGUIDResponse")
    public void addForcedRecordingByGUID(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String guid
    );

    @WebResult(name = "GetRejectedRecordingsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetRejectedRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetRejectedRecordings")
    @WebMethod(operationName = "GetRejectedRecordings", action = "http://www.snapstream.com/WebService/GetRejectedRecordings")
    @ResponseWrapper(localName = "GetRejectedRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetRejectedRecordingsResponse")
    public com.snapstream.webservice.ArrayOfPVSPropertyBag getRejectedRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket
    );

    @WebResult(name = "GetPotentialRecordingsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetPotentialRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetPotentialRecordings")
    @WebMethod(operationName = "GetPotentialRecordings", action = "http://www.snapstream.com/WebService/GetPotentialRecordings")
    @ResponseWrapper(localName = "GetPotentialRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetPotentialRecordingsResponse")
    public com.snapstream.webservice.ArrayOfPVSPropertyBag getPotentialRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bag", targetNamespace = "http://www.snapstream.com/WebService")
        com.snapstream.types.PVSPropertyBag bag
    );

    @WebResult(name = "GetRecordingsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetRecordings")
    @WebMethod(operationName = "GetRecordings", action = "http://www.snapstream.com/WebService/GetRecordings")
    @ResponseWrapper(localName = "GetRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.GetRecordingsResponse")
    public com.snapstream.webservice.ArrayOfPVSPropertyBag getRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String guid
    );

    @RequestWrapper(localName = "RemoveRecordingJobs", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.RemoveRecordingJobs")
    @WebMethod(operationName = "RemoveRecordingJobs", action = "http://www.snapstream.com/WebService/RemoveRecordingJobs")
    @ResponseWrapper(localName = "RemoveRecordingJobsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.RemoveRecordingJobsResponse")
    public void removeRecordingJobs(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        com.snapstream.webservice.ArrayOfPVSPropertyBag bags
    );

    @RequestWrapper(localName = "RemoveRecordingJob", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.RemoveRecordingJob")
    @WebMethod(operationName = "RemoveRecordingJob", action = "http://www.snapstream.com/WebService/RemoveRecordingJob")
    @ResponseWrapper(localName = "RemoveRecordingJobResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "com.snapstream.webservice.RemoveRecordingJobResponse")
    public void removeRecordingJob(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        java.lang.String guid
    );
}
