
package com.snapstream.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-05-05T12:55:49.117-06:00
 * Generated source version: 2.4.0
 * 
 */
public final class BTVSchedulerSoap_BTVSchedulerSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://www.snapstream.com/WebService", "BTVScheduler");

    private BTVSchedulerSoap_BTVSchedulerSoap12_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = BTVScheduler.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BTVScheduler ss = new BTVScheduler(wsdlURL, SERVICE_NAME);
        BTVSchedulerSoap port = ss.getBTVSchedulerSoap12();  
        
        {
        System.out.println("Invoking getNextRecording...");
        java.lang.String _getNextRecording_authTicket = "";
        com.snapstream.types.PVSPropertyBag _getNextRecording__return = port.getNextRecording(_getNextRecording_authTicket);
        System.out.println("getNextRecording.result=" + _getNextRecording__return);


        }
        {
        System.out.println("Invoking addRecentRecordings...");
        java.lang.String _addRecentRecordings_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _addRecentRecordings_bags = null;
        port.addRecentRecordings(_addRecentRecordings_authTicket, _addRecentRecordings_bags);


        }
        {
        System.out.println("Invoking addForcedRecordings...");
        java.lang.String _addForcedRecordings_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _addForcedRecordings_bags = null;
        port.addForcedRecordings(_addForcedRecordings_authTicket, _addForcedRecordings_bags);


        }
        {
        System.out.println("Invoking getLastRebuild...");
        java.lang.String _getLastRebuild_authTicket = "";
        java.math.BigInteger _getLastRebuild__return = port.getLastRebuild(_getLastRebuild_authTicket);
        System.out.println("getLastRebuild.result=" + _getLastRebuild__return);


        }
        {
        System.out.println("Invoking addRecordingJobs...");
        java.lang.String _addRecordingJobs_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _addRecordingJobs_bags = null;
        int _addRecordingJobs_highestPriority = 0;
        port.addRecordingJobs(_addRecordingJobs_authTicket, _addRecordingJobs_bags, _addRecordingJobs_highestPriority);


        }
        {
        System.out.println("Invoking getRecentRecordings...");
        java.lang.String _getRecentRecordings_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getRecentRecordings__return = port.getRecentRecordings(_getRecentRecordings_authTicket);
        System.out.println("getRecentRecordings.result=" + _getRecentRecordings__return);


        }
        {
        System.out.println("Invoking getEpisodeCollectionStatus...");
        java.lang.String _getEpisodeCollectionStatus_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getEpisodeCollectionStatus_bags = null;
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getEpisodeCollectionStatus__return = port.getEpisodeCollectionStatus(_getEpisodeCollectionStatus_authTicket, _getEpisodeCollectionStatus_bags);
        System.out.println("getEpisodeCollectionStatus.result=" + _getEpisodeCollectionStatus__return);


        }
        {
        System.out.println("Invoking getUpcomingRecordings...");
        java.lang.String _getUpcomingRecordings_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getUpcomingRecordings__return = port.getUpcomingRecordings(_getUpcomingRecordings_authTicket);
        System.out.println("getUpcomingRecordings.result=" + _getUpcomingRecordings__return);


        }
        {
        System.out.println("Invoking addRecentRecordingByGUID...");
        java.lang.String _addRecentRecordingByGUID_authTicket = "";
        java.lang.String _addRecentRecordingByGUID_guid = "";
        port.addRecentRecordingByGUID(_addRecentRecordingByGUID_authTicket, _addRecentRecordingByGUID_guid);


        }
        {
        System.out.println("Invoking hasPotentialConflicts...");
        java.lang.String _hasPotentialConflicts_authTicket = "";
        com.snapstream.types.PVSPropertyBag _hasPotentialConflicts_bag = null;
        int _hasPotentialConflicts__return = port.hasPotentialConflicts(_hasPotentialConflicts_authTicket, _hasPotentialConflicts_bag);
        System.out.println("hasPotentialConflicts.result=" + _hasPotentialConflicts__return);


        }
        {
        System.out.println("Invoking reprioritizeJob...");
        java.lang.String _reprioritizeJob_authTicket = "";
        java.lang.String _reprioritizeJob_guid = "";
        long _reprioritizeJob_priority = 0;
        port.reprioritizeJob(_reprioritizeJob_authTicket, _reprioritizeJob_guid, _reprioritizeJob_priority);


        }
        {
        System.out.println("Invoking removeForcedRecordingsByGUID...");
        java.lang.String _removeForcedRecordingsByGUID_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _removeForcedRecordingsByGUID_bags = null;
        port.removeForcedRecordingsByGUID(_removeForcedRecordingsByGUID_authTicket, _removeForcedRecordingsByGUID_bags);


        }
        {
        System.out.println("Invoking getForcedRecordings...");
        java.lang.String _getForcedRecordings_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getForcedRecordings__return = port.getForcedRecordings(_getForcedRecordings_authTicket);
        System.out.println("getForcedRecordings.result=" + _getForcedRecordings__return);


        }
        {
        System.out.println("Invoking getExistingConflicts...");
        java.lang.String _getExistingConflicts_authTicket = "";
        java.lang.String _getExistingConflicts_guid = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getExistingConflicts__return = port.getExistingConflicts(_getExistingConflicts_authTicket, _getExistingConflicts_guid);
        System.out.println("getExistingConflicts.result=" + _getExistingConflicts__return);


        }
        {
        System.out.println("Invoking getEpisodeStatus...");
        java.lang.String _getEpisodeStatus_authTicket = "";
        com.snapstream.types.PVSPropertyBag _getEpisodeStatus_bag = null;
        com.snapstream.types.PVSPropertyBag _getEpisodeStatus__return = port.getEpisodeStatus(_getEpisodeStatus_authTicket, _getEpisodeStatus_bag);
        System.out.println("getEpisodeStatus.result=" + _getEpisodeStatus__return);


        }
        {
        System.out.println("Invoking getPotentialScheduleAtPriority...");
        java.lang.String _getPotentialScheduleAtPriority_authTicket = "";
        com.snapstream.types.PVSPropertyBag _getPotentialScheduleAtPriority_bag = null;
        long _getPotentialScheduleAtPriority_priority = 0;
        com.snapstream.webservice.ArrayOfPVSPropertyBagArray _getPotentialScheduleAtPriority__return = port.getPotentialScheduleAtPriority(_getPotentialScheduleAtPriority_authTicket, _getPotentialScheduleAtPriority_bag, _getPotentialScheduleAtPriority_priority);
        System.out.println("getPotentialScheduleAtPriority.result=" + _getPotentialScheduleAtPriority__return);


        }
        {
        System.out.println("Invoking getJobByGUID...");
        java.lang.String _getJobByGUID_authTicket = "";
        java.lang.String _getJobByGUID_guid = "";
        com.snapstream.types.PVSPropertyBag _getJobByGUID__return = port.getJobByGUID(_getJobByGUID_authTicket, _getJobByGUID_guid);
        System.out.println("getJobByGUID.result=" + _getJobByGUID__return);


        }
        {
        System.out.println("Invoking hasExistingConflicts...");
        java.lang.String _hasExistingConflicts_authTicket = "";
        java.lang.String _hasExistingConflicts_guid = "";
        int _hasExistingConflicts__return = port.hasExistingConflicts(_hasExistingConflicts_authTicket, _hasExistingConflicts_guid);
        System.out.println("hasExistingConflicts.result=" + _hasExistingConflicts__return);


        }
        {
        System.out.println("Invoking getPossibleRecordings...");
        java.lang.String _getPossibleRecordings_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getPossibleRecordings__return = port.getPossibleRecordings(_getPossibleRecordings_authTicket);
        System.out.println("getPossibleRecordings.result=" + _getPossibleRecordings__return);


        }
        {
        System.out.println("Invoking isSeriesManaged...");
        java.lang.String _isSeriesManaged_authTicket = "";
        java.lang.String _isSeriesManaged_bstrEPGID = "";
        boolean _isSeriesManaged__return = port.isSeriesManaged(_isSeriesManaged_authTicket, _isSeriesManaged_bstrEPGID);
        System.out.println("isSeriesManaged.result=" + _isSeriesManaged__return);


        }
        {
        System.out.println("Invoking reprioritizeJobs...");
        java.lang.String _reprioritizeJobs_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _reprioritizeJobs_bags = null;
        port.reprioritizeJobs(_reprioritizeJobs_authTicket, _reprioritizeJobs_bags);


        }
        {
        System.out.println("Invoking clearPopularityJobs...");
        java.lang.String _clearPopularityJobs_authTicket = "";
        port.clearPopularityJobs(_clearPopularityJobs_authTicket);


        }
        {
        System.out.println("Invoking removeRecentRecordings...");
        java.lang.String _removeRecentRecordings_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _removeRecentRecordings_bags = null;
        port.removeRecentRecordings(_removeRecentRecordings_authTicket, _removeRecentRecordings_bags);


        }
        {
        System.out.println("Invoking getJobs...");
        java.lang.String _getJobs_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getJobs__return = port.getJobs(_getJobs_authTicket);
        System.out.println("getJobs.result=" + _getJobs__return);


        }
        {
        System.out.println("Invoking getBlockedRecordings...");
        java.lang.String _getBlockedRecordings_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getBlockedRecordings__return = port.getBlockedRecordings(_getBlockedRecordings_authTicket);
        System.out.println("getBlockedRecordings.result=" + _getBlockedRecordings__return);


        }
        {
        System.out.println("Invoking removeBlockedRecordings...");
        java.lang.String _removeBlockedRecordings_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _removeBlockedRecordings_bags = null;
        port.removeBlockedRecordings(_removeBlockedRecordings_authTicket, _removeBlockedRecordings_bags);


        }
        {
        System.out.println("Invoking removeForcedRecordings...");
        java.lang.String _removeForcedRecordings_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _removeForcedRecordings_bags = null;
        port.removeForcedRecordings(_removeForcedRecordings_authTicket, _removeForcedRecordings_bags);


        }
        {
        System.out.println("Invoking getLastRecording...");
        java.lang.String _getLastRecording_authTicket = "";
        com.snapstream.types.PVSPropertyBag _getLastRecording__return = port.getLastRecording(_getLastRecording_authTicket);
        System.out.println("getLastRecording.result=" + _getLastRecording__return);


        }
        {
        System.out.println("Invoking removeRecentRecordingsByGUID...");
        java.lang.String _removeRecentRecordingsByGUID_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _removeRecentRecordingsByGUID_bags = null;
        port.removeRecentRecordingsByGUID(_removeRecentRecordingsByGUID_authTicket, _removeRecentRecordingsByGUID_bags);


        }
        {
        System.out.println("Invoking addBlockedRecordings...");
        java.lang.String _addBlockedRecordings_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _addBlockedRecordings_bags = null;
        port.addBlockedRecordings(_addBlockedRecordings_authTicket, _addBlockedRecordings_bags);


        }
        {
        System.out.println("Invoking removeBlockedRecordingsByGUID...");
        java.lang.String _removeBlockedRecordingsByGUID_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _removeBlockedRecordingsByGUID_bags = null;
        port.removeBlockedRecordingsByGUID(_removeBlockedRecordingsByGUID_authTicket, _removeBlockedRecordingsByGUID_bags);


        }
        {
        System.out.println("Invoking addRecordingJob...");
        java.lang.String _addRecordingJob_authTicket = "";
        com.snapstream.types.PVSPropertyBag _addRecordingJob_bag = null;
        int _addRecordingJob_highestPriority = 0;
        port.addRecordingJob(_addRecordingJob_authTicket, _addRecordingJob_bag, _addRecordingJob_highestPriority);


        }
        {
        System.out.println("Invoking addBlockedRecordingByGUID...");
        java.lang.String _addBlockedRecordingByGUID_authTicket = "";
        java.lang.String _addBlockedRecordingByGUID_guid = "";
        port.addBlockedRecordingByGUID(_addBlockedRecordingByGUID_authTicket, _addBlockedRecordingByGUID_guid);


        }
        {
        System.out.println("Invoking editRecordingJob...");
        java.lang.String _editRecordingJob_authTicket = "";
        java.lang.String _editRecordingJob_guid = "";
        com.snapstream.types.PVSPropertyBag _editRecordingJob_bag = null;
        port.editRecordingJob(_editRecordingJob_authTicket, _editRecordingJob_guid, _editRecordingJob_bag);


        }
        {
        System.out.println("Invoking getUpcomingRecordingDuration...");
        java.lang.String _getUpcomingRecordingDuration_authTicket = "";
        java.math.BigInteger _getUpcomingRecordingDuration__return = port.getUpcomingRecordingDuration(_getUpcomingRecordingDuration_authTicket);
        System.out.println("getUpcomingRecordingDuration.result=" + _getUpcomingRecordingDuration__return);


        }
        {
        System.out.println("Invoking getPotentialConflicts...");
        java.lang.String _getPotentialConflicts_authTicket = "";
        com.snapstream.types.PVSPropertyBag _getPotentialConflicts_bag = null;
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getPotentialConflicts__return = port.getPotentialConflicts(_getPotentialConflicts_authTicket, _getPotentialConflicts_bag);
        System.out.println("getPotentialConflicts.result=" + _getPotentialConflicts__return);


        }
        {
        System.out.println("Invoking editRecordingJobs...");
        java.lang.String _editRecordingJobs_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _editRecordingJobs_bags = null;
        port.editRecordingJobs(_editRecordingJobs_authTicket, _editRecordingJobs_bags);


        }
        {
        System.out.println("Invoking addForcedRecordingByGUID...");
        java.lang.String _addForcedRecordingByGUID_authTicket = "";
        java.lang.String _addForcedRecordingByGUID_guid = "";
        port.addForcedRecordingByGUID(_addForcedRecordingByGUID_authTicket, _addForcedRecordingByGUID_guid);


        }
        {
        System.out.println("Invoking getRejectedRecordings...");
        java.lang.String _getRejectedRecordings_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getRejectedRecordings__return = port.getRejectedRecordings(_getRejectedRecordings_authTicket);
        System.out.println("getRejectedRecordings.result=" + _getRejectedRecordings__return);


        }
        {
        System.out.println("Invoking getPotentialRecordings...");
        java.lang.String _getPotentialRecordings_authTicket = "";
        com.snapstream.types.PVSPropertyBag _getPotentialRecordings_bag = null;
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getPotentialRecordings__return = port.getPotentialRecordings(_getPotentialRecordings_authTicket, _getPotentialRecordings_bag);
        System.out.println("getPotentialRecordings.result=" + _getPotentialRecordings__return);


        }
        {
        System.out.println("Invoking getRecordings...");
        java.lang.String _getRecordings_authTicket = "";
        java.lang.String _getRecordings_guid = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _getRecordings__return = port.getRecordings(_getRecordings_authTicket, _getRecordings_guid);
        System.out.println("getRecordings.result=" + _getRecordings__return);


        }
        {
        System.out.println("Invoking removeRecordingJobs...");
        java.lang.String _removeRecordingJobs_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _removeRecordingJobs_bags = null;
        port.removeRecordingJobs(_removeRecordingJobs_authTicket, _removeRecordingJobs_bags);


        }
        {
        System.out.println("Invoking removeRecordingJob...");
        java.lang.String _removeRecordingJob_authTicket = "";
        java.lang.String _removeRecordingJob_guid = "";
        port.removeRecordingJob(_removeRecordingJob_authTicket, _removeRecordingJob_guid);


        }

        System.exit(0);
    }

}
