
/*
 * 
 */

package com.snapstream.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-05-05T12:52:41.718-06:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "BTVTaskListProcessor", 
                  wsdlLocation = "file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/BTVBatchProcessor.asmx.xml",
                  targetNamespace = "http://www.snapstream.com/WebService") 
public class BTVTaskListProcessor extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.snapstream.com/WebService", "BTVTaskListProcessor");
    public final static QName BTVTaskListProcessorSoap12 = new QName("http://www.snapstream.com/WebService", "BTVTaskListProcessorSoap12");
    public final static QName BTVTaskListProcessorSoap = new QName("http://www.snapstream.com/WebService", "BTVTaskListProcessorSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/BTVBatchProcessor.asmx.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BTVTaskListProcessor.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/BTVBatchProcessor.asmx.xml");
        }
        WSDL_LOCATION = url;
    }

    public BTVTaskListProcessor(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BTVTaskListProcessor(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BTVTaskListProcessor() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns BTVTaskListProcessorSoap
     */
    @WebEndpoint(name = "BTVTaskListProcessorSoap12")
    public BTVTaskListProcessorSoap getBTVTaskListProcessorSoap12() {
        return super.getPort(BTVTaskListProcessorSoap12, BTVTaskListProcessorSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BTVTaskListProcessorSoap
     */
    @WebEndpoint(name = "BTVTaskListProcessorSoap12")
    public BTVTaskListProcessorSoap getBTVTaskListProcessorSoap12(WebServiceFeature... features) {
        return super.getPort(BTVTaskListProcessorSoap12, BTVTaskListProcessorSoap.class, features);
    }
    /**
     * 
     * @return
     *     returns BTVTaskListProcessorSoap
     */
    @WebEndpoint(name = "BTVTaskListProcessorSoap")
    public BTVTaskListProcessorSoap getBTVTaskListProcessorSoap() {
        return super.getPort(BTVTaskListProcessorSoap, BTVTaskListProcessorSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BTVTaskListProcessorSoap
     */
    @WebEndpoint(name = "BTVTaskListProcessorSoap")
    public BTVTaskListProcessorSoap getBTVTaskListProcessorSoap(WebServiceFeature... features) {
        return super.getPort(BTVTaskListProcessorSoap, BTVTaskListProcessorSoap.class, features);
    }

}
