
package com.snapstream.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-05-05T12:52:41.664-06:00
 * Generated source version: 2.4.0
 * 
 */
public final class BTVTaskListProcessorSoap_BTVTaskListProcessorSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://www.snapstream.com/WebService", "BTVTaskListProcessor");

    private BTVTaskListProcessorSoap_BTVTaskListProcessorSoap_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = BTVTaskListProcessor.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BTVTaskListProcessor ss = new BTVTaskListProcessor(wsdlURL, SERVICE_NAME);
        BTVTaskListProcessorSoap port = ss.getBTVTaskListProcessorSoap();  
        
        {
        System.out.println("Invoking setEnableTimeConstraint...");
        java.lang.String _setEnableTimeConstraint_authTicket = "";
        int _setEnableTimeConstraint_val = 0;
        port.setEnableTimeConstraint(_setEnableTimeConstraint_authTicket, _setEnableTimeConstraint_val);


        }
        {
        System.out.println("Invoking submitClip...");
        java.lang.String _submitClip_authTicket = "";
        com.snapstream.types.PVSPropertyBag _submitClip_bag = null;
        port.submitClip(_submitClip_authTicket, _submitClip_bag);


        }
        {
        System.out.println("Invoking getEnableTimeConstraint...");
        java.lang.String _getEnableTimeConstraint_authTicket = "";
        int _getEnableTimeConstraint__return = port.getEnableTimeConstraint(_getEnableTimeConstraint_authTicket);
        System.out.println("getEnableTimeConstraint.result=" + _getEnableTimeConstraint__return);


        }
        {
        System.out.println("Invoking removeByName...");
        java.lang.String _removeByName_authTicket = "";
        java.lang.String _removeByName_guid = "";
        java.lang.String _removeByName_taskName = "";
        long _removeByName_startingIndex = 0;
        long _removeByName__return = port.removeByName(_removeByName_authTicket, _removeByName_guid, _removeByName_taskName, _removeByName_startingIndex);
        System.out.println("removeByName.result=" + _removeByName__return);


        }
        {
        System.out.println("Invoking remove...");
        java.lang.String _remove_authTicket = "";
        java.lang.String _remove_guid = "";
        port.remove(_remove_authTicket, _remove_guid);


        }
        {
        System.out.println("Invoking submitConvertSSXToAVI...");
        java.lang.String _submitConvertSSXToAVI_authTicket = "";
        com.snapstream.types.PVSPropertyBag _submitConvertSSXToAVI_bag = null;
        port.submitConvertSSXToAVI(_submitConvertSSXToAVI_authTicket, _submitConvertSSXToAVI_bag);


        }
        {
        System.out.println("Invoking run...");
        java.lang.String _run_authTicket = "";
        java.lang.String _run_guid = "";
        port.run(_run_authTicket, _run_guid);


        }
        {
        System.out.println("Invoking submitEmail...");
        java.lang.String _submitEmail_authTicket = "";
        com.snapstream.types.PVSPropertyBag _submitEmail_bag = null;
        port.submitEmail(_submitEmail_authTicket, _submitEmail_bag);


        }
        {
        System.out.println("Invoking reset...");
        java.lang.String _reset_authTicket = "";
        java.lang.String _reset_guid = "";
        port.reset(_reset_authTicket, _reset_guid);


        }
        {
        System.out.println("Invoking itemByIndex...");
        java.lang.String _itemByIndex_authTicket = "";
        long _itemByIndex_index = 0;
        java.lang.String _itemByIndex__return = port.itemByIndex(_itemByIndex_authTicket, _itemByIndex_index);
        System.out.println("itemByIndex.result=" + _itemByIndex__return);


        }
        {
        System.out.println("Invoking isTranscoding...");
        java.lang.String _isTranscoding_authTicket = "";
        int _isTranscoding__return = port.isTranscoding(_isTranscoding_authTicket);
        System.out.println("isTranscoding.result=" + _isTranscoding__return);


        }
        {
        System.out.println("Invoking submitChapterList...");
        java.lang.String _submitChapterList_authTicket = "";
        com.snapstream.types.PVSPropertyBag _submitChapterList_bag = null;
        port.submitChapterList(_submitChapterList_authTicket, _submitChapterList_bag);


        }
        {
        System.out.println("Invoking wait...");
        java.lang.String _wait_authTicket = "";
        java.lang.String _wait_guid = "";
        port.wait(_wait_authTicket, _wait_guid);


        }
        {
        System.out.println("Invoking submitFileTag...");
        java.lang.String _submitFileTag_authTicket = "";
        java.lang.String _submitFileTag_bstrXMLProps = "";
        port.submitFileTag(_submitFileTag_authTicket, _submitFileTag_bstrXMLProps);


        }
        {
        System.out.println("Invoking submitBatchClip...");
        java.lang.String _submitBatchClip_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _submitBatchClip_bags = null;
        port.submitBatchClip(_submitBatchClip_authTicket, _submitBatchClip_bags);


        }
        {
        System.out.println("Invoking getNumberOfTasksInProgress...");
        java.lang.String _getNumberOfTasksInProgress_authTicket = "";
        long _getNumberOfTasksInProgress__return = port.getNumberOfTasksInProgress(_getNumberOfTasksInProgress_authTicket);
        System.out.println("getNumberOfTasksInProgress.result=" + _getNumberOfTasksInProgress__return);


        }
        {
        System.out.println("Invoking setTimeConstraint...");
        java.lang.String _setTimeConstraint_authTicket = "";
        java.lang.String _setTimeConstraint_bstrStartXml = "";
        java.lang.String _setTimeConstraint_bstrEndXml = "";
        port.setTimeConstraint(_setTimeConstraint_authTicket, _setTimeConstraint_bstrStartXml, _setTimeConstraint_bstrEndXml);


        }
        {
        System.out.println("Invoking progressByID...");
        java.lang.String _progressByID_authTicket = "";
        java.lang.String _progressByID_guid = "";
        long _progressByID__return = port.progressByID(_progressByID_authTicket, _progressByID_guid);
        System.out.println("progressByID.result=" + _progressByID__return);


        }
        {
        System.out.println("Invoking getNumberOfTasksPending...");
        java.lang.String _getNumberOfTasksPending_authTicket = "";
        long _getNumberOfTasksPending__return = port.getNumberOfTasksPending(_getNumberOfTasksPending_authTicket);
        System.out.println("getNumberOfTasksPending.result=" + _getNumberOfTasksPending__return);


        }
        {
        System.out.println("Invoking getTaskByFullName...");
        java.lang.String _getTaskByFullName_authTicket = "";
        java.lang.String _getTaskByFullName_taskName = "";
        java.lang.String _getTaskByFullName_fullName = "";
        java.lang.Long _getTaskByFullName_indexVal = null;
        javax.xml.ws.Holder<java.lang.Long> _getTaskByFullName_index = new javax.xml.ws.Holder<java.lang.Long>(_getTaskByFullName_indexVal);
        javax.xml.ws.Holder<java.lang.String> _getTaskByFullName_getTaskByFullNameResult = new javax.xml.ws.Holder<java.lang.String>();
        port.getTaskByFullName(_getTaskByFullName_authTicket, _getTaskByFullName_taskName, _getTaskByFullName_fullName, _getTaskByFullName_index, _getTaskByFullName_getTaskByFullNameResult);

        System.out.println("getTaskByFullName._getTaskByFullName_index=" + _getTaskByFullName_index.value);
        System.out.println("getTaskByFullName._getTaskByFullName_getTaskByFullNameResult=" + _getTaskByFullName_getTaskByFullNameResult.value);

        }
        {
        System.out.println("Invoking submitClipAndSqueeze...");
        java.lang.String _submitClipAndSqueeze_authTicket = "";
        com.snapstream.types.PVSPropertyBag _submitClipAndSqueeze_bag = null;
        port.submitClipAndSqueeze(_submitClipAndSqueeze_authTicket, _submitClipAndSqueeze_bag);


        }
        {
        System.out.println("Invoking submitBatchClipAndSqueeze...");
        java.lang.String _submitBatchClipAndSqueeze_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _submitBatchClipAndSqueeze_bags = null;
        port.submitBatchClipAndSqueeze(_submitBatchClipAndSqueeze_authTicket, _submitBatchClipAndSqueeze_bags);


        }
        {
        System.out.println("Invoking submitRecompress...");
        java.lang.String _submitRecompress_authTicket = "";
        com.snapstream.types.PVSPropertyBag _submitRecompress_bag = null;
        port.submitRecompress(_submitRecompress_authTicket, _submitRecompress_bag);


        }
        {
        System.out.println("Invoking getTimeConstraint...");
        java.lang.String _getTimeConstraint_authTicket = "";
        com.snapstream.webservice.ArrayOfString _getTimeConstraint__return = port.getTimeConstraint(_getTimeConstraint_authTicket);
        System.out.println("getTimeConstraint.result=" + _getTimeConstraint__return);


        }
        {
        System.out.println("Invoking submitBatchRecompress...");
        java.lang.String _submitBatchRecompress_authTicket = "";
        com.snapstream.webservice.ArrayOfPVSPropertyBag _submitBatchRecompress_bags = null;
        port.submitBatchRecompress(_submitBatchRecompress_authTicket, _submitBatchRecompress_bags);


        }
        {
        System.out.println("Invoking submitTPSnip...");
        java.lang.String _submitTPSnip_authTicket = "";
        com.snapstream.types.PVSPropertyBag _submitTPSnip_bag = null;
        port.submitTPSnip(_submitTPSnip_authTicket, _submitTPSnip_bag);


        }
        {
        System.out.println("Invoking itemByID...");
        java.lang.String _itemByID_authTicket = "";
        java.lang.String _itemByID_guid = "";
        java.lang.String _itemByID__return = port.itemByID(_itemByID_authTicket, _itemByID_guid);
        System.out.println("itemByID.result=" + _itemByID__return);


        }
        {
        System.out.println("Invoking halt...");
        java.lang.String _halt_authTicket = "";
        java.lang.String _halt_guid = "";
        port.halt(_halt_authTicket, _halt_guid);


        }
        {
        System.out.println("Invoking getCount...");
        java.lang.String _getCount_authTicket = "";
        long _getCount__return = port.getCount(_getCount_authTicket);
        System.out.println("getCount.result=" + _getCount__return);


        }

        System.exit(0);
    }

}
