
/*
 * 
 */

package com.snapstream.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-05-05T12:56:11.645-06:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "BTVWebServiceManager", 
                  wsdlLocation = "file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/BTVWebServiceManager.asmx.xml",
                  targetNamespace = "http://www.snapstream.com/WebService") 
public class BTVWebServiceManager extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.snapstream.com/WebService", "BTVWebServiceManager");
    public final static QName BTVWebServiceManagerSoap12 = new QName("http://www.snapstream.com/WebService", "BTVWebServiceManagerSoap12");
    public final static QName BTVWebServiceManagerSoap = new QName("http://www.snapstream.com/WebService", "BTVWebServiceManagerSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/BTVWebServiceManager.asmx.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BTVWebServiceManager.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/BTVWebServiceManager.asmx.xml");
        }
        WSDL_LOCATION = url;
    }

    public BTVWebServiceManager(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BTVWebServiceManager(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BTVWebServiceManager() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns BTVWebServiceManagerSoap
     */
    @WebEndpoint(name = "BTVWebServiceManagerSoap12")
    public BTVWebServiceManagerSoap getBTVWebServiceManagerSoap12() {
        return super.getPort(BTVWebServiceManagerSoap12, BTVWebServiceManagerSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BTVWebServiceManagerSoap
     */
    @WebEndpoint(name = "BTVWebServiceManagerSoap12")
    public BTVWebServiceManagerSoap getBTVWebServiceManagerSoap12(WebServiceFeature... features) {
        return super.getPort(BTVWebServiceManagerSoap12, BTVWebServiceManagerSoap.class, features);
    }
    /**
     * 
     * @return
     *     returns BTVWebServiceManagerSoap
     */
    @WebEndpoint(name = "BTVWebServiceManagerSoap")
    public BTVWebServiceManagerSoap getBTVWebServiceManagerSoap() {
        return super.getPort(BTVWebServiceManagerSoap, BTVWebServiceManagerSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BTVWebServiceManagerSoap
     */
    @WebEndpoint(name = "BTVWebServiceManagerSoap")
    public BTVWebServiceManagerSoap getBTVWebServiceManagerSoap(WebServiceFeature... features) {
        return super.getPort(BTVWebServiceManagerSoap, BTVWebServiceManagerSoap.class, features);
    }

}
