
/*
 * 
 */

package com.snapstream.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-05-05T12:56:21.810-06:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "InternalBTVScheduler", 
                  wsdlLocation = "file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/InternalBTVScheduler.asmx.xml",
                  targetNamespace = "http://www.snapstream.com/WebService") 
public class InternalBTVScheduler extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.snapstream.com/WebService", "InternalBTVScheduler");
    public final static QName InternalBTVSchedulerSoap = new QName("http://www.snapstream.com/WebService", "InternalBTVSchedulerSoap");
    public final static QName InternalBTVSchedulerSoap12 = new QName("http://www.snapstream.com/WebService", "InternalBTVSchedulerSoap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/InternalBTVScheduler.asmx.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(InternalBTVScheduler.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/kleider/lm/repositories/atgas-sync-media/beyondTV/wsdl/InternalBTVScheduler.asmx.xml");
        }
        WSDL_LOCATION = url;
    }

    public InternalBTVScheduler(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InternalBTVScheduler(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InternalBTVScheduler() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns InternalBTVSchedulerSoap
     */
    @WebEndpoint(name = "InternalBTVSchedulerSoap")
    public InternalBTVSchedulerSoap getInternalBTVSchedulerSoap() {
        return super.getPort(InternalBTVSchedulerSoap, InternalBTVSchedulerSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InternalBTVSchedulerSoap
     */
    @WebEndpoint(name = "InternalBTVSchedulerSoap")
    public InternalBTVSchedulerSoap getInternalBTVSchedulerSoap(WebServiceFeature... features) {
        return super.getPort(InternalBTVSchedulerSoap, InternalBTVSchedulerSoap.class, features);
    }
    /**
     * 
     * @return
     *     returns InternalBTVSchedulerSoap
     */
    @WebEndpoint(name = "InternalBTVSchedulerSoap12")
    public InternalBTVSchedulerSoap getInternalBTVSchedulerSoap12() {
        return super.getPort(InternalBTVSchedulerSoap12, InternalBTVSchedulerSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InternalBTVSchedulerSoap
     */
    @WebEndpoint(name = "InternalBTVSchedulerSoap12")
    public InternalBTVSchedulerSoap getInternalBTVSchedulerSoap12(WebServiceFeature... features) {
        return super.getPort(InternalBTVSchedulerSoap12, InternalBTVSchedulerSoap.class, features);
    }

}
