
package org.atgas.sync.media.beyondTV.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.atgas.sync.media.beyondTV.webservices.types.PVSPropertyBag;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.3-b01-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BTVExpirationSoap", targetNamespace = "http://www.snapstream.com/WebService")
@XmlSeeAlso({
    org.atgas.sync.media.beyondTV.webservices.btvexpiration.ObjectFactory.class,
    org.atgas.sync.media.beyondTV.webservices.types.ObjectFactory.class
})
public interface BTVExpirationSoap {


    /**
     * 
     * @param guid
     * @param authTicket
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetShowLimitsByGuid", action = "http://www.snapstream.com/WebService/GetShowLimitsByGuid")
    @WebResult(name = "GetShowLimitsByGuidResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetShowLimitsByGuid", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvexpiration.GetShowLimitsByGuid")
    @ResponseWrapper(localName = "GetShowLimitsByGuidResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvexpiration.GetShowLimitsByGuidResponse")
    public int getShowLimitsByGuid(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        String guid);

    /**
     * 
     * @param guid
     * @param authTicket
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetMaxDaysByGuid", action = "http://www.snapstream.com/WebService/GetMaxDaysByGuid")
    @WebResult(name = "GetMaxDaysByGuidResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetMaxDaysByGuid", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvexpiration.GetMaxDaysByGuid")
    @ResponseWrapper(localName = "GetMaxDaysByGuidResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvexpiration.GetMaxDaysByGuidResponse")
    public int getMaxDaysByGuid(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        String guid);

    /**
     * 
     * @param limit
     * @param guid
     * @param authTicket
     */
    @WebMethod(operationName = "SetShowLimitsByGuid", action = "http://www.snapstream.com/WebService/SetShowLimitsByGuid")
    @RequestWrapper(localName = "SetShowLimitsByGuid", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvexpiration.SetShowLimitsByGuid")
    @ResponseWrapper(localName = "SetShowLimitsByGuidResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvexpiration.SetShowLimitsByGuidResponse")
    public void setShowLimitsByGuid(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        String guid,
        @WebParam(name = "limit", targetNamespace = "http://www.snapstream.com/WebService")
        int limit);

    /**
     * 
     * @param guid
     * @param authTicket
     * @param days
     */
    @WebMethod(operationName = "SetDaysLimitsByGuid", action = "http://www.snapstream.com/WebService/SetDaysLimitsByGuid")
    @RequestWrapper(localName = "SetDaysLimitsByGuid", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvexpiration.SetDaysLimitsByGuid")
    @ResponseWrapper(localName = "SetDaysLimitsByGuidResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvexpiration.SetDaysLimitsByGuidResponse")
    public void setDaysLimitsByGuid(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        String guid,
        @WebParam(name = "days", targetNamespace = "http://www.snapstream.com/WebService")
        int days);

    /**
     * 
     * @param authTicket
     * @param bag
     */
    @WebMethod(operationName = "SetDriveLimits", action = "http://www.snapstream.com/WebService/SetDriveLimits")
    @RequestWrapper(localName = "SetDriveLimits", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvexpiration.SetDriveLimits")
    @ResponseWrapper(localName = "SetDriveLimitsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvexpiration.SetDriveLimitsResponse")
    public void setDriveLimits(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "bag", targetNamespace = "http://www.snapstream.com/WebService")
        PVSPropertyBag bag);

    /**
     * 
     * @param authTicket
     * @param name
     * @return
     *     returns org.atgas.sync.media.beyondTV.webservices.types.PVSPropertyBag
     */
    @WebMethod(operationName = "GetDriveLimitsByName", action = "http://www.snapstream.com/WebService/GetDriveLimitsByName")
    @WebResult(name = "GetDriveLimitsByNameResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetDriveLimitsByName", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvexpiration.GetDriveLimitsByName")
    @ResponseWrapper(localName = "GetDriveLimitsByNameResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvexpiration.GetDriveLimitsByNameResponse")
    public PVSPropertyBag getDriveLimitsByName(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "name", targetNamespace = "http://www.snapstream.com/WebService")
        String name);

}
