
package org.atgas.sync.media.beyondTV.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.3-b01-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BTVGuideData", targetNamespace = "http://www.snapstream.com/WebService", wsdlLocation = "http://localhost:8129/wsdl/BTVGuideData.asmx")
public class BTVGuideData
    extends Service
{

    private final static URL BTVGUIDEDATA_WSDL_LOCATION;
    private final static WebServiceException BTVGUIDEDATA_EXCEPTION;
    private final static QName BTVGUIDEDATA_QNAME = new QName("http://www.snapstream.com/WebService", "BTVGuideData");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8129/wsdl/BTVGuideData.asmx");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BTVGUIDEDATA_WSDL_LOCATION = url;
        BTVGUIDEDATA_EXCEPTION = e;
    }

    public BTVGuideData() {
        super(__getWsdlLocation(), BTVGUIDEDATA_QNAME);
    }

    public BTVGuideData(WebServiceFeature... features) {
        super(__getWsdlLocation(), BTVGUIDEDATA_QNAME, features);
    }

    public BTVGuideData(URL wsdlLocation) {
        super(wsdlLocation, BTVGUIDEDATA_QNAME);
    }

    public BTVGuideData(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BTVGUIDEDATA_QNAME, features);
    }

    public BTVGuideData(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BTVGuideData(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BTVGuideDataSoap
     */
    @WebEndpoint(name = "BTVGuideDataSoap")
    public BTVGuideDataSoap getBTVGuideDataSoap() {
        return super.getPort(new QName("http://www.snapstream.com/WebService", "BTVGuideDataSoap"), BTVGuideDataSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BTVGuideDataSoap
     */
    @WebEndpoint(name = "BTVGuideDataSoap")
    public BTVGuideDataSoap getBTVGuideDataSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.snapstream.com/WebService", "BTVGuideDataSoap"), BTVGuideDataSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BTVGUIDEDATA_EXCEPTION!= null) {
            throw BTVGUIDEDATA_EXCEPTION;
        }
        return BTVGUIDEDATA_WSDL_LOCATION;
    }

}
