
package org.atgas.sync.media.beyondtv.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.ArrayOfAnyType;
import org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.ArrayOfPVSPropertyBag;
import org.atgas.sync.media.beyondtv.webservices.types.PVSPropertyBag;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.3-b01-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BTVLiveTVManagerSoap", targetNamespace = "http://www.snapstream.com/WebService")
@XmlSeeAlso({
    org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.ObjectFactory.class,
    org.atgas.sync.media.beyondtv.webservices.types.ObjectFactory.class
})
public interface BTVLiveTVManagerSoap {


    /**
     * 
     * @param authTicket
     * @param uniqueChannelId
     * @param sessionType
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "NewSession", action = "http://www.snapstream.com/WebService/NewSession")
    @WebResult(name = "NewSessionResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "NewSession", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.NewSession")
    @ResponseWrapper(localName = "NewSessionResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.NewSessionResponse")
    public String newSession(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "sessionType", targetNamespace = "http://www.snapstream.com/WebService")
        String sessionType,
        @WebParam(name = "uniqueChannelId", targetNamespace = "http://www.snapstream.com/WebService")
        String uniqueChannelId);

    /**
     * 
     * @param authTicket
     * @param uniqueChannelID
     * @param sessionType
     * @return
     *     returns org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.ArrayOfAnyType
     */
    @WebMethod(operationName = "NewSessionWithErrorCondition", action = "http://www.snapstream.com/WebService/NewSessionWithErrorCondition")
    @WebResult(name = "NewSessionWithErrorConditionResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "NewSessionWithErrorCondition", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.NewSessionWithErrorCondition")
    @ResponseWrapper(localName = "NewSessionWithErrorConditionResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.NewSessionWithErrorConditionResponse")
    public ArrayOfAnyType newSessionWithErrorCondition(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "sessionType", targetNamespace = "http://www.snapstream.com/WebService")
        String sessionType,
        @WebParam(name = "uniqueChannelID", targetNamespace = "http://www.snapstream.com/WebService")
        String uniqueChannelID);

    /**
     * 
     * @param authTicket
     * @param sessionType
     * @param guidSource
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "NewSessionOnSource", action = "http://www.snapstream.com/WebService/NewSessionOnSource")
    @WebResult(name = "NewSessionOnSourceResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "NewSessionOnSource", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.NewSessionOnSource")
    @ResponseWrapper(localName = "NewSessionOnSourceResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.NewSessionOnSourceResponse")
    public String newSessionOnSource(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "sessionType", targetNamespace = "http://www.snapstream.com/WebService")
        String sessionType,
        @WebParam(name = "guidSource", targetNamespace = "http://www.snapstream.com/WebService")
        String guidSource);

    /**
     * 
     * @param authTicket
     * @param existingGuid
     * @param sessionType
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ExistingSession", action = "http://www.snapstream.com/WebService/ExistingSession")
    @WebResult(name = "ExistingSessionResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "ExistingSession", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.ExistingSession")
    @ResponseWrapper(localName = "ExistingSessionResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.ExistingSessionResponse")
    public String existingSession(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "sessionType", targetNamespace = "http://www.snapstream.com/WebService")
        String sessionType,
        @WebParam(name = "existingGuid", targetNamespace = "http://www.snapstream.com/WebService")
        String existingGuid);

    /**
     * 
     * @param guid
     * @param authTicket
     */
    @WebMethod(operationName = "KeepAlive", action = "http://www.snapstream.com/WebService/KeepAlive")
    @RequestWrapper(localName = "KeepAlive", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.KeepAlive")
    @ResponseWrapper(localName = "KeepAliveResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.KeepAliveResponse")
    public void keepAlive(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        String guid);

    /**
     * 
     * @param guid
     * @param authTicket
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetChannel", action = "http://www.snapstream.com/WebService/GetChannel")
    @WebResult(name = "GetChannelResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetChannel", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.GetChannel")
    @ResponseWrapper(localName = "GetChannelResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.GetChannelResponse")
    public String getChannel(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        String guid);

    /**
     * 
     * @param guid
     * @param authTicket
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "IsRecording", action = "http://www.snapstream.com/WebService/IsRecording")
    @WebResult(name = "IsRecordingResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "IsRecording", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.IsRecording")
    @ResponseWrapper(localName = "IsRecordingResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.IsRecordingResponse")
    public boolean isRecording(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        String guid);

    /**
     * 
     * @param guid
     * @param authTicket
     * @param channel
     */
    @WebMethod(operationName = "SetChannel", action = "http://www.snapstream.com/WebService/SetChannel")
    @RequestWrapper(localName = "SetChannel", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.SetChannel")
    @ResponseWrapper(localName = "SetChannelResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.SetChannelResponse")
    public void setChannel(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        String guid,
        @WebParam(name = "channel", targetNamespace = "http://www.snapstream.com/WebService")
        String channel);

    /**
     * 
     * @param guid
     * @param authTicket
     * @param channel
     * @return
     *     returns int
     */
    @WebMethod(operationName = "SetChannelWithErrorCondition", action = "http://www.snapstream.com/WebService/SetChannelWithErrorCondition")
    @WebResult(name = "SetChannelWithErrorConditionResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "SetChannelWithErrorCondition", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.SetChannelWithErrorCondition")
    @ResponseWrapper(localName = "SetChannelWithErrorConditionResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.SetChannelWithErrorConditionResponse")
    public int setChannelWithErrorCondition(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        String guid,
        @WebParam(name = "channel", targetNamespace = "http://www.snapstream.com/WebService")
        String channel);

    /**
     * 
     * @param guid
     * @param authTicket
     * @param guidSource
     * @param channel
     */
    @WebMethod(operationName = "ForceChannel", action = "http://www.snapstream.com/WebService/ForceChannel")
    @RequestWrapper(localName = "ForceChannel", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.ForceChannel")
    @ResponseWrapper(localName = "ForceChannelResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.ForceChannelResponse")
    public void forceChannel(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        String guid,
        @WebParam(name = "guidSource", targetNamespace = "http://www.snapstream.com/WebService")
        String guidSource,
        @WebParam(name = "channel", targetNamespace = "http://www.snapstream.com/WebService")
        String channel);

    /**
     * 
     * @param guid
     * @param authTicket
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetSignalStrength", action = "http://www.snapstream.com/WebService/GetSignalStrength")
    @WebResult(name = "GetSignalStrengthResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetSignalStrength", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.GetSignalStrength")
    @ResponseWrapper(localName = "GetSignalStrengthResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.GetSignalStrengthResponse")
    public int getSignalStrength(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        String guid);

    /**
     * 
     * @param guid
     * @param authTicket
     */
    @WebMethod(operationName = "EndSession", action = "http://www.snapstream.com/WebService/EndSession")
    @RequestWrapper(localName = "EndSession", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.EndSession")
    @ResponseWrapper(localName = "EndSessionResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.EndSessionResponse")
    public void endSession(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        String guid);

    /**
     * 
     * @param guid
     * @param authTicket
     * @return
     *     returns org.atgas.sync.media.beyondtv.webservices.types.PVSPropertyBag
     */
    @WebMethod(operationName = "GetRecording", action = "http://www.snapstream.com/WebService/GetRecording")
    @WebResult(name = "GetRecordingResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetRecording", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.GetRecording")
    @ResponseWrapper(localName = "GetRecordingResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.GetRecordingResponse")
    public PVSPropertyBag getRecording(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        String guid);

    /**
     * 
     * @param guid
     * @param authTicket
     * @return
     *     returns org.atgas.sync.media.beyondtv.webservices.types.PVSPropertyBag
     */
    @WebMethod(operationName = "GetSessionProps", action = "http://www.snapstream.com/WebService/GetSessionProps")
    @WebResult(name = "GetSessionPropsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetSessionProps", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.GetSessionProps")
    @ResponseWrapper(localName = "GetSessionPropsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.GetSessionPropsResponse")
    public PVSPropertyBag getSessionProps(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        String guid);

    /**
     * 
     * @param authTicket
     * @return
     *     returns org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetSessions", action = "http://www.snapstream.com/WebService/GetSessions")
    @WebResult(name = "GetSessionsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetSessions", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.GetSessions")
    @ResponseWrapper(localName = "GetSessionsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.GetSessionsResponse")
    public ArrayOfPVSPropertyBag getSessions(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param guid
     * @param authTicket
     * @return
     *     returns org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetImminentRecordings", action = "http://www.snapstream.com/WebService/GetImminentRecordings")
    @WebResult(name = "GetImminentRecordingsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetImminentRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.GetImminentRecordings")
    @ResponseWrapper(localName = "GetImminentRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.GetImminentRecordingsResponse")
    public ArrayOfPVSPropertyBag getImminentRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        String guid);

    /**
     * 
     * @param authTicket
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "NewSourceSession", action = "http://www.snapstream.com/WebService/NewSourceSession")
    @WebResult(name = "NewSourceSessionResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "NewSourceSession", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.NewSourceSession")
    @ResponseWrapper(localName = "NewSourceSessionResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.NewSourceSessionResponse")
    public String newSourceSession(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     * @param channelID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "NewSourceSessionOnChannel", action = "http://www.snapstream.com/WebService/NewSourceSessionOnChannel")
    @WebResult(name = "NewSourceSessionOnChannelResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "NewSourceSessionOnChannel", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.NewSourceSessionOnChannel")
    @ResponseWrapper(localName = "NewSourceSessionOnChannelResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.NewSourceSessionOnChannelResponse")
    public String newSourceSessionOnChannel(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "channelID", targetNamespace = "http://www.snapstream.com/WebService")
        String channelID);

    /**
     * 
     * @param authTicket
     * @param sourceGuid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ExistingSourceSession", action = "http://www.snapstream.com/WebService/ExistingSourceSession")
    @WebResult(name = "ExistingSourceSessionResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "ExistingSourceSession", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.ExistingSourceSession")
    @ResponseWrapper(localName = "ExistingSourceSessionResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.ExistingSourceSessionResponse")
    public String existingSourceSession(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "sourceGuid", targetNamespace = "http://www.snapstream.com/WebService")
        String sourceGuid);

    /**
     * 
     * @param authTicket
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "NewWebSession", action = "http://www.snapstream.com/WebService/NewWebSession")
    @WebResult(name = "NewWebSessionResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "NewWebSession", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.NewWebSession")
    @ResponseWrapper(localName = "NewWebSessionResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.NewWebSessionResponse")
    public String newWebSession(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     * @param sourceGuid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ExistingWebSession", action = "http://www.snapstream.com/WebService/ExistingWebSession")
    @WebResult(name = "ExistingWebSessionResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "ExistingWebSession", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.ExistingWebSession")
    @ResponseWrapper(localName = "ExistingWebSessionResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvlivetvmanager.ExistingWebSessionResponse")
    public String existingWebSession(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "sourceGuid", targetNamespace = "http://www.snapstream.com/WebService")
        String sourceGuid);

}
