
package org.atgas.sync.media.beyondtv.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.3-b01-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BTVLibrary", targetNamespace = "http://www.snapstream.com/WebService", wsdlLocation = "http://localhost:8129/wsdl/BTVLibrary.asmx")
public class BTVLibrary
    extends Service
{

    private final static URL BTVLIBRARY_WSDL_LOCATION;
    private final static WebServiceException BTVLIBRARY_EXCEPTION;
    private final static QName BTVLIBRARY_QNAME = new QName("http://www.snapstream.com/WebService", "BTVLibrary");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8129/wsdl/BTVLibrary.asmx");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BTVLIBRARY_WSDL_LOCATION = url;
        BTVLIBRARY_EXCEPTION = e;
    }

    public BTVLibrary() {
        super(__getWsdlLocation(), BTVLIBRARY_QNAME);
    }

    public BTVLibrary(WebServiceFeature... features) {
        super(__getWsdlLocation(), BTVLIBRARY_QNAME, features);
    }

    public BTVLibrary(URL wsdlLocation) {
        super(wsdlLocation, BTVLIBRARY_QNAME);
    }

    public BTVLibrary(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BTVLIBRARY_QNAME, features);
    }

    public BTVLibrary(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BTVLibrary(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BTVLibrarySoap
     */
    @WebEndpoint(name = "BTVLibrarySoap")
    public BTVLibrarySoap getBTVLibrarySoap() {
        return super.getPort(new QName("http://www.snapstream.com/WebService", "BTVLibrarySoap"), BTVLibrarySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BTVLibrarySoap
     */
    @WebEndpoint(name = "BTVLibrarySoap")
    public BTVLibrarySoap getBTVLibrarySoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.snapstream.com/WebService", "BTVLibrarySoap"), BTVLibrarySoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BTVLIBRARY_EXCEPTION!= null) {
            throw BTVLIBRARY_EXCEPTION;
        }
        return BTVLIBRARY_WSDL_LOCATION;
    }

}
