
package org.atgas.sync.media.beyondTV.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.3-b01-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BTVLicenseManager", targetNamespace = "http://www.snapstream.com/WebService", wsdlLocation = "http://localhost:8129/wsdl/BTVLicenseManager.asmx")
public class BTVLicenseManager
    extends Service
{

    private final static URL BTVLICENSEMANAGER_WSDL_LOCATION;
    private final static WebServiceException BTVLICENSEMANAGER_EXCEPTION;
    private final static QName BTVLICENSEMANAGER_QNAME = new QName("http://www.snapstream.com/WebService", "BTVLicenseManager");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8129/wsdl/BTVLicenseManager.asmx");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BTVLICENSEMANAGER_WSDL_LOCATION = url;
        BTVLICENSEMANAGER_EXCEPTION = e;
    }

    public BTVLicenseManager() {
        super(__getWsdlLocation(), BTVLICENSEMANAGER_QNAME);
    }

    public BTVLicenseManager(WebServiceFeature... features) {
        super(__getWsdlLocation(), BTVLICENSEMANAGER_QNAME, features);
    }

    public BTVLicenseManager(URL wsdlLocation) {
        super(wsdlLocation, BTVLICENSEMANAGER_QNAME);
    }

    public BTVLicenseManager(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BTVLICENSEMANAGER_QNAME, features);
    }

    public BTVLicenseManager(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BTVLicenseManager(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BTVLicenseManagerSoap
     */
    @WebEndpoint(name = "BTVLicenseManagerSoap")
    public BTVLicenseManagerSoap getBTVLicenseManagerSoap() {
        return super.getPort(new QName("http://www.snapstream.com/WebService", "BTVLicenseManagerSoap"), BTVLicenseManagerSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BTVLicenseManagerSoap
     */
    @WebEndpoint(name = "BTVLicenseManagerSoap")
    public BTVLicenseManagerSoap getBTVLicenseManagerSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.snapstream.com/WebService", "BTVLicenseManagerSoap"), BTVLicenseManagerSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BTVLICENSEMANAGER_EXCEPTION!= null) {
            throw BTVLICENSEMANAGER_EXCEPTION;
        }
        return BTVLICENSEMANAGER_WSDL_LOCATION;
    }

}
