
package org.atgas.sync.media.beyondTV.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.atgas.sync.media.beyondTV.webservices.btvlibrary.ArrayOfPVSPropertyBag;
import org.atgas.sync.media.beyondTV.webservices.btvlibrary.LibraryHideOption;
import org.atgas.sync.media.beyondTV.webservices.btvlibrary.LibrarySort;
import org.atgas.sync.media.beyondTV.webservices.btvlibrary.LibrarySortOrder;
import org.atgas.sync.media.beyondTV.webservices.types.PVSPropertyBag;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.3-b01-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BTVLibrarySoap", targetNamespace = "http://www.snapstream.com/WebService")
@XmlSeeAlso({
    org.atgas.sync.media.beyondTV.webservices.btvlibrary.ObjectFactory.class,
    org.atgas.sync.media.beyondTV.webservices.types.ObjectFactory.class
})
public interface BTVLibrarySoap {


    /**
     * 
     * @param authTicket
     * @param folderName
     * @return
     *     returns org.atgas.sync.media.beyondTV.webservices.btvlibrary.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetFolders", action = "http://www.snapstream.com/WebService/GetFolders")
    @WebResult(name = "GetFoldersResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetFolders", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetFolders")
    @ResponseWrapper(localName = "GetFoldersResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetFoldersResponse")
    public ArrayOfPVSPropertyBag getFolders(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "folderName", targetNamespace = "http://www.snapstream.com/WebService")
        String folderName);

    /**
     * 
     * @param authTicket
     * @param count
     * @param totalCount
     * @param start
     * @param getFoldersByRangeResult
     * @param folderName
     */
    @WebMethod(operationName = "GetFoldersByRange", action = "http://www.snapstream.com/WebService/GetFoldersByRange")
    @RequestWrapper(localName = "GetFoldersByRange", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetFoldersByRange")
    @ResponseWrapper(localName = "GetFoldersByRangeResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetFoldersByRangeResponse")
    public void getFoldersByRange(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "folderName", targetNamespace = "http://www.snapstream.com/WebService")
        String folderName,
        @WebParam(name = "start", targetNamespace = "http://www.snapstream.com/WebService")
        int start,
        @WebParam(name = "count", targetNamespace = "http://www.snapstream.com/WebService")
        int count,
        @WebParam(name = "GetFoldersByRangeResult", targetNamespace = "http://www.snapstream.com/WebService", mode = WebParam.Mode.OUT)
        Holder<ArrayOfPVSPropertyBag> getFoldersByRangeResult,
        @WebParam(name = "totalCount", targetNamespace = "http://www.snapstream.com/WebService", mode = WebParam.Mode.OUT)
        Holder<Integer> totalCount);

    /**
     * 
     * @param authTicket
     * @param folderName
     * @return
     *     returns org.atgas.sync.media.beyondTV.webservices.types.PVSPropertyBag
     */
    @WebMethod(operationName = "GetFolder", action = "http://www.snapstream.com/WebService/GetFolder")
    @WebResult(name = "GetFolderResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetFolder", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetFolder")
    @ResponseWrapper(localName = "GetFolderResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetFolderResponse")
    public PVSPropertyBag getFolder(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "folderName", targetNamespace = "http://www.snapstream.com/WebService")
        String folderName);

    /**
     * 
     * @param authTicket
     * @return
     *     returns long
     */
    @WebMethod(operationName = "GetLastChange", action = "http://www.snapstream.com/WebService/GetLastChange")
    @WebResult(name = "GetLastChangeResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetLastChange", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetLastChange")
    @ResponseWrapper(localName = "GetLastChangeResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetLastChangeResponse")
    public long getLastChange(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     * @param sFolder
     */
    @WebMethod(operationName = "AddFolder", action = "http://www.snapstream.com/WebService/AddFolder")
    @RequestWrapper(localName = "AddFolder", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.AddFolder")
    @ResponseWrapper(localName = "AddFolderResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.AddFolderResponse")
    public void addFolder(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "sFolder", targetNamespace = "http://www.snapstream.com/WebService")
        String sFolder);

    /**
     * 
     * @param authTicket
     * @param bRecurse
     * @param sFolder
     */
    @WebMethod(operationName = "AddFolder2", action = "http://www.snapstream.com/WebService/AddFolder2")
    @RequestWrapper(localName = "AddFolder2", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.AddFolder2")
    @ResponseWrapper(localName = "AddFolder2Response", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.AddFolder2Response")
    public void addFolder2(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "sFolder", targetNamespace = "http://www.snapstream.com/WebService")
        String sFolder,
        @WebParam(name = "bRecurse", targetNamespace = "http://www.snapstream.com/WebService")
        boolean bRecurse);

    /**
     * 
     * @param authTicket
     * @param bRecurse
     * @param bManaged
     * @param sFolder
     */
    @WebMethod(operationName = "AddFolder3", action = "http://www.snapstream.com/WebService/AddFolder3")
    @RequestWrapper(localName = "AddFolder3", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.AddFolder3")
    @ResponseWrapper(localName = "AddFolder3Response", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.AddFolder3Response")
    public void addFolder3(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "sFolder", targetNamespace = "http://www.snapstream.com/WebService")
        String sFolder,
        @WebParam(name = "bRecurse", targetNamespace = "http://www.snapstream.com/WebService")
        boolean bRecurse,
        @WebParam(name = "bManaged", targetNamespace = "http://www.snapstream.com/WebService")
        boolean bManaged);

    /**
     * 
     * @param authTicket
     * @param sFolder
     */
    @WebMethod(operationName = "RemoveFolder", action = "http://www.snapstream.com/WebService/RemoveFolder")
    @RequestWrapper(localName = "RemoveFolder", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.RemoveFolder")
    @ResponseWrapper(localName = "RemoveFolderResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.RemoveFolderResponse")
    public void removeFolder(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "sFolder", targetNamespace = "http://www.snapstream.com/WebService")
        String sFolder);

    /**
     * 
     * @param authTicket
     * @param bag
     * @param fullName
     */
    @WebMethod(operationName = "EditMedia", action = "http://www.snapstream.com/WebService/EditMedia")
    @RequestWrapper(localName = "EditMedia", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.EditMedia")
    @ResponseWrapper(localName = "EditMediaResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.EditMediaResponse")
    public void editMedia(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "fullName", targetNamespace = "http://www.snapstream.com/WebService")
        String fullName,
        @WebParam(name = "bag", targetNamespace = "http://www.snapstream.com/WebService")
        PVSPropertyBag bag);

    /**
     * 
     * @param authTicket
     * @param value
     * @param property
     * @param fullName
     */
    @WebMethod(operationName = "SetUserSpecificProperty", action = "http://www.snapstream.com/WebService/SetUserSpecificProperty")
    @RequestWrapper(localName = "SetUserSpecificProperty", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.SetUserSpecificProperty")
    @ResponseWrapper(localName = "SetUserSpecificPropertyResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.SetUserSpecificPropertyResponse")
    public void setUserSpecificProperty(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "fullName", targetNamespace = "http://www.snapstream.com/WebService")
        String fullName,
        @WebParam(name = "property", targetNamespace = "http://www.snapstream.com/WebService")
        String property,
        @WebParam(name = "value", targetNamespace = "http://www.snapstream.com/WebService")
        String value);

    /**
     * 
     * @param authTicket
     * @param fullName
     */
    @WebMethod(operationName = "DeleteMedia", action = "http://www.snapstream.com/WebService/DeleteMedia")
    @RequestWrapper(localName = "DeleteMedia", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.DeleteMedia")
    @ResponseWrapper(localName = "DeleteMediaResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.DeleteMediaResponse")
    public void deleteMedia(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "fullName", targetNamespace = "http://www.snapstream.com/WebService")
        String fullName);

    /**
     * 
     * @param authTicket
     * @param sort
     * @param order
     * @param hide
     * @return
     *     returns org.atgas.sync.media.beyondTV.webservices.btvlibrary.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetAllClipsWithFilter", action = "http://www.snapstream.com/WebService/GetAllClipsWithFilter")
    @WebResult(name = "GetAllClipsWithFilterResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetAllClipsWithFilter", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetAllClipsWithFilter")
    @ResponseWrapper(localName = "GetAllClipsWithFilterResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetAllClipsWithFilterResponse")
    public ArrayOfPVSPropertyBag getAllClipsWithFilter(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "hide", targetNamespace = "http://www.snapstream.com/WebService")
        LibraryHideOption hide,
        @WebParam(name = "sort", targetNamespace = "http://www.snapstream.com/WebService")
        LibrarySort sort,
        @WebParam(name = "order", targetNamespace = "http://www.snapstream.com/WebService")
        LibrarySortOrder order);

    /**
     * 
     * @param authTicket
     * @param sort
     * @param count
     * @param order
     * @param hide
     * @param totalCount
     * @param start
     * @param getMyClipsResult
     */
    @WebMethod(operationName = "GetMyClips", action = "http://www.snapstream.com/WebService/GetMyClips")
    @RequestWrapper(localName = "GetMyClips", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetMyClips")
    @ResponseWrapper(localName = "GetMyClipsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetMyClipsResponse")
    public void getMyClips(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "hide", targetNamespace = "http://www.snapstream.com/WebService")
        LibraryHideOption hide,
        @WebParam(name = "sort", targetNamespace = "http://www.snapstream.com/WebService")
        LibrarySort sort,
        @WebParam(name = "order", targetNamespace = "http://www.snapstream.com/WebService")
        LibrarySortOrder order,
        @WebParam(name = "start", targetNamespace = "http://www.snapstream.com/WebService")
        int start,
        @WebParam(name = "count", targetNamespace = "http://www.snapstream.com/WebService")
        int count,
        @WebParam(name = "GetMyClipsResult", targetNamespace = "http://www.snapstream.com/WebService", mode = WebParam.Mode.OUT)
        Holder<ArrayOfPVSPropertyBag> getMyClipsResult,
        @WebParam(name = "totalCount", targetNamespace = "http://www.snapstream.com/WebService", mode = WebParam.Mode.OUT)
        Holder<Integer> totalCount);

    /**
     * 
     * @param authTicket
     * @param sort
     * @param count
     * @param order
     * @param hide
     * @param totalCount
     * @param start
     * @param getClipsResult
     */
    @WebMethod(operationName = "GetClips", action = "http://www.snapstream.com/WebService/GetClips")
    @RequestWrapper(localName = "GetClips", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetClips")
    @ResponseWrapper(localName = "GetClipsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetClipsResponse")
    public void getClips(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "hide", targetNamespace = "http://www.snapstream.com/WebService")
        LibraryHideOption hide,
        @WebParam(name = "sort", targetNamespace = "http://www.snapstream.com/WebService")
        LibrarySort sort,
        @WebParam(name = "order", targetNamespace = "http://www.snapstream.com/WebService")
        LibrarySortOrder order,
        @WebParam(name = "start", targetNamespace = "http://www.snapstream.com/WebService")
        int start,
        @WebParam(name = "count", targetNamespace = "http://www.snapstream.com/WebService")
        int count,
        @WebParam(name = "GetClipsResult", targetNamespace = "http://www.snapstream.com/WebService", mode = WebParam.Mode.OUT)
        Holder<ArrayOfPVSPropertyBag> getClipsResult,
        @WebParam(name = "totalCount", targetNamespace = "http://www.snapstream.com/WebService", mode = WebParam.Mode.OUT)
        Holder<Integer> totalCount);

    /**
     * 
     * @param authTicket
     * @param sort
     * @param order
     * @param hide
     * @return
     *     returns org.atgas.sync.media.beyondTV.webservices.btvlibrary.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetAllMediaWithFilter", action = "http://www.snapstream.com/WebService/GetAllMediaWithFilter")
    @WebResult(name = "GetAllMediaWithFilterResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetAllMediaWithFilter", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetAllMediaWithFilter")
    @ResponseWrapper(localName = "GetAllMediaWithFilterResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetAllMediaWithFilterResponse")
    public ArrayOfPVSPropertyBag getAllMediaWithFilter(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "hide", targetNamespace = "http://www.snapstream.com/WebService")
        LibraryHideOption hide,
        @WebParam(name = "sort", targetNamespace = "http://www.snapstream.com/WebService")
        LibrarySort sort,
        @WebParam(name = "order", targetNamespace = "http://www.snapstream.com/WebService")
        LibrarySortOrder order);

    /**
     * 
     * @param authTicket
     * @param sort
     * @param count
     * @param order
     * @param hide
     * @param totalCount
     * @param start
     * @param getMediaResult
     */
    @WebMethod(operationName = "GetMedia", action = "http://www.snapstream.com/WebService/GetMedia")
    @RequestWrapper(localName = "GetMedia", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetMedia")
    @ResponseWrapper(localName = "GetMediaResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetMediaResponse")
    public void getMedia(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "hide", targetNamespace = "http://www.snapstream.com/WebService")
        LibraryHideOption hide,
        @WebParam(name = "sort", targetNamespace = "http://www.snapstream.com/WebService")
        LibrarySort sort,
        @WebParam(name = "order", targetNamespace = "http://www.snapstream.com/WebService")
        LibrarySortOrder order,
        @WebParam(name = "start", targetNamespace = "http://www.snapstream.com/WebService")
        int start,
        @WebParam(name = "count", targetNamespace = "http://www.snapstream.com/WebService")
        int count,
        @WebParam(name = "GetMediaResult", targetNamespace = "http://www.snapstream.com/WebService", mode = WebParam.Mode.OUT)
        Holder<ArrayOfPVSPropertyBag> getMediaResult,
        @WebParam(name = "totalCount", targetNamespace = "http://www.snapstream.com/WebService", mode = WebParam.Mode.OUT)
        Holder<Integer> totalCount);

    /**
     * 
     * @param authTicket
     * @return
     *     returns org.atgas.sync.media.beyondTV.webservices.btvlibrary.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "FlatViewClipsByDate", action = "http://www.snapstream.com/WebService/FlatViewClipsByDate")
    @WebResult(name = "FlatViewClipsByDateResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "FlatViewClipsByDate", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.FlatViewClipsByDate")
    @ResponseWrapper(localName = "FlatViewClipsByDateResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.FlatViewClipsByDateResponse")
    public ArrayOfPVSPropertyBag flatViewClipsByDate(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     * @return
     *     returns org.atgas.sync.media.beyondTV.webservices.btvlibrary.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "FlatViewByDate", action = "http://www.snapstream.com/WebService/FlatViewByDate")
    @WebResult(name = "FlatViewByDateResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "FlatViewByDate", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.FlatViewByDate")
    @ResponseWrapper(localName = "FlatViewByDateResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.FlatViewByDateResponse")
    public ArrayOfPVSPropertyBag flatViewByDate(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     * @param index
     * @param count
     * @return
     *     returns org.atgas.sync.media.beyondTV.webservices.btvlibrary.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "FlatViewByDate2", action = "http://www.snapstream.com/WebService/FlatViewByDate2")
    @WebResult(name = "FlatViewByDate2Result", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "FlatViewByDate2", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.FlatViewByDate2")
    @ResponseWrapper(localName = "FlatViewByDate2Response", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.FlatViewByDate2Response")
    public ArrayOfPVSPropertyBag flatViewByDate2(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "index", targetNamespace = "http://www.snapstream.com/WebService")
        int index,
        @WebParam(name = "count", targetNamespace = "http://www.snapstream.com/WebService")
        int count);

    /**
     * 
     * @param authTicket
     * @return
     *     returns org.atgas.sync.media.beyondTV.webservices.btvlibrary.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "FlatViewByTitle", action = "http://www.snapstream.com/WebService/FlatViewByTitle")
    @WebResult(name = "FlatViewByTitleResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "FlatViewByTitle", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.FlatViewByTitle")
    @ResponseWrapper(localName = "FlatViewByTitleResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.FlatViewByTitleResponse")
    public ArrayOfPVSPropertyBag flatViewByTitle(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     * @return
     *     returns org.atgas.sync.media.beyondTV.webservices.btvlibrary.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetSeries", action = "http://www.snapstream.com/WebService/GetSeries")
    @WebResult(name = "GetSeriesResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetSeries", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetSeries")
    @ResponseWrapper(localName = "GetSeriesResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetSeriesResponse")
    public ArrayOfPVSPropertyBag getSeries(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     * @param getSeriesByRangeResult
     * @param count
     * @param totalCount
     * @param start
     */
    @WebMethod(operationName = "GetSeriesByRange", action = "http://www.snapstream.com/WebService/GetSeriesByRange")
    @RequestWrapper(localName = "GetSeriesByRange", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetSeriesByRange")
    @ResponseWrapper(localName = "GetSeriesByRangeResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetSeriesByRangeResponse")
    public void getSeriesByRange(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "start", targetNamespace = "http://www.snapstream.com/WebService")
        int start,
        @WebParam(name = "count", targetNamespace = "http://www.snapstream.com/WebService")
        int count,
        @WebParam(name = "GetSeriesByRangeResult", targetNamespace = "http://www.snapstream.com/WebService", mode = WebParam.Mode.OUT)
        Holder<ArrayOfPVSPropertyBag> getSeriesByRangeResult,
        @WebParam(name = "totalCount", targetNamespace = "http://www.snapstream.com/WebService", mode = WebParam.Mode.OUT)
        Holder<Integer> totalCount);

    /**
     * 
     * @param authTicket
     * @param series
     * @param sort
     * @param order
     * @param hide
     * @return
     *     returns org.atgas.sync.media.beyondTV.webservices.btvlibrary.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetItemsBySeriesWithFilter", action = "http://www.snapstream.com/WebService/GetItemsBySeriesWithFilter")
    @WebResult(name = "GetItemsBySeriesWithFilterResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetItemsBySeriesWithFilter", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetItemsBySeriesWithFilter")
    @ResponseWrapper(localName = "GetItemsBySeriesWithFilterResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetItemsBySeriesWithFilterResponse")
    public ArrayOfPVSPropertyBag getItemsBySeriesWithFilter(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "series", targetNamespace = "http://www.snapstream.com/WebService")
        String series,
        @WebParam(name = "hide", targetNamespace = "http://www.snapstream.com/WebService")
        LibraryHideOption hide,
        @WebParam(name = "sort", targetNamespace = "http://www.snapstream.com/WebService")
        LibrarySort sort,
        @WebParam(name = "order", targetNamespace = "http://www.snapstream.com/WebService")
        LibrarySortOrder order);

    /**
     * 
     * @param authTicket
     * @param series
     * @param sort
     * @param count
     * @param order
     * @param hide
     * @param totalCount
     * @param start
     * @param getSeriesWithFilterResult
     */
    @WebMethod(operationName = "GetSeriesWithFilter", action = "http://www.snapstream.com/WebService/GetSeriesWithFilter")
    @RequestWrapper(localName = "GetSeriesWithFilter", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetSeriesWithFilter")
    @ResponseWrapper(localName = "GetSeriesWithFilterResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetSeriesWithFilterResponse")
    public void getSeriesWithFilter(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "series", targetNamespace = "http://www.snapstream.com/WebService")
        String series,
        @WebParam(name = "hide", targetNamespace = "http://www.snapstream.com/WebService")
        LibraryHideOption hide,
        @WebParam(name = "sort", targetNamespace = "http://www.snapstream.com/WebService")
        LibrarySort sort,
        @WebParam(name = "order", targetNamespace = "http://www.snapstream.com/WebService")
        LibrarySortOrder order,
        @WebParam(name = "start", targetNamespace = "http://www.snapstream.com/WebService")
        int start,
        @WebParam(name = "count", targetNamespace = "http://www.snapstream.com/WebService")
        int count,
        @WebParam(name = "GetSeriesWithFilterResult", targetNamespace = "http://www.snapstream.com/WebService", mode = WebParam.Mode.OUT)
        Holder<ArrayOfPVSPropertyBag> getSeriesWithFilterResult,
        @WebParam(name = "totalCount", targetNamespace = "http://www.snapstream.com/WebService", mode = WebParam.Mode.OUT)
        Holder<Integer> totalCount);

    /**
     * 
     * @param folder
     * @param authTicket
     * @param sort
     * @param order
     * @param hide
     * @return
     *     returns org.atgas.sync.media.beyondTV.webservices.btvlibrary.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetItemsByFolderWithFilter", action = "http://www.snapstream.com/WebService/GetItemsByFolderWithFilter")
    @WebResult(name = "GetItemsByFolderWithFilterResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetItemsByFolderWithFilter", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetItemsByFolderWithFilter")
    @ResponseWrapper(localName = "GetItemsByFolderWithFilterResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetItemsByFolderWithFilterResponse")
    public ArrayOfPVSPropertyBag getItemsByFolderWithFilter(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "folder", targetNamespace = "http://www.snapstream.com/WebService")
        String folder,
        @WebParam(name = "hide", targetNamespace = "http://www.snapstream.com/WebService")
        LibraryHideOption hide,
        @WebParam(name = "sort", targetNamespace = "http://www.snapstream.com/WebService")
        LibrarySort sort,
        @WebParam(name = "order", targetNamespace = "http://www.snapstream.com/WebService")
        LibrarySortOrder order);

    /**
     * 
     * @param folder
     * @param authTicket
     * @param sort
     * @param count
     * @param order
     * @param hide
     * @param totalCount
     * @param start
     * @param getFolderWithFilterResult
     */
    @WebMethod(operationName = "GetFolderWithFilter", action = "http://www.snapstream.com/WebService/GetFolderWithFilter")
    @RequestWrapper(localName = "GetFolderWithFilter", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetFolderWithFilter")
    @ResponseWrapper(localName = "GetFolderWithFilterResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetFolderWithFilterResponse")
    public void getFolderWithFilter(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "folder", targetNamespace = "http://www.snapstream.com/WebService")
        String folder,
        @WebParam(name = "hide", targetNamespace = "http://www.snapstream.com/WebService")
        LibraryHideOption hide,
        @WebParam(name = "sort", targetNamespace = "http://www.snapstream.com/WebService")
        LibrarySort sort,
        @WebParam(name = "order", targetNamespace = "http://www.snapstream.com/WebService")
        LibrarySortOrder order,
        @WebParam(name = "start", targetNamespace = "http://www.snapstream.com/WebService")
        int start,
        @WebParam(name = "count", targetNamespace = "http://www.snapstream.com/WebService")
        int count,
        @WebParam(name = "GetFolderWithFilterResult", targetNamespace = "http://www.snapstream.com/WebService", mode = WebParam.Mode.OUT)
        Holder<ArrayOfPVSPropertyBag> getFolderWithFilterResult,
        @WebParam(name = "totalCount", targetNamespace = "http://www.snapstream.com/WebService", mode = WebParam.Mode.OUT)
        Holder<Integer> totalCount);

    /**
     * 
     * @param authTicket
     * @param series
     * @return
     *     returns org.atgas.sync.media.beyondTV.webservices.btvlibrary.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetItemsBySeries", action = "http://www.snapstream.com/WebService/GetItemsBySeries")
    @WebResult(name = "GetItemsBySeriesResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetItemsBySeries", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetItemsBySeries")
    @ResponseWrapper(localName = "GetItemsBySeriesResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetItemsBySeriesResponse")
    public ArrayOfPVSPropertyBag getItemsBySeries(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "series", targetNamespace = "http://www.snapstream.com/WebService")
        String series);

    /**
     * 
     * @param folder
     * @param authTicket
     * @return
     *     returns org.atgas.sync.media.beyondTV.webservices.btvlibrary.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetItemsByFolder", action = "http://www.snapstream.com/WebService/GetItemsByFolder")
    @WebResult(name = "GetItemsByFolderResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetItemsByFolder", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetItemsByFolder")
    @ResponseWrapper(localName = "GetItemsByFolderResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetItemsByFolderResponse")
    public ArrayOfPVSPropertyBag getItemsByFolder(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "folder", targetNamespace = "http://www.snapstream.com/WebService")
        String folder);

    /**
     * 
     * @param authTicket
     * @param job
     * @return
     *     returns org.atgas.sync.media.beyondTV.webservices.btvlibrary.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetItemsByJob", action = "http://www.snapstream.com/WebService/GetItemsByJob")
    @WebResult(name = "GetItemsByJobResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetItemsByJob", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetItemsByJob")
    @ResponseWrapper(localName = "GetItemsByJobResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetItemsByJobResponse")
    public ArrayOfPVSPropertyBag getItemsByJob(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "job", targetNamespace = "http://www.snapstream.com/WebService")
        String job);

    /**
     * 
     * @param authTicket
     * @param fullName
     * @return
     *     returns org.atgas.sync.media.beyondTV.webservices.types.PVSPropertyBag
     */
    @WebMethod(operationName = "GetMediaByFullName", action = "http://www.snapstream.com/WebService/GetMediaByFullName")
    @WebResult(name = "GetMediaByFullNameResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetMediaByFullName", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetMediaByFullName")
    @ResponseWrapper(localName = "GetMediaByFullNameResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetMediaByFullNameResponse")
    public PVSPropertyBag getMediaByFullName(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "fullName", targetNamespace = "http://www.snapstream.com/WebService")
        String fullName);

    /**
     * 
     * @param authTicket
     * @param driveName
     * @return
     *     returns org.atgas.sync.media.beyondTV.webservices.types.PVSPropertyBag
     */
    @WebMethod(operationName = "GetDriveInformationByName", action = "http://www.snapstream.com/WebService/GetDriveInformationByName")
    @WebResult(name = "GetDriveInformationByNameResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetDriveInformationByName", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetDriveInformationByName")
    @ResponseWrapper(localName = "GetDriveInformationByNameResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetDriveInformationByNameResponse")
    public PVSPropertyBag getDriveInformationByName(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "driveName", targetNamespace = "http://www.snapstream.com/WebService")
        String driveName);

    /**
     * 
     * @param authTicket
     * @param advancedSearchCCResult
     * @param numberOfResults
     * @param search
     * @param highlightStart
     * @param resultsPerPage
     * @param highlightEnd
     * @param ccSearch
     * @param pageNumber
     * @param numberOfPages
     * @param titleSearch
     * @param descSearch
     */
    @WebMethod(operationName = "AdvancedSearchCC", action = "http://www.snapstream.com/WebService/AdvancedSearchCC")
    @RequestWrapper(localName = "AdvancedSearchCC", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.AdvancedSearchCC")
    @ResponseWrapper(localName = "AdvancedSearchCCResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.AdvancedSearchCCResponse")
    public void advancedSearchCC(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "search", targetNamespace = "http://www.snapstream.com/WebService")
        String search,
        @WebParam(name = "pageNumber", targetNamespace = "http://www.snapstream.com/WebService")
        int pageNumber,
        @WebParam(name = "resultsPerPage", targetNamespace = "http://www.snapstream.com/WebService")
        int resultsPerPage,
        @WebParam(name = "titleSearch", targetNamespace = "http://www.snapstream.com/WebService")
        boolean titleSearch,
        @WebParam(name = "descSearch", targetNamespace = "http://www.snapstream.com/WebService")
        boolean descSearch,
        @WebParam(name = "ccSearch", targetNamespace = "http://www.snapstream.com/WebService")
        boolean ccSearch,
        @WebParam(name = "highlightStart", targetNamespace = "http://www.snapstream.com/WebService")
        String highlightStart,
        @WebParam(name = "highlightEnd", targetNamespace = "http://www.snapstream.com/WebService")
        String highlightEnd,
        @WebParam(name = "AdvancedSearchCCResult", targetNamespace = "http://www.snapstream.com/WebService", mode = WebParam.Mode.OUT)
        Holder<ArrayOfPVSPropertyBag> advancedSearchCCResult,
        @WebParam(name = "numberOfPages", targetNamespace = "http://www.snapstream.com/WebService", mode = WebParam.Mode.OUT)
        Holder<Integer> numberOfPages,
        @WebParam(name = "numberOfResults", targetNamespace = "http://www.snapstream.com/WebService", mode = WebParam.Mode.OUT)
        Holder<Integer> numberOfResults);

    /**
     * 
     * @param highlightStart
     * @param ccSearch
     * @param suggestionFormatted
     * @param titleSearch
     * @param suggestionStart
     * @param authTicket
     * @param suggestionEnd
     * @param numberOfResults
     * @param search
     * @param resultsPerPage
     * @param advancedSearchCCWithSuggestionResult
     * @param pageNumber
     * @param highlightEnd
     * @param suggestion
     * @param numberOfPages
     * @param descSearch
     */
    @WebMethod(operationName = "AdvancedSearchCCWithSuggestion", action = "http://www.snapstream.com/WebService/AdvancedSearchCCWithSuggestion")
    @RequestWrapper(localName = "AdvancedSearchCCWithSuggestion", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.AdvancedSearchCCWithSuggestion")
    @ResponseWrapper(localName = "AdvancedSearchCCWithSuggestionResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.AdvancedSearchCCWithSuggestionResponse")
    public void advancedSearchCCWithSuggestion(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "search", targetNamespace = "http://www.snapstream.com/WebService")
        String search,
        @WebParam(name = "pageNumber", targetNamespace = "http://www.snapstream.com/WebService")
        int pageNumber,
        @WebParam(name = "resultsPerPage", targetNamespace = "http://www.snapstream.com/WebService")
        int resultsPerPage,
        @WebParam(name = "titleSearch", targetNamespace = "http://www.snapstream.com/WebService")
        boolean titleSearch,
        @WebParam(name = "descSearch", targetNamespace = "http://www.snapstream.com/WebService")
        boolean descSearch,
        @WebParam(name = "ccSearch", targetNamespace = "http://www.snapstream.com/WebService")
        boolean ccSearch,
        @WebParam(name = "highlightStart", targetNamespace = "http://www.snapstream.com/WebService")
        String highlightStart,
        @WebParam(name = "highlightEnd", targetNamespace = "http://www.snapstream.com/WebService")
        String highlightEnd,
        @WebParam(name = "suggestionStart", targetNamespace = "http://www.snapstream.com/WebService")
        String suggestionStart,
        @WebParam(name = "suggestionEnd", targetNamespace = "http://www.snapstream.com/WebService")
        String suggestionEnd,
        @WebParam(name = "AdvancedSearchCCWithSuggestionResult", targetNamespace = "http://www.snapstream.com/WebService", mode = WebParam.Mode.OUT)
        Holder<ArrayOfPVSPropertyBag> advancedSearchCCWithSuggestionResult,
        @WebParam(name = "numberOfPages", targetNamespace = "http://www.snapstream.com/WebService", mode = WebParam.Mode.OUT)
        Holder<Integer> numberOfPages,
        @WebParam(name = "numberOfResults", targetNamespace = "http://www.snapstream.com/WebService", mode = WebParam.Mode.OUT)
        Holder<Integer> numberOfResults,
        @WebParam(name = "suggestion", targetNamespace = "http://www.snapstream.com/WebService", mode = WebParam.Mode.OUT)
        Holder<String> suggestion,
        @WebParam(name = "suggestionFormatted", targetNamespace = "http://www.snapstream.com/WebService", mode = WebParam.Mode.OUT)
        Holder<String> suggestionFormatted);

    /**
     * 
     * @param authTicket
     * @return
     *     returns long
     */
    @WebMethod(operationName = "GetOldestUnlockedMediaDateTicks", action = "http://www.snapstream.com/WebService/GetOldestUnlockedMediaDateTicks")
    @WebResult(name = "GetOldestUnlockedMediaDateTicksResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetOldestUnlockedMediaDateTicks", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetOldestUnlockedMediaDateTicks")
    @ResponseWrapper(localName = "GetOldestUnlockedMediaDateTicksResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetOldestUnlockedMediaDateTicksResponse")
    public long getOldestUnlockedMediaDateTicks(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     * @param search
     * @param ccSearch
     * @param titleSearch
     * @param descSearch
     * @return
     *     returns int
     */
    @WebMethod(operationName = "AdvancedSearchCCCount", action = "http://www.snapstream.com/WebService/AdvancedSearchCCCount")
    @WebResult(name = "AdvancedSearchCCCountResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "AdvancedSearchCCCount", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.AdvancedSearchCCCount")
    @ResponseWrapper(localName = "AdvancedSearchCCCountResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.AdvancedSearchCCCountResponse")
    public int advancedSearchCCCount(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "search", targetNamespace = "http://www.snapstream.com/WebService")
        String search,
        @WebParam(name = "titleSearch", targetNamespace = "http://www.snapstream.com/WebService")
        boolean titleSearch,
        @WebParam(name = "descSearch", targetNamespace = "http://www.snapstream.com/WebService")
        boolean descSearch,
        @WebParam(name = "ccSearch", targetNamespace = "http://www.snapstream.com/WebService")
        boolean ccSearch);

    /**
     * 
     * @param authTicket
     * @param suggestionEnd
     * @param search
     * @param advancedSearchCCCountWithSuggestionResult
     * @param ccSearch
     * @param suggestionFormatted
     * @param suggestion
     * @param titleSearch
     * @param descSearch
     * @param suggestionStart
     */
    @WebMethod(operationName = "AdvancedSearchCCCountWithSuggestion", action = "http://www.snapstream.com/WebService/AdvancedSearchCCCountWithSuggestion")
    @RequestWrapper(localName = "AdvancedSearchCCCountWithSuggestion", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.AdvancedSearchCCCountWithSuggestion")
    @ResponseWrapper(localName = "AdvancedSearchCCCountWithSuggestionResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.AdvancedSearchCCCountWithSuggestionResponse")
    public void advancedSearchCCCountWithSuggestion(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "search", targetNamespace = "http://www.snapstream.com/WebService")
        String search,
        @WebParam(name = "titleSearch", targetNamespace = "http://www.snapstream.com/WebService")
        boolean titleSearch,
        @WebParam(name = "descSearch", targetNamespace = "http://www.snapstream.com/WebService")
        boolean descSearch,
        @WebParam(name = "ccSearch", targetNamespace = "http://www.snapstream.com/WebService")
        boolean ccSearch,
        @WebParam(name = "suggestionStart", targetNamespace = "http://www.snapstream.com/WebService")
        String suggestionStart,
        @WebParam(name = "suggestionEnd", targetNamespace = "http://www.snapstream.com/WebService")
        String suggestionEnd,
        @WebParam(name = "AdvancedSearchCCCountWithSuggestionResult", targetNamespace = "http://www.snapstream.com/WebService", mode = WebParam.Mode.OUT)
        Holder<Integer> advancedSearchCCCountWithSuggestionResult,
        @WebParam(name = "suggestion", targetNamespace = "http://www.snapstream.com/WebService", mode = WebParam.Mode.OUT)
        Holder<String> suggestion,
        @WebParam(name = "suggestionFormatted", targetNamespace = "http://www.snapstream.com/WebService", mode = WebParam.Mode.OUT)
        Holder<String> suggestionFormatted);

    /**
     * 
     * @param authTicket
     * @param inputString
     * @param highlightStart
     * @param query
     * @param highlightEnd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LuceneHighlightString", action = "http://www.snapstream.com/WebService/LuceneHighlightString")
    @WebResult(name = "LuceneHighlightStringResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "LuceneHighlightString", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.LuceneHighlightString")
    @ResponseWrapper(localName = "LuceneHighlightStringResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.LuceneHighlightStringResponse")
    public String luceneHighlightString(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "inputString", targetNamespace = "http://www.snapstream.com/WebService")
        String inputString,
        @WebParam(name = "query", targetNamespace = "http://www.snapstream.com/WebService")
        String query,
        @WebParam(name = "highlightStart", targetNamespace = "http://www.snapstream.com/WebService")
        String highlightStart,
        @WebParam(name = "highlightEnd", targetNamespace = "http://www.snapstream.com/WebService")
        String highlightEnd);

    /**
     * 
     * @param authTicket
     * @return
     *     returns org.atgas.sync.media.beyondTV.webservices.btvlibrary.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetStatsInformation", action = "http://www.snapstream.com/WebService/GetStatsInformation")
    @WebResult(name = "GetStatsInformationResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetStatsInformation", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetStatsInformation")
    @ResponseWrapper(localName = "GetStatsInformationResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetStatsInformationResponse")
    public ArrayOfPVSPropertyBag getStatsInformation(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     * @param folderName
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetFolderMediaCount", action = "http://www.snapstream.com/WebService/GetFolderMediaCount")
    @WebResult(name = "GetFolderMediaCountResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetFolderMediaCount", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetFolderMediaCount")
    @ResponseWrapper(localName = "GetFolderMediaCountResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondTV.webservices.btvlibrary.GetFolderMediaCountResponse")
    public int getFolderMediaCount(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "folderName", targetNamespace = "http://www.snapstream.com/WebService")
        String folderName);

}
