
package org.atgas.sync.media.beyondtv.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.atgas.sync.media.beyondtv.webservices.btvsettings.ArrayOfPVSPropertyBag;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.3-b01-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BTVSettingsSoap", targetNamespace = "http://www.snapstream.com/WebService")
@XmlSeeAlso({
    org.atgas.sync.media.beyondtv.webservices.btvsettings.ObjectFactory.class,
    org.atgas.sync.media.beyondtv.webservices.types.ObjectFactory.class
})
public interface BTVSettingsSoap {


    /**
     * 
     * @param authTicket
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetNetURL", action = "http://www.snapstream.com/WebService/GetNetURL")
    @WebResult(name = "GetNetURLResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetNetURL", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetNetURL")
    @ResponseWrapper(localName = "GetNetURLResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetNetURLResponse")
    public String getNetURL(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     * @return
     *     returns long
     */
    @WebMethod(operationName = "GetValidRecordingFormats", action = "http://www.snapstream.com/WebService/GetValidRecordingFormats")
    @WebResult(name = "GetValidRecordingFormatsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetValidRecordingFormats", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetValidRecordingFormats")
    @ResponseWrapper(localName = "GetValidRecordingFormatsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetValidRecordingFormatsResponse")
    public long getValidRecordingFormats(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetProperty", action = "http://www.snapstream.com/WebService/GetProperty")
    @WebResult(name = "GetPropertyResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetProperty", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetProperty")
    @ResponseWrapper(localName = "GetPropertyResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetPropertyResponse")
    public String getProperty(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "name", targetNamespace = "http://www.snapstream.com/WebService")
        String name);

    /**
     * 
     * @param authTicket
     * @param name
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "GetPropertyAsBool", action = "http://www.snapstream.com/WebService/GetPropertyAsBool")
    @WebResult(name = "GetPropertyAsBoolResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetPropertyAsBool", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetPropertyAsBool")
    @ResponseWrapper(localName = "GetPropertyAsBoolResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetPropertyAsBoolResponse")
    public boolean getPropertyAsBool(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "name", targetNamespace = "http://www.snapstream.com/WebService")
        String name);

    /**
     * 
     * @param authTicket
     * @param name
     * @return
     *     returns long
     */
    @WebMethod(operationName = "GetPropertyAsInt", action = "http://www.snapstream.com/WebService/GetPropertyAsInt")
    @WebResult(name = "GetPropertyAsIntResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetPropertyAsInt", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetPropertyAsInt")
    @ResponseWrapper(localName = "GetPropertyAsIntResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetPropertyAsIntResponse")
    public long getPropertyAsInt(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "name", targetNamespace = "http://www.snapstream.com/WebService")
        String name);

    /**
     * 
     * @param authTicket
     * @param name
     * @return
     *     returns double
     */
    @WebMethod(operationName = "GetPropertyAsDouble", action = "http://www.snapstream.com/WebService/GetPropertyAsDouble")
    @WebResult(name = "GetPropertyAsDoubleResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetPropertyAsDouble", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetPropertyAsDouble")
    @ResponseWrapper(localName = "GetPropertyAsDoubleResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetPropertyAsDoubleResponse")
    public double getPropertyAsDouble(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "name", targetNamespace = "http://www.snapstream.com/WebService")
        String name);

    /**
     * 
     * @param authTicket
     * @param name
     * @param valueString
     */
    @WebMethod(operationName = "SetProperty", action = "http://www.snapstream.com/WebService/SetProperty")
    @RequestWrapper(localName = "SetProperty", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.SetProperty")
    @ResponseWrapper(localName = "SetPropertyResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.SetPropertyResponse")
    public void setProperty(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "name", targetNamespace = "http://www.snapstream.com/WebService")
        String name,
        @WebParam(name = "valueString", targetNamespace = "http://www.snapstream.com/WebService")
        String valueString);

    /**
     * 
     * @param val
     * @param authTicket
     * @param name
     */
    @WebMethod(operationName = "SetPropertyAsBool", action = "http://www.snapstream.com/WebService/SetPropertyAsBool")
    @RequestWrapper(localName = "SetPropertyAsBool", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.SetPropertyAsBool")
    @ResponseWrapper(localName = "SetPropertyAsBoolResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.SetPropertyAsBoolResponse")
    public void setPropertyAsBool(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "name", targetNamespace = "http://www.snapstream.com/WebService")
        String name,
        @WebParam(name = "val", targetNamespace = "http://www.snapstream.com/WebService")
        boolean val);

    /**
     * 
     * @param val
     * @param authTicket
     * @param name
     */
    @WebMethod(operationName = "SetPropertyAsInt", action = "http://www.snapstream.com/WebService/SetPropertyAsInt")
    @RequestWrapper(localName = "SetPropertyAsInt", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.SetPropertyAsInt")
    @ResponseWrapper(localName = "SetPropertyAsIntResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.SetPropertyAsIntResponse")
    public void setPropertyAsInt(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "name", targetNamespace = "http://www.snapstream.com/WebService")
        String name,
        @WebParam(name = "val", targetNamespace = "http://www.snapstream.com/WebService")
        long val);

    /**
     * 
     * @param val
     * @param authTicket
     * @param name
     */
    @WebMethod(operationName = "SetPropertyAsDouble", action = "http://www.snapstream.com/WebService/SetPropertyAsDouble")
    @RequestWrapper(localName = "SetPropertyAsDouble", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.SetPropertyAsDouble")
    @ResponseWrapper(localName = "SetPropertyAsDoubleResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.SetPropertyAsDoubleResponse")
    public void setPropertyAsDouble(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "name", targetNamespace = "http://www.snapstream.com/WebService")
        String name,
        @WebParam(name = "val", targetNamespace = "http://www.snapstream.com/WebService")
        double val);

    /**
     * 
     * @param authTicket
     * @param name
     * @return
     *     returns org.atgas.sync.media.beyondtv.webservices.btvsettings.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetPropertyBagCollection", action = "http://www.snapstream.com/WebService/GetPropertyBagCollection")
    @WebResult(name = "GetPropertyBagCollectionResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetPropertyBagCollection", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetPropertyBagCollection")
    @ResponseWrapper(localName = "GetPropertyBagCollectionResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetPropertyBagCollectionResponse")
    public ArrayOfPVSPropertyBag getPropertyBagCollection(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "name", targetNamespace = "http://www.snapstream.com/WebService")
        String name);

    /**
     * 
     * @param authTicket
     * @return
     *     returns org.atgas.sync.media.beyondtv.webservices.btvsettings.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetProfiles", action = "http://www.snapstream.com/WebService/GetProfiles")
    @WebResult(name = "GetProfilesResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetProfiles", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetProfiles")
    @ResponseWrapper(localName = "GetProfilesResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetProfilesResponse")
    public ArrayOfPVSPropertyBag getProfiles(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     * @return
     *     returns org.atgas.sync.media.beyondtv.webservices.btvsettings.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetDevices", action = "http://www.snapstream.com/WebService/GetDevices")
    @WebResult(name = "GetDevicesResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetDevices", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetDevices")
    @ResponseWrapper(localName = "GetDevicesResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetDevicesResponse")
    public ArrayOfPVSPropertyBag getDevices(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     * @param bSaveFile
     * @param bags
     */
    @WebMethod(operationName = "SetProfiles", action = "http://www.snapstream.com/WebService/SetProfiles")
    @RequestWrapper(localName = "SetProfiles", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.SetProfiles")
    @ResponseWrapper(localName = "SetProfilesResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.SetProfilesResponse")
    public void setProfiles(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        ArrayOfPVSPropertyBag bags,
        @WebParam(name = "bSaveFile", targetNamespace = "http://www.snapstream.com/WebService")
        int bSaveFile);

    /**
     * 
     * @param authTicket
     * @param bags
     */
    @WebMethod(operationName = "SetDevices", action = "http://www.snapstream.com/WebService/SetDevices")
    @RequestWrapper(localName = "SetDevices", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.SetDevices")
    @ResponseWrapper(localName = "SetDevicesResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.SetDevicesResponse")
    public void setDevices(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        ArrayOfPVSPropertyBag bags);

    /**
     * 
     * @param authTicket
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRadioLineup", action = "http://www.snapstream.com/WebService/GetRadioLineup")
    @WebResult(name = "GetRadioLineupResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetRadioLineup", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetRadioLineup")
    @ResponseWrapper(localName = "GetRadioLineupResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetRadioLineupResponse")
    public String getRadioLineup(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     */
    @WebMethod(operationName = "WriteSettingsToDisk", action = "http://www.snapstream.com/WebService/WriteSettingsToDisk")
    @RequestWrapper(localName = "WriteSettingsToDisk", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.WriteSettingsToDisk")
    @ResponseWrapper(localName = "WriteSettingsToDiskResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.WriteSettingsToDiskResponse")
    public void writeSettingsToDisk(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetUnifiedLineup", action = "http://www.snapstream.com/WebService/GetUnifiedLineup")
    @WebResult(name = "GetUnifiedLineupResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetUnifiedLineup", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetUnifiedLineup")
    @ResponseWrapper(localName = "GetUnifiedLineupResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetUnifiedLineupResponse")
    public String getUnifiedLineup(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetUnifiedLineupDisplayedChannels", action = "http://www.snapstream.com/WebService/GetUnifiedLineupDisplayedChannels")
    @WebResult(name = "GetUnifiedLineupDisplayedChannelsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetUnifiedLineupDisplayedChannels", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetUnifiedLineupDisplayedChannels")
    @ResponseWrapper(localName = "GetUnifiedLineupDisplayedChannelsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetUnifiedLineupDisplayedChannelsResponse")
    public String getUnifiedLineupDisplayedChannels(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetUserLineups", action = "http://www.snapstream.com/WebService/GetUserLineups")
    @WebResult(name = "GetUserLineupsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetUserLineups", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetUserLineups")
    @ResponseWrapper(localName = "GetUserLineupsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetUserLineupsResponse")
    public String getUserLineups(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBaseLineups", action = "http://www.snapstream.com/WebService/GetBaseLineups")
    @WebResult(name = "GetBaseLineupsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetBaseLineups", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetBaseLineups")
    @ResponseWrapper(localName = "GetBaseLineupsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetBaseLineupsResponse")
    public String getBaseLineups(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetFeature", action = "http://www.snapstream.com/WebService/GetFeature")
    @WebResult(name = "GetFeatureResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetFeature", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetFeature")
    @ResponseWrapper(localName = "GetFeatureResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetFeatureResponse")
    public String getFeature(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "name", targetNamespace = "http://www.snapstream.com/WebService")
        String name);

    /**
     * 
     * @param authTicket
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetOEMCode", action = "http://www.snapstream.com/WebService/GetOEMCode")
    @WebResult(name = "GetOEMCodeResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetOEMCode", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetOEMCode")
    @ResponseWrapper(localName = "GetOEMCodeResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvsettings.GetOEMCodeResponse")
    public int getOEMCode(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

}
