
package org.atgas.sync.media.beyondTV.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.3-b01-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BTVScheduler", targetNamespace = "http://www.snapstream.com/WebService", wsdlLocation = "http://localhost:8129/wsdl/BTVScheduler.asmx")
public class BTVScheduler
    extends Service
{

    private final static URL BTVSCHEDULER_WSDL_LOCATION;
    private final static WebServiceException BTVSCHEDULER_EXCEPTION;
    private final static QName BTVSCHEDULER_QNAME = new QName("http://www.snapstream.com/WebService", "BTVScheduler");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8129/wsdl/BTVScheduler.asmx");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BTVSCHEDULER_WSDL_LOCATION = url;
        BTVSCHEDULER_EXCEPTION = e;
    }

    public BTVScheduler() {
        super(__getWsdlLocation(), BTVSCHEDULER_QNAME);
    }

    public BTVScheduler(WebServiceFeature... features) {
        super(__getWsdlLocation(), BTVSCHEDULER_QNAME, features);
    }

    public BTVScheduler(URL wsdlLocation) {
        super(wsdlLocation, BTVSCHEDULER_QNAME);
    }

    public BTVScheduler(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BTVSCHEDULER_QNAME, features);
    }

    public BTVScheduler(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BTVScheduler(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BTVSchedulerSoap
     */
    @WebEndpoint(name = "BTVSchedulerSoap")
    public BTVSchedulerSoap getBTVSchedulerSoap() {
        return super.getPort(new QName("http://www.snapstream.com/WebService", "BTVSchedulerSoap"), BTVSchedulerSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BTVSchedulerSoap
     */
    @WebEndpoint(name = "BTVSchedulerSoap")
    public BTVSchedulerSoap getBTVSchedulerSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.snapstream.com/WebService", "BTVSchedulerSoap"), BTVSchedulerSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BTVSCHEDULER_EXCEPTION!= null) {
            throw BTVSCHEDULER_EXCEPTION;
        }
        return BTVSCHEDULER_WSDL_LOCATION;
    }

}
