
package org.atgas.sync.media.beyondtv.webservices;

import java.math.BigInteger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.atgas.sync.media.beyondtv.webservices.btvscheduler.ArrayOfPVSPropertyBag;
import org.atgas.sync.media.beyondtv.webservices.btvscheduler.ArrayOfPVSPropertyBagArray;
import org.atgas.sync.media.beyondtv.webservices.types.PVSPropertyBag;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BTVSchedulerSoap", targetNamespace = "http://www.snapstream.com/WebService")
@XmlSeeAlso({
    org.atgas.sync.media.beyondtv.webservices.types.ObjectFactory.class,
    org.atgas.sync.media.beyondtv.webservices.btvscheduler.ObjectFactory.class
})
public interface BTVSchedulerSoap {


    /**
     * 
     * @param authTicket
     * @return
     *     returns org.atgas.sync.media.beyondtv.webservices.btvscheduler.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetJobs", action = "http://www.snapstream.com/WebService/GetJobs")
    @WebResult(name = "GetJobsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetJobs", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetJobs")
    @ResponseWrapper(localName = "GetJobsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetJobsResponse")
    public ArrayOfPVSPropertyBag getJobs(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param guid
     * @param authTicket
     * @return
     *     returns org.atgas.sync.media.beyondtv.webservices.types.PVSPropertyBag
     */
    @WebMethod(operationName = "GetJobByGUID", action = "http://www.snapstream.com/WebService/GetJobByGUID")
    @WebResult(name = "GetJobByGUIDResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetJobByGUID", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetJobByGUID")
    @ResponseWrapper(localName = "GetJobByGUIDResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetJobByGUIDResponse")
    public PVSPropertyBag getJobByGUID(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        String guid);

    /**
     * 
     * @param authTicket
     * @return
     *     returns org.atgas.sync.media.beyondtv.webservices.btvscheduler.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetUpcomingRecordings", action = "http://www.snapstream.com/WebService/GetUpcomingRecordings")
    @WebResult(name = "GetUpcomingRecordingsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetUpcomingRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetUpcomingRecordings")
    @ResponseWrapper(localName = "GetUpcomingRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetUpcomingRecordingsResponse")
    public ArrayOfPVSPropertyBag getUpcomingRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     * @return
     *     returns java.math.BigInteger
     */
    @WebMethod(operationName = "GetLastRebuild", action = "http://www.snapstream.com/WebService/GetLastRebuild")
    @WebResult(name = "GetLastRebuildResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetLastRebuild", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetLastRebuild")
    @ResponseWrapper(localName = "GetLastRebuildResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetLastRebuildResponse")
    public BigInteger getLastRebuild(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param guid
     * @param authTicket
     * @param bag
     */
    @WebMethod(operationName = "EditRecordingJob", action = "http://www.snapstream.com/WebService/EditRecordingJob")
    @RequestWrapper(localName = "EditRecordingJob", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.EditRecordingJob")
    @ResponseWrapper(localName = "EditRecordingJobResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.EditRecordingJobResponse")
    public void editRecordingJob(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        String guid,
        @WebParam(name = "bag", targetNamespace = "http://www.snapstream.com/WebService")
        PVSPropertyBag bag);

    /**
     * 
     * @param authTicket
     * @return
     *     returns org.atgas.sync.media.beyondtv.webservices.btvscheduler.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetPossibleRecordings", action = "http://www.snapstream.com/WebService/GetPossibleRecordings")
    @WebResult(name = "GetPossibleRecordingsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetPossibleRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetPossibleRecordings")
    @ResponseWrapper(localName = "GetPossibleRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetPossibleRecordingsResponse")
    public ArrayOfPVSPropertyBag getPossibleRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     * @param bag
     * @return
     *     returns org.atgas.sync.media.beyondtv.webservices.types.PVSPropertyBag
     */
    @WebMethod(operationName = "GetEpisodeStatus", action = "http://www.snapstream.com/WebService/GetEpisodeStatus")
    @WebResult(name = "GetEpisodeStatusResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetEpisodeStatus", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetEpisodeStatus")
    @ResponseWrapper(localName = "GetEpisodeStatusResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetEpisodeStatusResponse")
    public PVSPropertyBag getEpisodeStatus(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "bag", targetNamespace = "http://www.snapstream.com/WebService")
        PVSPropertyBag bag);

    /**
     * 
     * @param authTicket
     * @param bags
     * @return
     *     returns org.atgas.sync.media.beyondtv.webservices.btvscheduler.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetEpisodeCollectionStatus", action = "http://www.snapstream.com/WebService/GetEpisodeCollectionStatus")
    @WebResult(name = "GetEpisodeCollectionStatusResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetEpisodeCollectionStatus", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetEpisodeCollectionStatus")
    @ResponseWrapper(localName = "GetEpisodeCollectionStatusResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetEpisodeCollectionStatusResponse")
    public ArrayOfPVSPropertyBag getEpisodeCollectionStatus(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        ArrayOfPVSPropertyBag bags);

    /**
     * 
     * @param authTicket
     * @return
     *     returns org.atgas.sync.media.beyondtv.webservices.btvscheduler.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetBlockedRecordings", action = "http://www.snapstream.com/WebService/GetBlockedRecordings")
    @WebResult(name = "GetBlockedRecordingsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetBlockedRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetBlockedRecordings")
    @ResponseWrapper(localName = "GetBlockedRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetBlockedRecordingsResponse")
    public ArrayOfPVSPropertyBag getBlockedRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param guid
     * @param authTicket
     * @return
     *     returns org.atgas.sync.media.beyondtv.webservices.btvscheduler.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetExistingConflicts", action = "http://www.snapstream.com/WebService/GetExistingConflicts")
    @WebResult(name = "GetExistingConflictsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetExistingConflicts", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetExistingConflicts")
    @ResponseWrapper(localName = "GetExistingConflictsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetExistingConflictsResponse")
    public ArrayOfPVSPropertyBag getExistingConflicts(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        String guid);

    /**
     * 
     * @param guid
     * @param authTicket
     * @return
     *     returns int
     */
    @WebMethod(operationName = "HasExistingConflicts", action = "http://www.snapstream.com/WebService/HasExistingConflicts")
    @WebResult(name = "HasExistingConflictsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "HasExistingConflicts", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.HasExistingConflicts")
    @ResponseWrapper(localName = "HasExistingConflictsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.HasExistingConflictsResponse")
    public int hasExistingConflicts(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        String guid);

    /**
     * 
     * @param authTicket
     * @param bag
     * @return
     *     returns org.atgas.sync.media.beyondtv.webservices.btvscheduler.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetPotentialConflicts", action = "http://www.snapstream.com/WebService/GetPotentialConflicts")
    @WebResult(name = "GetPotentialConflictsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetPotentialConflicts", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetPotentialConflicts")
    @ResponseWrapper(localName = "GetPotentialConflictsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetPotentialConflictsResponse")
    public ArrayOfPVSPropertyBag getPotentialConflicts(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "bag", targetNamespace = "http://www.snapstream.com/WebService")
        PVSPropertyBag bag);

    /**
     * 
     * @param authTicket
     * @param bag
     * @return
     *     returns int
     */
    @WebMethod(operationName = "HasPotentialConflicts", action = "http://www.snapstream.com/WebService/HasPotentialConflicts")
    @WebResult(name = "HasPotentialConflictsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "HasPotentialConflicts", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.HasPotentialConflicts")
    @ResponseWrapper(localName = "HasPotentialConflictsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.HasPotentialConflictsResponse")
    public int hasPotentialConflicts(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "bag", targetNamespace = "http://www.snapstream.com/WebService")
        PVSPropertyBag bag);

    /**
     * 
     * @param authTicket
     * @return
     *     returns org.atgas.sync.media.beyondtv.webservices.btvscheduler.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetForcedRecordings", action = "http://www.snapstream.com/WebService/GetForcedRecordings")
    @WebResult(name = "GetForcedRecordingsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetForcedRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetForcedRecordings")
    @ResponseWrapper(localName = "GetForcedRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetForcedRecordingsResponse")
    public ArrayOfPVSPropertyBag getForcedRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     * @return
     *     returns org.atgas.sync.media.beyondtv.webservices.btvscheduler.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetRejectedRecordings", action = "http://www.snapstream.com/WebService/GetRejectedRecordings")
    @WebResult(name = "GetRejectedRecordingsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetRejectedRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetRejectedRecordings")
    @ResponseWrapper(localName = "GetRejectedRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetRejectedRecordingsResponse")
    public ArrayOfPVSPropertyBag getRejectedRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     * @return
     *     returns org.atgas.sync.media.beyondtv.webservices.btvscheduler.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetRecentRecordings", action = "http://www.snapstream.com/WebService/GetRecentRecordings")
    @WebResult(name = "GetRecentRecordingsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetRecentRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetRecentRecordings")
    @ResponseWrapper(localName = "GetRecentRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetRecentRecordingsResponse")
    public ArrayOfPVSPropertyBag getRecentRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param guid
     * @param authTicket
     * @param priority
     */
    @WebMethod(operationName = "ReprioritizeJob", action = "http://www.snapstream.com/WebService/ReprioritizeJob")
    @RequestWrapper(localName = "ReprioritizeJob", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.ReprioritizeJob")
    @ResponseWrapper(localName = "ReprioritizeJobResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.ReprioritizeJobResponse")
    public void reprioritizeJob(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        String guid,
        @WebParam(name = "priority", targetNamespace = "http://www.snapstream.com/WebService")
        long priority);

    /**
     * 
     * @param guid
     * @param authTicket
     */
    @WebMethod(operationName = "RemoveRecordingJob", action = "http://www.snapstream.com/WebService/RemoveRecordingJob")
    @RequestWrapper(localName = "RemoveRecordingJob", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.RemoveRecordingJob")
    @ResponseWrapper(localName = "RemoveRecordingJobResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.RemoveRecordingJobResponse")
    public void removeRecordingJob(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        String guid);

    /**
     * 
     * @param authTicket
     * @param bags
     */
    @WebMethod(operationName = "RemoveRecordingJobs", action = "http://www.snapstream.com/WebService/RemoveRecordingJobs")
    @RequestWrapper(localName = "RemoveRecordingJobs", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.RemoveRecordingJobs")
    @ResponseWrapper(localName = "RemoveRecordingJobsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.RemoveRecordingJobsResponse")
    public void removeRecordingJobs(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        ArrayOfPVSPropertyBag bags);

    /**
     * 
     * @param authTicket
     * @param bag
     * @param highestPriority
     */
    @WebMethod(operationName = "AddRecordingJob", action = "http://www.snapstream.com/WebService/AddRecordingJob")
    @RequestWrapper(localName = "AddRecordingJob", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.AddRecordingJob")
    @ResponseWrapper(localName = "AddRecordingJobResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.AddRecordingJobResponse")
    public void addRecordingJob(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "bag", targetNamespace = "http://www.snapstream.com/WebService")
        PVSPropertyBag bag,
        @WebParam(name = "highestPriority", targetNamespace = "http://www.snapstream.com/WebService")
        int highestPriority);

    /**
     * 
     * @param authTicket
     * @param highestPriority
     * @param bags
     */
    @WebMethod(operationName = "AddRecordingJobs", action = "http://www.snapstream.com/WebService/AddRecordingJobs")
    @RequestWrapper(localName = "AddRecordingJobs", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.AddRecordingJobs")
    @ResponseWrapper(localName = "AddRecordingJobsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.AddRecordingJobsResponse")
    public void addRecordingJobs(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        ArrayOfPVSPropertyBag bags,
        @WebParam(name = "highestPriority", targetNamespace = "http://www.snapstream.com/WebService")
        int highestPriority);

    /**
     * 
     * @param guid
     * @param authTicket
     * @return
     *     returns org.atgas.sync.media.beyondtv.webservices.btvscheduler.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetRecordings", action = "http://www.snapstream.com/WebService/GetRecordings")
    @WebResult(name = "GetRecordingsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetRecordings")
    @ResponseWrapper(localName = "GetRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetRecordingsResponse")
    public ArrayOfPVSPropertyBag getRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        String guid);

    /**
     * 
     * @param authTicket
     * @param bag
     * @return
     *     returns org.atgas.sync.media.beyondtv.webservices.btvscheduler.ArrayOfPVSPropertyBag
     */
    @WebMethod(operationName = "GetPotentialRecordings", action = "http://www.snapstream.com/WebService/GetPotentialRecordings")
    @WebResult(name = "GetPotentialRecordingsResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetPotentialRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetPotentialRecordings")
    @ResponseWrapper(localName = "GetPotentialRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetPotentialRecordingsResponse")
    public ArrayOfPVSPropertyBag getPotentialRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "bag", targetNamespace = "http://www.snapstream.com/WebService")
        PVSPropertyBag bag);

    /**
     * 
     * @param authTicket
     * @return
     *     returns org.atgas.sync.media.beyondtv.webservices.types.PVSPropertyBag
     */
    @WebMethod(operationName = "GetNextRecording", action = "http://www.snapstream.com/WebService/GetNextRecording")
    @WebResult(name = "GetNextRecordingResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetNextRecording", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetNextRecording")
    @ResponseWrapper(localName = "GetNextRecordingResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetNextRecordingResponse")
    public PVSPropertyBag getNextRecording(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     * @param bags
     */
    @WebMethod(operationName = "AddBlockedRecordings", action = "http://www.snapstream.com/WebService/AddBlockedRecordings")
    @RequestWrapper(localName = "AddBlockedRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.AddBlockedRecordings")
    @ResponseWrapper(localName = "AddBlockedRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.AddBlockedRecordingsResponse")
    public void addBlockedRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        ArrayOfPVSPropertyBag bags);

    /**
     * 
     * @param authTicket
     * @param bags
     */
    @WebMethod(operationName = "AddForcedRecordings", action = "http://www.snapstream.com/WebService/AddForcedRecordings")
    @RequestWrapper(localName = "AddForcedRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.AddForcedRecordings")
    @ResponseWrapper(localName = "AddForcedRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.AddForcedRecordingsResponse")
    public void addForcedRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        ArrayOfPVSPropertyBag bags);

    /**
     * 
     * @param authTicket
     * @param bags
     */
    @WebMethod(operationName = "RemoveBlockedRecordings", action = "http://www.snapstream.com/WebService/RemoveBlockedRecordings")
    @RequestWrapper(localName = "RemoveBlockedRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.RemoveBlockedRecordings")
    @ResponseWrapper(localName = "RemoveBlockedRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.RemoveBlockedRecordingsResponse")
    public void removeBlockedRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        ArrayOfPVSPropertyBag bags);

    /**
     * 
     * @param authTicket
     * @param bags
     */
    @WebMethod(operationName = "RemoveForcedRecordings", action = "http://www.snapstream.com/WebService/RemoveForcedRecordings")
    @RequestWrapper(localName = "RemoveForcedRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.RemoveForcedRecordings")
    @ResponseWrapper(localName = "RemoveForcedRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.RemoveForcedRecordingsResponse")
    public void removeForcedRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        ArrayOfPVSPropertyBag bags);

    /**
     * 
     * @param authTicket
     * @param bags
     */
    @WebMethod(operationName = "RemoveBlockedRecordingsByGUID", action = "http://www.snapstream.com/WebService/RemoveBlockedRecordingsByGUID")
    @RequestWrapper(localName = "RemoveBlockedRecordingsByGUID", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.RemoveBlockedRecordingsByGUID")
    @ResponseWrapper(localName = "RemoveBlockedRecordingsByGUIDResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.RemoveBlockedRecordingsByGUIDResponse")
    public void removeBlockedRecordingsByGUID(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        ArrayOfPVSPropertyBag bags);

    /**
     * 
     * @param authTicket
     * @param bags
     */
    @WebMethod(operationName = "RemoveForcedRecordingsByGUID", action = "http://www.snapstream.com/WebService/RemoveForcedRecordingsByGUID")
    @RequestWrapper(localName = "RemoveForcedRecordingsByGUID", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.RemoveForcedRecordingsByGUID")
    @ResponseWrapper(localName = "RemoveForcedRecordingsByGUIDResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.RemoveForcedRecordingsByGUIDResponse")
    public void removeForcedRecordingsByGUID(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        ArrayOfPVSPropertyBag bags);

    /**
     * 
     * @param authTicket
     * @param bags
     */
    @WebMethod(operationName = "RemoveRecentRecordingsByGUID", action = "http://www.snapstream.com/WebService/RemoveRecentRecordingsByGUID")
    @RequestWrapper(localName = "RemoveRecentRecordingsByGUID", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.RemoveRecentRecordingsByGUID")
    @ResponseWrapper(localName = "RemoveRecentRecordingsByGUIDResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.RemoveRecentRecordingsByGUIDResponse")
    public void removeRecentRecordingsByGUID(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        ArrayOfPVSPropertyBag bags);

    /**
     * 
     * @param authTicket
     * @param bags
     */
    @WebMethod(operationName = "AddRecentRecordings", action = "http://www.snapstream.com/WebService/AddRecentRecordings")
    @RequestWrapper(localName = "AddRecentRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.AddRecentRecordings")
    @ResponseWrapper(localName = "AddRecentRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.AddRecentRecordingsResponse")
    public void addRecentRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        ArrayOfPVSPropertyBag bags);

    /**
     * 
     * @param authTicket
     * @param bags
     */
    @WebMethod(operationName = "RemoveRecentRecordings", action = "http://www.snapstream.com/WebService/RemoveRecentRecordings")
    @RequestWrapper(localName = "RemoveRecentRecordings", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.RemoveRecentRecordings")
    @ResponseWrapper(localName = "RemoveRecentRecordingsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.RemoveRecentRecordingsResponse")
    public void removeRecentRecordings(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        ArrayOfPVSPropertyBag bags);

    /**
     * 
     * @param authTicket
     * @param priority
     * @param bag
     * @return
     *     returns org.atgas.sync.media.beyondtv.webservices.btvscheduler.ArrayOfPVSPropertyBagArray
     */
    @WebMethod(operationName = "GetPotentialScheduleAtPriority", action = "http://www.snapstream.com/WebService/GetPotentialScheduleAtPriority")
    @WebResult(name = "GetPotentialScheduleAtPriorityResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetPotentialScheduleAtPriority", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetPotentialScheduleAtPriority")
    @ResponseWrapper(localName = "GetPotentialScheduleAtPriorityResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetPotentialScheduleAtPriorityResponse")
    public ArrayOfPVSPropertyBagArray getPotentialScheduleAtPriority(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "bag", targetNamespace = "http://www.snapstream.com/WebService")
        PVSPropertyBag bag,
        @WebParam(name = "priority", targetNamespace = "http://www.snapstream.com/WebService")
        long priority);

    /**
     * 
     * @param authTicket
     * @param bags
     */
    @WebMethod(operationName = "ReprioritizeJobs", action = "http://www.snapstream.com/WebService/ReprioritizeJobs")
    @RequestWrapper(localName = "ReprioritizeJobs", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.ReprioritizeJobs")
    @ResponseWrapper(localName = "ReprioritizeJobsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.ReprioritizeJobsResponse")
    public void reprioritizeJobs(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        ArrayOfPVSPropertyBag bags);

    /**
     * 
     * @param authTicket
     * @param bags
     */
    @WebMethod(operationName = "EditRecordingJobs", action = "http://www.snapstream.com/WebService/EditRecordingJobs")
    @RequestWrapper(localName = "EditRecordingJobs", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.EditRecordingJobs")
    @ResponseWrapper(localName = "EditRecordingJobsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.EditRecordingJobsResponse")
    public void editRecordingJobs(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "bags", targetNamespace = "http://www.snapstream.com/WebService")
        ArrayOfPVSPropertyBag bags);

    /**
     * 
     * @param authTicket
     * @param bstrEPGID
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "IsSeriesManaged", action = "http://www.snapstream.com/WebService/IsSeriesManaged")
    @WebResult(name = "IsSeriesManagedResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "IsSeriesManaged", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.IsSeriesManaged")
    @ResponseWrapper(localName = "IsSeriesManagedResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.IsSeriesManagedResponse")
    public boolean isSeriesManaged(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "bstrEPGID", targetNamespace = "http://www.snapstream.com/WebService")
        String bstrEPGID);

    /**
     * 
     * @param authTicket
     */
    @WebMethod(operationName = "ClearPopularityJobs", action = "http://www.snapstream.com/WebService/ClearPopularityJobs")
    @RequestWrapper(localName = "ClearPopularityJobs", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.ClearPopularityJobs")
    @ResponseWrapper(localName = "ClearPopularityJobsResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.ClearPopularityJobsResponse")
    public void clearPopularityJobs(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     * @return
     *     returns java.math.BigInteger
     */
    @WebMethod(operationName = "GetUpcomingRecordingDuration", action = "http://www.snapstream.com/WebService/GetUpcomingRecordingDuration")
    @WebResult(name = "GetUpcomingRecordingDurationResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetUpcomingRecordingDuration", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetUpcomingRecordingDuration")
    @ResponseWrapper(localName = "GetUpcomingRecordingDurationResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetUpcomingRecordingDurationResponse")
    public BigInteger getUpcomingRecordingDuration(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param authTicket
     * @return
     *     returns org.atgas.sync.media.beyondtv.webservices.types.PVSPropertyBag
     */
    @WebMethod(operationName = "GetLastRecording", action = "http://www.snapstream.com/WebService/GetLastRecording")
    @WebResult(name = "GetLastRecordingResult", targetNamespace = "http://www.snapstream.com/WebService")
    @RequestWrapper(localName = "GetLastRecording", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetLastRecording")
    @ResponseWrapper(localName = "GetLastRecordingResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.GetLastRecordingResponse")
    public PVSPropertyBag getLastRecording(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket);

    /**
     * 
     * @param guid
     * @param authTicket
     */
    @WebMethod(operationName = "AddRecentRecordingByGUID", action = "http://www.snapstream.com/WebService/AddRecentRecordingByGUID")
    @RequestWrapper(localName = "AddRecentRecordingByGUID", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.AddRecentRecordingByGUID")
    @ResponseWrapper(localName = "AddRecentRecordingByGUIDResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.AddRecentRecordingByGUIDResponse")
    public void addRecentRecordingByGUID(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        String guid);

    /**
     * 
     * @param guid
     * @param authTicket
     */
    @WebMethod(operationName = "AddBlockedRecordingByGUID", action = "http://www.snapstream.com/WebService/AddBlockedRecordingByGUID")
    @RequestWrapper(localName = "AddBlockedRecordingByGUID", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.AddBlockedRecordingByGUID")
    @ResponseWrapper(localName = "AddBlockedRecordingByGUIDResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.AddBlockedRecordingByGUIDResponse")
    public void addBlockedRecordingByGUID(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        String guid);

    /**
     * 
     * @param guid
     * @param authTicket
     */
    @WebMethod(operationName = "AddForcedRecordingByGUID", action = "http://www.snapstream.com/WebService/AddForcedRecordingByGUID")
    @RequestWrapper(localName = "AddForcedRecordingByGUID", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.AddForcedRecordingByGUID")
    @ResponseWrapper(localName = "AddForcedRecordingByGUIDResponse", targetNamespace = "http://www.snapstream.com/WebService", className = "org.atgas.sync.media.beyondtv.webservices.btvscheduler.AddForcedRecordingByGUIDResponse")
    public void addForcedRecordingByGUID(
        @WebParam(name = "authTicket", targetNamespace = "http://www.snapstream.com/WebService")
        String authTicket,
        @WebParam(name = "guid", targetNamespace = "http://www.snapstream.com/WebService")
        String guid);

}
