
package org.atgas.sync.media.beyondTV.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.3-b01-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BTVTaskListProcessor", targetNamespace = "http://www.snapstream.com/WebService", wsdlLocation = "http://localhost:8129/wsdl/BTVBatchProcessor.asmx")
public class BTVTaskListProcessor
    extends Service
{

    private final static URL BTVTASKLISTPROCESSOR_WSDL_LOCATION;
    private final static WebServiceException BTVTASKLISTPROCESSOR_EXCEPTION;
    private final static QName BTVTASKLISTPROCESSOR_QNAME = new QName("http://www.snapstream.com/WebService", "BTVTaskListProcessor");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8129/wsdl/BTVBatchProcessor.asmx");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BTVTASKLISTPROCESSOR_WSDL_LOCATION = url;
        BTVTASKLISTPROCESSOR_EXCEPTION = e;
    }

    public BTVTaskListProcessor() {
        super(__getWsdlLocation(), BTVTASKLISTPROCESSOR_QNAME);
    }

    public BTVTaskListProcessor(WebServiceFeature... features) {
        super(__getWsdlLocation(), BTVTASKLISTPROCESSOR_QNAME, features);
    }

    public BTVTaskListProcessor(URL wsdlLocation) {
        super(wsdlLocation, BTVTASKLISTPROCESSOR_QNAME);
    }

    public BTVTaskListProcessor(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BTVTASKLISTPROCESSOR_QNAME, features);
    }

    public BTVTaskListProcessor(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BTVTaskListProcessor(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BTVTaskListProcessorSoap
     */
    @WebEndpoint(name = "BTVTaskListProcessorSoap")
    public BTVTaskListProcessorSoap getBTVTaskListProcessorSoap() {
        return super.getPort(new QName("http://www.snapstream.com/WebService", "BTVTaskListProcessorSoap"), BTVTaskListProcessorSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BTVTaskListProcessorSoap
     */
    @WebEndpoint(name = "BTVTaskListProcessorSoap")
    public BTVTaskListProcessorSoap getBTVTaskListProcessorSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.snapstream.com/WebService", "BTVTaskListProcessorSoap"), BTVTaskListProcessorSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BTVTASKLISTPROCESSOR_EXCEPTION!= null) {
            throw BTVTASKLISTPROCESSOR_EXCEPTION;
        }
        return BTVTASKLISTPROCESSOR_WSDL_LOCATION;
    }

}
