
package org.atgas.media.beyondtv.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BTVScheduler", targetNamespace = "http://www.snapstream.com/WebService", wsdlLocation = "http://localhost:8129/wsdl/BTVScheduler.asmx")
public class BTVScheduler
    extends Service
{

    private final static URL BTVSCHEDULER_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.atgas.media.beyondtv.webservices.BTVScheduler.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.atgas.media.beyondtv.webservices.BTVScheduler.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8129/wsdl/BTVScheduler.asmx");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8129/wsdl/BTVScheduler.asmx', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BTVSCHEDULER_WSDL_LOCATION = url;
    }

    public BTVScheduler(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BTVScheduler() {
        super(BTVSCHEDULER_WSDL_LOCATION, new QName("http://www.snapstream.com/WebService", "BTVScheduler"));
    }

    /**
     * 
     * @return
     *     returns BTVSchedulerSoap
     */
    @WebEndpoint(name = "BTVSchedulerSoap")
    public BTVSchedulerSoap getBTVSchedulerSoap() {
        return super.getPort(new QName("http://www.snapstream.com/WebService", "BTVSchedulerSoap"), BTVSchedulerSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BTVSchedulerSoap
     */
    @WebEndpoint(name = "BTVSchedulerSoap")
    public BTVSchedulerSoap getBTVSchedulerSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.snapstream.com/WebService", "BTVSchedulerSoap"), BTVSchedulerSoap.class, features);
    }

}
